configfile: "config.yaml"

###### paths ###############
DATA = config["general_paths"]["data"]
SRC = config["general_paths"]["src"]
CONDA_ENVS = config["general_paths"]["conda_envs"]
METADATA = config["paths"]["metadata"]
DATABASE = config["paths"]["database"]
GENE_SETS_DIR = config["paths"]["gene_sets_dir"]
SPLSDA_ANALYSIS_DIR = config["paths"]["splsda_analysis"]
GO_TRANSFERS = config["paths"]["go_transfers"]
MOTIF_ANALYSIS_DIR = config["paths"]["motif_analysis_dir"]
TS_GAINS_LOSSES_DIR = config["paths"]["ts_gains_and_losses_dir"]

######## tools ############
RSCRIPT = config["tools"]["rscript"]

###### variables ###########
MY_VERSION = config["variables"]["my_version"]
MY_CATEGORY = config["variables"]["my_category"]
ALL_SPECIES = config["variables"]["all_species"]
ALL_SPECIES_GAINS = config["variables"]["all_species_gains"]
BILATERIA = ALL_SPECIES
VERTEBRATA = config["variables"]["vertebrata"]
INSECTA = config["variables"]["insecta"]
OUTGROUPS = config["variables"]["outgroups"]
DEUTEROSTOMA = config["variables"]["deuterostoma"]
PROTOSTOMA = config["variables"]["protostoma"]
CLADES = config["variables"]["clades"]

CLADE_SPECIES_DICT = {}
CLADE_SPECIES_DICT["Vertebrata"] = VERTEBRATA
CLADE_SPECIES_DICT["Insecta"] = INSECTA
CLADE_SPECIES_DICT["Bilateria"] = BILATERIA

CATEGORIES = config["variables"]["categories"]
EVO_TYPES = config["variables"]["evo_types"]
EXPR_TYPES = config["variables"]["expr_types"]
ALL_TISSUES = config["variables"]["all_tissues"]
MOTIF_CATEGORIES = config["variables"]["motif_categories"]
NODE_SPECIES_DICT = config["variables"]["node_species_dict"]
ALL_NODES = config["variables"]["all_nodes"]
NODE_SUBNODES_DICT = config["variables"]["node_subnodes_dict"]
SPECIES_SUBCLADES_DICT = config["variables"]["species_subclades_dict"]

###### targets ##########

####### rules ############
rule all:	
	input:
	
#######################################
###### ANCESTRAL BILATERIAN INPUTS ####
#######################################

rule generate_ancestral_bilaterian_sets:
	input:
		BH_orthogroups = GENE_SETS_DIR+"/{my_version}/STRICT/Bilateria/conserved/Bilateria_conserved-reclustered_orthogroups-BH_genes.txt",
		OG_IDs = SPLSDA_ANALYSIS_DIR+"/{my_version}/STRICT/Bilateria/conserved/loadings/metasamples_median_expr/splsda_zscore_comb/{tissue}_splsda-zscore_loadings_orthogroups-GO_input.txt"
	output:
		MOTIF_ANALYSIS_DIR+"/{my_version}/gene_sets_inputs/Bilateria_ancestral/{tissue}/{species}-{tissue}-Bilateria_ancestral_geneIDs.txt"
	shell:
		"""
		cat {input.BH_orthogroups} | grep {wildcards.species} | filter_1col 1 {input.OG_IDs} | cut -f3 | sort | uniq > {output}
		"""


#######################################
###### CLADE-SPECIFIC INPUTS ##########
#######################################

rule generate_clade_specific_sets:
	input:
		BH_orthogroups = GENE_SETS_DIR+"/{my_version}/STRICT/Bilateria/conserved/Bilateria_conserved-reclustered_orthogroups-BH_genes.txt",
		OG_IDs = SPLSDA_ANALYSIS_DIR+"/{my_version}/STRICT/Bilateria/conserved/loadings_clade_tissue/metasamples_median_expr/{tissue}/splsda_zscore_comb/{clade}_{tissue}_splsda-zscore_loadings_orthogroups-GO_input.txt"
	output:
		MOTIF_ANALYSIS_DIR+"/{my_version}/gene_sets_inputs/{clade}_specific/{tissue}/{species}-{tissue}-{clade}_specific_geneIDs.txt"
	shell:
		"""
		cat {input.BH_orthogroups} | grep {wildcards.species} | filter_1col 1 {input.OG_IDs} | cut -f3 | sort | uniq > {output}
		"""

#######################################
###### BACKGROUNDS ####################
#######################################

#This is the BH background
rule generate_backgrounds:
	input:
		GENE_SETS_DIR+"/{my_version}/STRICT/Bilateria/conserved/Bilateria_conserved-reclustered_orthogroups-BH_genes.txt"
	output:
		MOTIF_ANALYSIS_DIR+"/{my_version}/backgrounds/{species}-all_bilaterian_conserved_BH_genes.txt"
	shell:
		"""
		cat {input} | grep {wildcards.species} | cut -f3 | sort | uniq > {output}
		"""

#I am now getting all the bilaterian conserved genes for each species which were not included in the BH background.
rule generate_complementary_background:
	input:
		bilaterian_conserved_orthogroups = GENE_SETS_DIR+"/{my_version}/STRICT/Bilateria/conserved/Bilateria_conserved_orthogroups-EXPR_genes.txt",
		BH_orthogroups = GENE_SETS_DIR+"/{my_version}/STRICT/Bilateria/conserved/Bilateria_conserved-reclustered_orthogroups-BH_genes.txt"
	output:
		MOTIF_ANALYSIS_DIR+"/{my_version}/backgrounds_complementary/{species}-all_bilaterian_conserved_nonBH_genes.txt"
	shell:
		"""
		cat {input.bilaterian_conserved_orthogroups} | grep {wildcards.species} | cut -f3 | sort | uniq | filter_1col -v 1 \
		<(cat {input.BH_orthogroups} | grep {wildcards.species} | cut -f3) > {output}
		"""
