general_paths:
  conda_envs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/conda_envs"

paths:
  database: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB"
  broccoli_revision: "/users/mirimia/fmantica/projects/bilaterian_GE/data/broccoli_revision"
  metasamples_quant_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/norm_counts_quant/metasamples_quantification"
  tissues_quant_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/norm_counts_quant/tissues_average_quantification"
  preprocessing_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all"
  quantification: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/kallisto_out"
  metadata: "/users/mirimia/fmantica/projects/bilaterian_GE/data/samples_metadata"
  pfam_raw_files: "/users/mirimia/fmantica/projects/bilaterian_GE/data/PFAM_transfers/raw_files"
  pfam_transfers: "/users/mirimia/fmantica/projects/bilaterian_GE/data/PFAM_transfers"
  ts_gains_losses_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_losses/species_QN_5_TPM_v6/All_version2"
  GO_raw_files: "downloaded_files"
  GO_transfers: "/users/mirimia/fmantica/projects/bilaterian_GE/data/GO_transfers"
  ts_call_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_call"
  tau_revision: "/users/mirimia/fmantica/projects/bilaterian_GE/data/tau_revision"
  ts_gains_losses_revision_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_losses_revision"

tools:
  broccoli_main: "/users/mirimia/fmantica/software/Broccoli-master-2/broccoli.py"
  filter_orthogroups: "bin/filter_orthogroups.py"
  quantile_normalize: "bin/quantile_normalize.R"
  compute_zscore_by_species: "bin/compute_zscore_by_species.R"
  convert_stk_to_tab: "bin/convert_stockholm_to_tab.py"
  transfer_go: "bin/TransferGOs_toOrthogroups.py"
  transfer_clade_specific_go: "bin/TransferGOs_toOrthogroups-clade_specific.py"
  get_gtm_files: "bin/get_gmt_files.py"
  run_gprofiler2: "bin/run_gprofiler2.R"
  average_all_samples_expr_by_tissue: "bin/average_all_samples_expr_by_tissue.py"
  average_metasample_expr_by_tissue: "bin/average_metasample_expr_by_tissue.py"
  median_sample_expr_by_metasample: "bin/median_sample_expr_by_metasample.py"
  compute_tau: "bin/compute_tau-v3.py"
  infer_ts_gains: "bin/infer_ts_gains-v14.py"
  infer_ts_losses: "bin/infer_ts_losses-v14.py" 

variables:
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi"]
  species_clades: ["vertebrata", "insecta"]
  max_genes: 80
  max_proportion: 0.12
  clade_species_dict: {"vertebrata" : ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"], "insecta" : ["Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi"], "bilateria" : ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]}
  expr_types: ["metasamples_median_expr", "tissue_average_expr"]
  all_tissues: ["Neural", "Testis", "Ovary", "Muscle", "Kidney", "Epithelial", "DigestiveTract", "Adipose"]
  vertebrata_nodes: ["Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata"]
  insecta_nodes: ["Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta"]
  inference_types: ["gains", "losses"]
  all_tissues: ["Neural", "Testis", "Ovary", "Muscle", "Kidney", "Epithelial", "DigestiveTract", "Adipose"]
  annotation_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Dme", "Aae", "Bmo", "Tca", "Ame"]
  annotation_species_dict: {"vertebrata" : ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"], "insecta" : ["Dme", "Aae", "Bmo", "Tca", "Ame"]}
  min_OGs_clade_specific_transfers: 2
  tau_categories: ["all_samples_average", "random_metasamples_average"]
  tau_up_cutoff: 0.75
  tau_low_cutoff: 0.60
  tau_low_cutoff_losses: 0.45
  tissue_diff_cutoff: 0.1
  all_nodes: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi", "Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma", "Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma", "Bilateria"]
  ancestral_clades: ["Chordata", "Deuterostoma", "Arthropoda", "Protostoma", "Vertebrata", "Insecta"]
  node_name_dict: '{"Hs2":"Hs2", "Hs2;Mm2":"Euarchontoglires", "Mm2":"Euarchontoglires", "Bt2":"Eutheria", "Mdo":"Mammalia", "Gga":"Amniota", "Xtr":"Tetrapoda", "Dre":"Euteleostomi", "Cmi":"Vertebrata", "Bla":"Chordata", "Sp2":"Deuterostoma", "Dme":"Dme", "Dme;Eba":"Cyclorrapha", "Eba":"Cyclorrapha", "Aae":"Diptera", "Bmo":"Panorpidae", "Tca":"Oligoneoptera", "Ame":"Holometabola", "Bge":"Neoptera", "Cdi":"Insecta", "Sma":"Arthropoda", "Obi":"Protostoma"}'
  deuterostome_nodes: ["Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma"]
  protostome_nodes: ["Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma"]
  node_species_dict: '{"Euarchontoglires":["Hs2","Mm2"], "Eutheria":["Hs2","Mm2","Bt2"], "Mammalia":["Hs2","Mm2","Bt2","Mdo"], "Amniota":["Hs2","Mm2","Bt2","Mdo","Gga"], "Tetrapoda":["Hs2","Mm2","Bt2","Mdo","Gga","Xtr"], "Euteleostomi":["Hs2","Mm2","Bt2","Mdo","Gga","Xtr","Dre"], "Vertebrata":["Hs2","Mm2","Bt2","Mdo","Gga","Xtr","Dre","Cmi"], "Chordata":["Hs2","Mm2","Bt2","Mdo","Gga","Xtr","Dre","Cmi","Bla"], "Deuterostoma":["Hs2","Mm2","Bt2","Mdo","Gga","Xtr","Dre","Cmi","Bla","Sp2"], "Cyclorrapha":["Dme","Eba"], "Diptera":["Dme","Eba","Aae"], "Panorpidae":["Dme","Eba","Aae","Bmo"], "Oligoneoptera":["Dme","Eba","Aae","Bmo","Tca"], "Holometabola":["Dme","Eba","Aae","Bmo","Tca","Ame"], "Neoptera":["Dme","Eba","Aae","Bmo","Tca","Ame","Bge"], "Insecta":["Dme","Eba","Aae","Bmo","Tca","Ame","Bge","Cdi"], "Arthropoda":["Dme","Eba","Aae","Bmo","Tca","Ame","Bge","Cdi","Sma"], "Protostoma":["Dme","Eba","Aae","Bmo","Tca","Ame","Bge","Cdi","Sma","Obi"], "Bilateria":["Hs2","Mm2","Bt2","Mdo","Gga","Xtr","Dre","Cmi","Bla","Sp2","Dme","Eba","Aae","Bmo","Tca","Ame","Bge","Cdi","Sma","Obi"]}'
  deuterostoma: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2"]
  protostoma: ["Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]

