general_paths:
  data: "/users/mirimia/fmantica/projects/bilaterian_GE/data"
  src: "/users/mirimia/fmantica/projects/bilaterian_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/conda_envs"

paths:
  metadata: "/users/mirimia/fmantica/projects/bilaterian_GE/data/samples_metadata"
  corrected_gtfs: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/corrected_gtf"
  metasamples_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/metasamples" 
  average_expr_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/average_expr_by_tissue"
  gene_sets_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/gene_sets"
  pca_analysis: "/users/mirimia/fmantica/projects/bilaterian_GE/data/pca_analysis"
  splsda_analysis: "/users/mirimia/fmantica/projects/bilaterian_GE/data/splsda_analysis"
  ts_call_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_call" 
 
tools:
  compute_tau: "bin/compute_tau.py"
  compute_cv: "bin/compute_cv.py"
  compute_relative_ts: "bin/compute_relative_ts.py"
  get_protein_coding_genes_from_gtf: "bin/get_protein_coding_genes_from_gtf.py" 
  associate_tissue_with_ts: "bin/associate_tissue_with_ts.py"

variables:
  my_version: "All_version"
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi"]
  deuterostoma: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2"]
  protostoma: ["Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  clades: ["Vertebrata", "Insecta", "Bilateria"]
  evo_types: ["conserved"]
  categories: ["STRICT"]
  expr_types: ["metasamples", "tissues"]
  all_tissues: ["Neural", "Muscle", "Testis", "Ovary", "Epithelial", "Kidney", "DigestiveTract", "Adipose"] 
  tau_cutoff: ["0.75", "0.60", "0.45", 0]
