general_paths:
  data: "/users/mirimia/fmantica/projects/bilaterian_GE/data"
  src: "/users/mirimia/fmantica/projects/bilaterian_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/conda_envs"

paths:
  metadata: "/users/mirimia/fmantica/projects/bilaterian_GE/data/samples_metadata"
  fastq_dir: "/no_backup/mirimia/fmantica/bilaterian_GE_fastq"
  fastQC_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing/fastQC"
  quantification: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing/kallisto_out"
  sva_correction: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing/sva_correction"
  genome_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/genomes"
  gtf_ref: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/corrected_gtf/ref"
  metasamples_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing/kmeans_clustering" 
 
tools:
  compute_log2: "/users/mirimia/fmantica/projects/bilaterian_GE/src/R/compute_log2.R"
  generate_sva_metadata: "/users/mirimia/fmantica/projects/bilaterian_GE/src/R/generate_sva_metadata.R"
  apply_sva_correction: "/users/mirimia/fmantica/projects/bilaterian_GE/src/R/transcriptome_curation2.r"
  get_gene_level_quantification: "/users/mirimia/fmantica/projects/bilaterian_GE/src/R/get_gene_level_quantification.R"
  generate_metasamples_kmeans: "/users/mirimia/fmantica/projects/bilaterian_GE/src/R/generate_metasamples_kmeans.R"

variables:
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Cmi", "Bla", "Spu", "Eba", "Aae", "Bmo", "Tca", "Bge", "Ame", "Cdi", "Sma", "Obi", "Dr2", "Dme"]
  download_threads_num: 8
  min_read_len: 49
  sva_tissues: "Neural|Muscle|Testis|Ovary|Kidney|Epithelial|DigestiveTract|Adipose"
