general_paths:
  data: "/users/mirimia/fmantica/projects/bilaterian_GE/data"
  src: "/users/mirimia/fmantica/projects/bilaterian_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/conda_envs"

paths:
  metadata: "/users/mirimia/fmantica/projects/bilaterian_GE/data/samples_metadata"
  metasamples_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/metasamples" 
  average_expr_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/preprocessing_all/average_expr_by_tissue"
  gene_sets_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/gene_sets"
  pca_analysis: "/users/mirimia/fmantica/projects/bilaterian_GE/data/pca_analysis"
  splsda_analysis: "/users/mirimia/fmantica/projects/bilaterian_GE/data/splsda_analysis"
  diff_expr_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/differential_expression"
 
tools:
  run_deseq2: "bin/run_DESeq2.R"
  get_gtm_files: "bin/get_gmt_files.py"
  run_gprofiler2: "bin/run_gprofiler2.R"
  filter_DE_genes: "bin/filter_DE_genes.R"

variables:
  my_version: "All_version"
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  vertebrata: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi"]
  insecta: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi"]
  deuterostoma: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2"]
  protostoma: ["Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  outgroups: ["Bla", "Sp2", "Sma", "Obi"]
  clades: ["Vertebrata", "Insecta", "Bilateria"]
  evo_types: ["conserved", "specific"]
  categories: ["STRICT"]
  expr_types: ["metasamples", "tissues"]
  all_tissues: ["Neural", "Muscle", "Testis", "Ovary", "Epithelial", "Kidney", "DigestiveTract", "Adipose"] 
  higher_GO_cutoff: 2000
  lower_GO_cutoff: 3
  log2fc_cutoff: 2
  pvalue_cutoff: 0.05
  DE_types: ["All", "filtered"] 
