general_paths:
  data: "/users/mirimia/fmantica/projects/bilaterian_GE/data"
  src: "/users/mirimia/fmantica/projects/bilaterian_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/conda_envs"

paths:
  GO_raw_files: "/users/mirimia/fmantica/projects/bilaterian_GE/src/snakemake/4_GO_TRANSFERS/downloaded_files"
  GO_transfers: "/users/mirimia/fmantica/projects/bilaterian_GE/data/GO_transfers"
  orthogroups_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/broccoli/" 
  clueGO_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/src/snakemake/4_GO_TRANSFERS/downloaded_files/clueGO"

tools:
  retrieve_ensembl_IDs: "bin/retrieve_ensembl_IDs.py"
  get_cluego_annot: "bin/get_clueGO_annot.py"
 
variables:
  my_version: "All_version"
  cluego_cat: ["BiologicalProcess", "MolecularFunction", "CellularComponent"]
