---
title: "EDF3"
output: html_document
---

```{r setup, include=FALSE}
#set Knitr option
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

#upload libraries
library(ggplot2)
library(extrafont)
library(hashmap)
library(reshape2)
library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(impute)
library(tidyverse)
library(kableExtra)

#set directories
home="/Users/federica/mnt/"
gene_sets_dir=paste0(home, "projects/bilaterian_GE/data/gene_sets/")
#tissue_expr_dir=paste0(home, "projects/bilaterian_GE/data/preprocessing/average_expr_by_tissue/")
pca_dir=paste0(home, "projects/bilaterian_GE/data/pca_analysis_all_norms/")
metadata_dir=paste0(home, "projects/bilaterian_GE/data/samples_metadata/")
splsda_dir= paste0(home, "projects/bilaterian_GE/data/splsda_analysis/")
diff_expr_dir = paste0(home, "projects/bilaterian_GE/data/differential_expression/")

#set variables
my_version = "All_version2"
my_category = "STRICT"
my_evo_type = "conserved"
clades = c("Vertebrata", "Insecta", "Bilateria")
clades_PCA = c("Vertebrata", "Insecta", "Bilateria")
options("scipen"=100, "digits"=4)

all_species = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi")
ordered_species = all_species
Bilateria = all_species
Vertebrata = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi")
Insecta = c("Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi")
Outgroups = c("Bla", "Sp2", "Sma", "Obi")
all_tissues=c("Adipose", "DigestiveTract", "Kidney", "Epithelial", "Muscle", "Neural", "Ovary", "Testis")
ordered_tissues = c("Neural", "Testis", "Ovary", "Muscle", "Kidney", "Epithelial", "DigestiveTract", "Adipose")

#set aestetics vectors
my_color_vector = c("Neural"="mediumblue", "Testis"="violet", "Ovary"="darkorchid", "Muscle"="springgreen3", 
                    "Kidney"="gold", "Epithelial"="steelblue1", "DigestiveTract"="chocolate1", "Adipose"="firebrick1")
my_shapes_vector = c("Hs2"=0, "Mm2"=1, "Bt2"=2, "Mdo"=3, "Gga"=4, "Xtr"=5, "Dre"=6, "Cmi"=7, "Bla"=9, "Sp2"=8, 
                     "Dme"=15, "Eba"=18, "Aae"= 23, "BmA"=25, "Tca"=17, "Bge"=10, "Ame"=16, "Cdi"=13, "Sma"=14, "Obi"=11)
my_alpha_vector=c("Hs2"=1, "Mm2"=1, "Bt2"=1, "Mdo"=1, "Gga"=1, "Xtr"=1, "Dre"=1, "Cmi"=1, "Bla"=0.5, "Sp2"=0.5, "Sma"=0.5, "Ame"=0.5, "Dme"=0.5, "Cdi"=0.5, "Obi"=0.5, "Bge"=0.5, "BmA"=0.5, "Tca"=0.5)
my_sets_color = c("Vertebrata"= "mediumorchid", "Deuterostoma"="olivedrab3", "Insecta"="tan3", "Protostoma"="yellow", "Bilateria"="firebrick1", "Outgroups"="dimgray")
my_species_colors=c("Hs2"="#00BFFF", "Mm2"="#159DFF", "Bt2"="#1873CD", "Mdo"="#174B8B", "Gga"="#3F3F8B", "Xtr"="#64398B", "Dre"="#82359D", "Cmi"="#9932CC", "Bla"="#2E8B57", "Sp2"="#96B12B", "Obi"="#FFFF00", "Sma"="#FFCC33", "Cdi"="goldenrod", "Bge"="burlywood2", "Ame"="#FF9966", "Tca"="#FF6600", "BmA"="#CC6600", "Aae"="#993300", "Eba"="firebrick3", "Dme"="red")
my_copy_status_colors = c("single_copy_ortholog"="gray18", "duplicated"="gray76")

#Create named vector with PC and corresponding tissue
PC_tissue_named_vector = c("1"="Neural", "2"="Testis", "3"="Ovary", 
                          "4"="Muscle", "5"="DigestiveTract", "6"="Epithelial", 
                          "7"="Kidney", "8"="Adipose")


tissue_PC_vector = c("Neural"="Negative_PC1",
                     "Testis"="Positive_PC2",
                     "Ovary"="Negative_PC3",
                     "Muscle"="Positive_PC4",
                     "DigestiveTract"="Negative_PC5",
                     "Epithelial"="Positive_PC6",
                     "Kidney"="Negative_PC7",
                     "Adipose"="Negative_PC8")

#Plot aestetics
paletteLength = 75
my_sets_color = c("Vertebrata"= "mediumorchid", "Insecta"="tan3", "Outgroups"="dimgray")
palette_brewer = colorRampPalette(rev(brewer.pal(11, "RdBu")))(paletteLength)

#Phenotypes variables
all_categories = c("Mammals_and_fly", "Mammals_only", "Fly_only", "Mammals_or_fly", "Neither_mammals_nor_fly")
phenotype_categories = c("Mammals_and_fly", "Mammals_only", "Fly_only", "Neither_mammals_nor_fly")
phenotype_categories_colors = c("Mammals_and_fly"="forestgreen", "Mammals_only"="olivedrab3", "Fly_only"="coral3", "Neither_mammals_nor_fly"="brown")

#Ancestrality variables
ancestry_categories = c("Pre_bilaterian", "Bilaterian", "Unclassified")
ancestry_categories_colors = c("Pre_bilaterian"="dodgerblue3", "Bilaterian"="rosybrown4", "Unclassified"="rosybrown1")
```

```{r functions, warning=FALSE, message=FALSE, echo=FALSE, dependson="setup"}
number_ticks <- function(n) {function(limits) pretty(limits, n)}

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

plot_gene_expr = function(original_OG_ID, loadings_expr_df_long, OGID_humanID_dict, Vertebrata, Insecta, Outgroups) {
  all_plots = list()
  i = 1
  for (clade in c("Vertebrata", "Insecta", "Outgroups")) {
    my_OG_ID = paste0(OGID_humanID_dict$find(original_OG_ID), " ~ ", original_OG_ID)
    OG_expr_df = subset(loadings_expr_df_long, OG_ID == original_OG_ID)
    my_max = max(OG_expr_df$Expr, na.rm=TRUE)
    my_min = min(OG_expr_df$Expr, na.rm=TRUE)
    if (clade == "Vertebrata") {OG_expr_df = subset(OG_expr_df, Species %in% Vertebrata)}
    if (clade == "Insecta") {OG_expr_df = subset(OG_expr_df, Species %in% Insecta)}
    if (clade == "Outgroups") {OG_expr_df = subset(OG_expr_df, Species %in% Outgroups)}
    
    expr_plot = ggplot(data=OG_expr_df, aes(x=Tissue, y=Expr, fill=Tissue), color="black") +
      geom_boxplot(alpha=0.7, outlier.shape = NA) +
      geom_jitter(aes(shape=Species), width=0.2, fill="black") +
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_shapes_vector) +
      theme_bw() +
      theme(axis.title = element_text(color="black"),
            axis.text.x = element_text(color="black", angle=30, hjust=1, vjust=1)
            ) +
      guides(fill=FALSE) +
      ggtitle(paste0(my_OG_ID, " ~ ", clade)) +
      ylim(c(my_min, my_max))
    
    all_plots[[i]] = expr_plot
    i = i+1
  }
  final_plot = plot_grid(all_plots[[1]], all_plots[[2]], all_plots[[3]], ncol=3, rel_widths = c(1,1,1))
  return(final_plot)
}
```

```{r PCA_functions, echo=FALSE, warning=FALSE, message=FALSE, dependson="setup"}
PCA_basic_plot = function(expr_df, features_table, species_set, cluster_number, quantity) {
    imputation_out = impute.knn(as.matrix(expr_df), k = 10) #impute missing values.
    imputation_df = as.data.frame(imputation_out$data) #transform to a dataframe.
    #compute PCA. I need the genes on columns in the input table.
    PCA_res = prcomp(as.matrix(t(imputation_df)), center = TRUE, scale = TRUE) #center and scale the PCs.
    ordered_PCA_res = as.data.frame(PCA_res$x[order(rownames(PCA_res$x)),]) 
    #filter the sample only for the samples that made it after the sva correction
    filtered_features_table = features_table[rownames(features_table) %in% colnames(imputation_df),]
    ordered_features_table = filtered_features_table[order(rownames(filtered_features_table)),] #order the table
    all(rownames(ordered_features_table) == rownames(ordered_PCA_res))
    #compute the percentage of variance explained
    eigs <- PCA_res$sdev^2
    first_PC_var = round(eigs[1]/sum(eigs), 3)*100
    second_PC_var = round(eigs[2]/sum(eigs), 3)*100
    third_PC_var = round(eigs[3]/sum(eigs), 3)*100
    fourth_PC_var = round(eigs[4]/sum(eigs), 3)*100
    #filter shapes vector
    my_filtered_shapes_vector=my_shapes_vector[unique(as.vector(ordered_features_table$species))] #filter the shape vector
    #filter ordered species
    filt_ordered_species = ordered_species[ordered_species %in% unique(as.vector(ordered_features_table$species))]
    ordered_features_table$species <- factor(ordered_features_table$species, levels=filt_ordered_species) #change the order of the levels in the factor
    #plot the first two PC
    ordered_PCA_res$tissues=ordered_features_table$tissues
    ordered_PCA_res$species=ordered_features_table$species
    
    p = ggplot() + geom_point(data=as.data.frame(ordered_PCA_res), 
                              aes(x=PC1, y=PC2, 
                                  color=tissues, 
                                  fill=tissues,
                                  shape=species), size=2, stroke=0.8) +
      ggtitle(paste0(species_set, " ~ ", cluster_number, ": ", quantity)) + 
      xlab(paste0("PC1: ", first_PC_var, "%")) + 
      ylab(paste0("PC2: ", second_PC_var, "%")) + theme_bw() +
      theme(axis.title = element_text(color="black", size=14), 
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12), 
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_filtered_shapes_vector) + 
      guides(color=guide_legend(title="Tissues"), shape=guide_legend(title="Species")) +
      coord_fixed()
      
    
    p1 = ggplot() + geom_point(data=as.data.frame(ordered_PCA_res), 
                               aes(x=PC2, y=PC3, 
                                   color=tissues,
                                   fill=tissues,
                                   shape=species), size=2, stroke=0.8) +
      ggtitle(paste0(species_set, " ~ ", cluster_number, ": ", quantity)) + 
      xlab(paste0("PC2: ", second_PC_var, "%")) + 
      ylab(paste0("PC3: ", third_PC_var, "%")) + 
      theme_bw() +
      theme(axis.title = element_text(color="black", size=14), 
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12), 
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_filtered_shapes_vector) + 
      guides(color=guide_legend(title="Tissues"), shape=guide_legend(title="Species"), fill=FALSE)
    
    p2 = ggplot() + geom_point(data=as.data.frame(ordered_PCA_res), 
                               aes(x=PC3, y=PC4, 
                                   color=tissues,
                                   fill=tissues,
                                   shape=species), size=2, stroke=0.8) +
      ggtitle(paste0(species_set, " ~ ", cluster_number, ": ", quantity)) + xlab(paste0("PC3: ", third_PC_var, "%")) + ylab(paste0("PC4: ", fourth_PC_var, "%")) + theme_bw() +
      theme(axis.title = element_text(color="black", size=14), 
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12), 
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_filtered_shapes_vector) + 
      guides(color=guide_legend(title="Tissues"), shape=guide_legend(title="Species"), fill=FALSE)
    
    res = list()
    res[[1]] = p
    res[[2]] = p1
    res[[3]] = p2
    
    my_plots = plot_grid(p, p1, p2, rel_widths=c(1,1,1), align="h", ncol=3)
    return(list("plots" = my_plots, "results"=res))
}

anova_plot = function(expr_df, features_table, species_set) {
  imputation_out = impute.knn(as.matrix(expr_df), k = 10) #impute NAs
  imputation_df = as.data.frame(imputation_out$data)
  ##### compute PCA. I need the genes on columns in the input table
  PCA_res = prcomp(as.matrix(t(imputation_df)), center = TRUE, scale = TRUE)
  ordered_PCA_res = as.data.frame(PCA_res$x[order(rownames(PCA_res$x)),])
  #filter feature table as neeeded
  filtered_features_table = features_table[rownames(features_table) %in% colnames(imputation_df),]
  ordered_features_table = filtered_features_table[order(rownames(filtered_features_table)),]
  all(rownames(ordered_features_table) == rownames(ordered_PCA_res))
  
  #merge results
  my_merged_table = merge(ordered_PCA_res, ordered_features_table, by=0)
  
  #Create the categories relative to the tissues.
  for (element in all_tissues) { #cycle on the tissues
    local_tissues = all_tissues
    local_tissues[local_tissues != element] = paste0("not_", element)
    my_dict <- hashmap(all_tissues,  local_tissues)
    my_merged_table$element =  as.factor(my_dict$find(my_merged_table$tissues))
    names(my_merged_table)[names(my_merged_table) == "element"] = element
  }
    
  #This is something relative to the species.
  my_species = unique(as.vector(my_merged_table$species))
  for (element in my_species) {
    local_species = my_species
    local_species[local_species != element] = paste0("not_", element)
    my_dict <- hashmap(my_species, local_species)
    my_merged_table$element =  as.factor(my_dict$find(my_merged_table$species))
    names(my_merged_table)[names(my_merged_table) == "element"] = element
  }
  
  colnames(my_merged_table)[1] = "sample"
  
  PCs = colnames(ordered_PCA_res)[1:15]
  pvalues_matrix = vector()
  species_pvalues_matrix = vector()
  tissues_pvalues_matrix = vector()
  for(PC in PCs) {
    pvalues_vector = vector() #create empty pvalue vector
    species_pvalues_vector = vector()
    tissues_pvalues_vector = vector()
    for(category in c("species", "tissues")) { #cycle on the previously defined categories
      res.aov <- aov(as.formula(paste0(PC, " ~ ", category)), data = my_merged_table) #run the anova test
      pvalue = summary(res.aov)[[1]][["Pr(>F)"]][1] #get the general pvalue from the anova test
      pvalues_vector = c(pvalues_vector, pvalue) #build the pvalue vector from the different anova test (one per category)
    }
    for (category in my_species) {
      res.aov <- aov(as.formula(paste0(PC, " ~ ", category)), data = my_merged_table) #run the anova test
      pvalue = summary(res.aov)[[1]][["Pr(>F)"]][1] #get the general pvalue from the anova test
      species_pvalues_vector = c(species_pvalues_vector, pvalue)
    }
    for (category in all_tissues) {
      res.aov <- aov(as.formula(paste0(PC, " ~ ", category)), data = my_merged_table) #run the anova test
      pvalue = summary(res.aov)[[1]][["Pr(>F)"]][1] #get the general pvalue from the anova test
      tissues_pvalues_vector = c(tissues_pvalues_vector, pvalue)
    }
    pvalues_matrix = rbind(pvalues_matrix, pvalues_vector) #build pvalue matrix (each row refers to a different PC)
    species_pvalues_matrix = rbind(species_pvalues_matrix, species_pvalues_vector) #build species matrix (each row refers to a different PC)
    tissues_pvalues_matrix = rbind(tissues_pvalues_matrix, tissues_pvalues_vector) #build tissues matrix (each row refers to a different PC)
  }
  
  #transform rownames and colnames
  rownames(pvalues_matrix) = PCs
  colnames(pvalues_matrix) = c("species", "tissues")
  rownames(species_pvalues_matrix) = PCs
  colnames(species_pvalues_matrix) = my_species
  rownames(tissues_pvalues_matrix) = PCs
  colnames(tissues_pvalues_matrix) = all_tissues
  
  #Correct the pvalues
  tot_tests = dim(pvalues_matrix)[1]*dim(pvalues_matrix)[2] + 
    dim(species_pvalues_matrix)[1]*dim(species_pvalues_matrix)[2] + 
    dim(tissues_pvalues_matrix)[1]*dim(tissues_pvalues_matrix)[2]
  
  pvalues_matrix = apply(pvalues_matrix, c(1,2), function(x) x*tot_tests)
  species_pvalues_matrix = apply(species_pvalues_matrix, c(1,2), function(x) x*tot_tests)
  tissues_pvalues_matrix = apply(tissues_pvalues_matrix, c(1,2), function(x) x*tot_tests)
  pvalues_matrix[pvalues_matrix > 1] = 1
  species_pvalues_matrix[species_pvalues_matrix > 1] = 1
  tissues_pvalues_matrix[tissues_pvalues_matrix > 1] = 1
  
  ######## compute max and min between all tables in order to scale all the plots accordingly.
  my_max = max(max(apply(pvalues_matrix, c(1,2), 
                         function(x) -log10(x))), 
               max(apply(species_pvalues_matrix, c(1,2), 
                         function(x) -log10(x))), 
               max(apply(tissues_pvalues_matrix, c(1,2), 
                         function(x) -log10(x))))
  my_min = 0
  
  ######### work on the general pvalues matrix
  log10_pvalues_matrix = apply(pvalues_matrix, c(1,2), function(x) -log10(x))
  log10_pvalues_table = as.data.frame(log10_pvalues_matrix)
  log10_pvalues_table$PC = rownames(log10_pvalues_table)
  log10_pvalues_table_long = melt(log10_pvalues_table, id.vars="PC")
  
  my_palette <- colorRampPalette(c("white", "springgreen", "forestgreen"))(n = 100)
  my_palette_1 = colorRampPalette(c("white", "springgreen"))(n=20)
  my_palette_2 = colorRampPalette(c("springgreen", "forestgreen"))(n=80)
  my_palette = c(my_palette_1, my_palette_2)
  
  log10_pvalues_table_long$PC = factor(log10_pvalues_table_long$PC, levels=rev(log10_pvalues_table$PC))
  log10_pvalues_table_long$Significant = ""
  log10_pvalues_table_long$Significant[log10_pvalues_table$value >= -log10(0.05)] = "*"
  
  
  p = ggplot(data=log10_pvalues_table_long, aes(x=variable, y=PC)) + 
    geom_tile(aes(fill=value)) + 
    geom_text(aes(label=Significant)) +
    ggtitle(paste0(species_set, " ~ Anova on PCs")) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", angle=30, hjust=1, size=12),
          axis.text.y = element_text(color="black", size=12), axis.title.y = element_blank(),
          axis.title.x = element_blank(), legend.position="bottom", axis.ticks = element_blank(),
          legend.text=element_text(size=12), legend.title=element_text(size=13),
          plot.title = element_text(size = 16), legend.key.size = unit(3, "mm")) +
    scale_fill_gradientn(colours=my_palette, limits = c(my_min, my_max)) + 
    guides(fill=guide_legend(title="-log10(pvalue)"))
  
  ######## work on species comparison matrix
  #the values should already be -log10(pvalue)
  species_pvalues_matrix = apply(species_pvalues_matrix, c(1,2), function(x) -log10(x))
  species_pvalues_table = as.data.frame(species_pvalues_matrix)
  species_pvalues_table$PC = rownames(species_pvalues_table)
  species_pvalues_table_long = melt(species_pvalues_table, id.vars="PC")
  
  #my_palette <- colorRampPalette(c("white", "chocolate1", "orangered3"))(n = 100)
  my_palette_1 = colorRampPalette(c("white", "chocolate1"))(n=20)
  my_palette_2 = colorRampPalette(c("chocolate1", "orangered3"))(n=80)
  my_palette = c(my_palette_1, my_palette_2)
  
  #create factors to have ordered axis
  species_pvalues_table_long$PC = factor(species_pvalues_table_long$PC, levels=rev(species_pvalues_table$PC))
  species_pvalues_table_long$variable = factor(species_pvalues_table_long$variable, levels=all_species)
  
  #plot
  p1 = ggplot() + geom_tile(data=species_pvalues_table_long, aes(x=variable, y=PC, fill=value)) + 
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", angle=45, hjust=1, size=12), 
          axis.title.x = element_blank(), 
          legend.position="bottom", axis.ticks = element_blank(), 
          axis.title.y=element_blank(), 
          legend.text=element_text(size=12), 
          legend.title=element_text(size=13),
          axis.text.y = element_blank(),
          plot.title = element_text(size = 16), legend.key.size = unit(3, "mm")) +
    scale_fill_gradientn(colours=my_palette, limits = c(my_min, my_max)) + 
    ggtitle(paste0(species_set, " ~ species sep by Anova")) + guides(fill=guide_legend(title="-log10(pvalue)"))
  
  ###### work on tissues comparison matrix
  #the values should already be -log10(pvalue)
  tissues_pvalues_matrix = apply(tissues_pvalues_matrix, c(1,2), function(x) -log10(x))
  tissues_pvalues_table = as.data.frame(tissues_pvalues_matrix)
  tissues_pvalues_table$PC = rownames(tissues_pvalues_table)
  tissues_pvalues_table_long = melt(tissues_pvalues_table, id.vars="PC")
  
  #my_palette <- colorRampPalette(c("white", "chocolate1", "orangered3"))(n = 100)
  my_palette_1 = colorRampPalette(c("white", "deepskyblue1"))(n=20)
  my_palette_2 = colorRampPalette(c("deepskyblue1", "mediumblue"))(n=80)
  my_palette = c(my_palette_1, my_palette_2)
  
  #create factors to have ordered axis
  tissues_pvalues_table_long$PC = factor(tissues_pvalues_table_long$PC, levels=rev(tissues_pvalues_table$PC))
  tissues_pvalues_table_long$variable = factor(tissues_pvalues_table_long$variable, levels=all_tissues)
  
  #plot
  p2 = ggplot() + geom_tile(data=tissues_pvalues_table_long, aes(x=variable, y=PC, fill=value)) + 
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", angle=45, hjust=1, size=12), 
          axis.title.x = element_blank(), 
          legend.position="bottom", axis.ticks = element_blank(), 
          axis.title.y=element_blank(), 
          legend.text=element_text(size=12), 
          legend.title=element_text(size=13),
          axis.text.y = element_blank(),
          plot.title = element_text(size = 16),
          legend.key.size = unit(3, "mm")) +
    scale_fill_gradientn(colours=my_palette, limits = c(my_min, my_max)) + 
    ggtitle(paste0(species_set, " ~ tissues sep by Anova")) + guides(fill=guide_legend(title="-log10(pvalue)"))
  
  eigs <- PCA_res$sdev^2
  my_eigs = eigs/sum(eigs)*100
  my_eigs_df = as.data.frame(my_eigs[1:15])
  my_eigs_df$PC = paste0("PC", seq(1,nrow(my_eigs_df)))
  my_eigs_df$PC = factor(my_eigs_df$PC, levels=rev(my_eigs_df$PC))
  colnames(my_eigs_df) = c("my_eigs", "PC")
  
  p3 = ggplot() + geom_bar(data=my_eigs_df, aes(x=PC, y=my_eigs, fill="random"), stat="identity") + coord_flip(ylim=c(0,25)) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", size=12), 
          axis.title.y=element_blank(), axis.text.y = element_blank(),
          axis.title.x = element_text(color="black", size=13),
          axis.line = element_blank(), axis.ticks = element_blank(),
          panel.border = element_blank(), panel.background = element_blank(), 
          legend.text=element_text(size=12), legend.title=element_text(size=13),
          panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position="bottom", legend.key.size = unit(3, "mm")) + 
    scale_fill_manual(values=c("random"="violet")) +
    ylab("Variance explained (%)") +
    ggtitle(paste0(species_set, " ~ PC variance"))

  res = list()
  res[[1]] = p
  res[[2]] = p1
  res[[3]] = p2
  res[[4]] = p3
  
  my_plots = plot_grid(p, p1, p2, p3, rel_widths=c(2,2,2,0.75), align="h", ncol=4)
  return(list("plots" = my_plots, "results"=res))
}

plot_PC_distrib = function(expr_df, features_table, PC, all_tissues) {
    clusters_number=nrow(expr_df)
    imputation_out = impute.knn(as.matrix(expr_df),k = 10)
    imputation_df = as.data.frame(imputation_out$data)
    #compute PCA. I need the genes on columns in the input table
    PCA_res = prcomp(as.matrix(t(imputation_df)), center = TRUE, scale = TRUE)
    ordered_PCA_res = as.data.frame(PCA_res$x[order(rownames(PCA_res$x)),])
    #filter feature table as neeeded
    filtered_features_table = features_table[rownames(features_table) %in% colnames(imputation_df),]
    ordered_features_table = filtered_features_table[order(rownames(filtered_features_table)),]
    all(rownames(ordered_features_table) == rownames(ordered_PCA_res))
     #compute the percentage of variance explained
    eigs <- PCA_res$sdev^2
    first_PC_var = round(eigs[1]/sum(eigs), 3)*100
    second_PC_var = round(eigs[2]/sum(eigs), 3)*100
    third_PC_var = round(eigs[3]/sum(eigs), 3)*100
    fourth_PC_var = round(eigs[4]/sum(eigs), 3)*100
    #filter shapes vector
    my_filtered_shapes_vector=my_shapes_vector[unique(as.vector(ordered_features_table$species))]
    #filter ordered species
    filt_ordered_species = ordered_species[ordered_species %in% unique(as.vector(ordered_features_table$species))]
    ordered_features_table$species <- factor(ordered_features_table$species, levels=filt_ordered_species) #change the order of the levels in the factor
    #plot the first two PC
    ordered_PCA_res$tissues=as.vector(ordered_features_table$tissues)
    ordered_PCA_res$species=as.vector(ordered_features_table$species)
    
    all_plots = list()
    i = 1
    for (tissue in all_tissues) {
      tissue_ordered_PCA_res = ordered_PCA_res
      tissue_ordered_PCA_res$tissues[tissue_ordered_PCA_res$tissues != tissue] = "Other"
      #tissue_ordered_PCA_res$tissues[!(tissue_ordered_PCA_res$tissues %in% all_tissues)] = "Other" #alternative
      my_tissues = "tissues"
      my_PC = paste0("PC", PC)
    
      PC_distrib_plot = ggplot(data=tissue_ordered_PCA_res) +
        geom_density(aes_string(x=my_PC, color=my_tissues, fill=my_tissues), alpha=0.8) +
        theme_bw() +
        scale_color_manual(values= my_color_vector_distrib) +
        scale_fill_manual(values= my_color_vector_distrib) +
        theme(axis.text = element_text(color="black", size=10),
              axis.title = element_text(color="black", size=12),
              plot.title = element_text(color="black", size=18),
              legend.text = element_text(color="black", size=12),
              legend.title = element_text(color="black", size=12)) +
        #scale_x_reverse() +
        ggtitle(paste0("PC", PC, ": ", tissue, " vs Others")) +
        guides(color="none", fill="none")

      all_plots[[i]] = PC_distrib_plot
      i = i +1
    }
    return(all_plots)
}


##############
PCA_basic_plot_tissue = function(expr_df, features_table, species_set, cluster_number, quantity) {
    features_table = unique(features_table)
    rownames(features_table) = paste0(features_table$species, "_", features_table$tissues)
    imputation_out = impute.knn(as.matrix(expr_df), k = 10) #impute missing values.
    imputation_df = as.data.frame(imputation_out$data) #transform to a dataframe.
    #compute PCA. I need the genes on columns in the input table.
    PCA_res = prcomp(as.matrix(t(imputation_df)), center = TRUE, scale = TRUE) #center and scale the PCs.
    ordered_PCA_res = as.data.frame(PCA_res$x[order(rownames(PCA_res$x)),]) 
    #filter the sample only for the samples that made it after the sva correction
    filtered_features_table = features_table[rownames(features_table) %in% colnames(imputation_df),]
    ordered_features_table = filtered_features_table[order(rownames(filtered_features_table)),] #order the table
    all(rownames(ordered_features_table) == rownames(ordered_PCA_res))
    #compute the percentage of variance explained
    eigs <- PCA_res$sdev^2
    first_PC_var = round(eigs[1]/sum(eigs), 3)*100
    second_PC_var = round(eigs[2]/sum(eigs), 3)*100
    third_PC_var = round(eigs[3]/sum(eigs), 3)*100
    fourth_PC_var = round(eigs[4]/sum(eigs), 3)*100
    #filter shapes vector
    my_filtered_shapes_vector=my_shapes_vector[unique(as.vector(ordered_features_table$species))] #filter the shape vector
    #filter ordered species
    filt_ordered_species = ordered_species[ordered_species %in% unique(as.vector(ordered_features_table$species))]
    ordered_features_table$species <- factor(ordered_features_table$species, levels=filt_ordered_species) #change the order of the levels in the factor
    #plot the first two PC
    ordered_PCA_res$tissues=ordered_features_table$tissues
    ordered_PCA_res$species=ordered_features_table$species
    
    p = ggplot() + geom_point(data=as.data.frame(ordered_PCA_res), 
                              aes(x=PC1, y=PC2, 
                                  color=tissues, 
                                  fill=tissues,
                                  shape=species), size=2, stroke=0.8) +
      ggtitle(paste0(species_set, " ~ ", cluster_number, ": ", quantity)) + 
      xlab(paste0("PC1: ", first_PC_var, "%")) + 
      ylab(paste0("PC2: ", second_PC_var, "%")) + theme_bw() +
      theme(axis.title = element_text(color="black", size=14), 
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12), 
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_filtered_shapes_vector) + 
      guides(color=guide_legend(title="Tissues"), shape=guide_legend(title="Species")) +
      coord_fixed()
      
    
    p1 = ggplot() + geom_point(data=as.data.frame(ordered_PCA_res), 
                               aes(x=PC2, y=PC3, 
                                   color=tissues,
                                   fill=tissues,
                                   shape=species), size=2, stroke=0.8) +
      ggtitle(paste0(species_set, " ~ ", cluster_number, ": ", quantity)) + 
      xlab(paste0("PC2: ", second_PC_var, "%")) + 
      ylab(paste0("PC3: ", third_PC_var, "%")) + 
      theme_bw() +
      theme(axis.title = element_text(color="black", size=14), 
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12), 
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_filtered_shapes_vector) + 
      guides(color=guide_legend(title="Tissues"), shape=guide_legend(title="Species"), fill=FALSE)
    
    p2 = ggplot() + geom_point(data=as.data.frame(ordered_PCA_res), 
                               aes(x=PC3, y=PC4, 
                                   color=tissues,
                                   fill=tissues,
                                   shape=species), size=2, stroke=0.8) +
      ggtitle(paste0(species_set, " ~ ", cluster_number, ": ", quantity)) + xlab(paste0("PC3: ", third_PC_var, "%")) + ylab(paste0("PC4: ", fourth_PC_var, "%")) + theme_bw() +
      theme(axis.title = element_text(color="black", size=14), 
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12), 
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_filtered_shapes_vector) + 
      guides(color=guide_legend(title="Tissues"), shape=guide_legend(title="Species"), fill=FALSE)
    
    res = list()
    res[[1]] = p
    res[[2]] = p1
    res[[3]] = p2
    
    my_plots = plot_grid(p, p1, p2, rel_widths=c(1,1,1), align="h", ncol=3)
    return(list("plots" = my_plots, "results"=res))
}
##############

plot_PC_distrib_all_tissues = function(expr_df, features_table, PC) {
    clusters_number=nrow(expr_df)
    imputation_out = impute.knn(as.matrix(expr_df),k = 10)
    imputation_df = as.data.frame(imputation_out$data)
    #compute PCA. I need the genes on columns in the input table
    PCA_res = prcomp(as.matrix(t(imputation_df)), center = TRUE, scale = TRUE)
    ordered_PCA_res = as.data.frame(PCA_res$x[order(rownames(PCA_res$x)),])
    #filter feature table as neeeded
    filtered_features_table = features_table[rownames(features_table) %in% colnames(imputation_df),]
    ordered_features_table = filtered_features_table[order(rownames(filtered_features_table)),]
    all(rownames(ordered_features_table) == rownames(ordered_PCA_res))
     #compute the percentage of variance explained
    eigs <- PCA_res$sdev^2
    first_PC_var = round(eigs[1]/sum(eigs), 3)*100
    second_PC_var = round(eigs[2]/sum(eigs), 3)*100
    third_PC_var = round(eigs[3]/sum(eigs), 3)*100
    fourth_PC_var = round(eigs[4]/sum(eigs), 3)*100
    #filter shapes vector
    my_filtered_shapes_vector=my_shapes_vector[unique(as.vector(ordered_features_table$species))]
    #filter ordered species
    filt_ordered_species = ordered_species[ordered_species %in% unique(as.vector(ordered_features_table$species))]
    ordered_features_table$species <- factor(ordered_features_table$species, levels=filt_ordered_species) #Change the order of the levels in the factor
    #plot the first two PC
    ordered_PCA_res$tissues=as.vector(ordered_features_table$tissues)
    ordered_PCA_res$species=as.vector(ordered_features_table$species)
    
    #ordered_PCA_res$tissues[ordered_PCA_res$tissues != tissue] = "Other"
    my_tissues = "tissues"
    my_PC = paste0("PC", PC)
    
    PC_distrib_plot = ggplot(data=ordered_PCA_res) +
      geom_density(aes_string(x=my_PC, color=my_tissues, fill=my_tissues), alpha=0.7) +
      theme_bw() +
      scale_color_manual(values= my_color_vector_distrib) +
      scale_fill_manual(values= my_color_vector_distrib) +
      theme(axis.text = element_text(color="black", size=10),
            #axis.ticks = element_line(),
            axis.title = element_text(color="black", size=12),
            plot.title = element_text(color="black", size=18),
            legend.text = element_text(color="black", size=12),
            legend.title = element_text(color="black", size=12)) +
      #scale_x_reverse() +
      ggtitle(paste0("PC", PC, ": All tissues")) +
      guides(color="none", fill="none")

    return(PC_distrib_plot)
}
```

```{r anova_function, echo=FALSE, warning=FALSE, message=FALSE, dependson="setup"}
anova_plot = function(expr_df, features_table, species_set) {
  imputation_out = impute.knn(as.matrix(expr_df), k = 10) #impute NAs
  imputation_df = as.data.frame(imputation_out$data)
  ##### compute PCA. I need the genes on columns in the input table
  PCA_res = prcomp(as.matrix(t(imputation_df)), center = TRUE, scale = TRUE)
  ordered_PCA_res = as.data.frame(PCA_res$x[order(rownames(PCA_res$x)),])
  #filter feature table as neeeded
  filtered_features_table = features_table[rownames(features_table) %in% colnames(imputation_df),]
  ordered_features_table = filtered_features_table[order(rownames(filtered_features_table)),]
  all(rownames(ordered_features_table) == rownames(ordered_PCA_res))
  
  #merge results
  my_merged_table = merge(ordered_PCA_res, ordered_features_table, by=0)
  
  #Create the categories relative to the tissues.
  for (element in all_tissues) { #cycle on the tissues
    local_tissues = all_tissues
    local_tissues[local_tissues != element] = paste0("not_", element)
    my_dict <- hashmap(all_tissues,  local_tissues)
    my_merged_table$element =  as.factor(my_dict$find(my_merged_table$tissues))
    names(my_merged_table)[names(my_merged_table) == "element"] = element
  }
    
  #This is something relative to the species.
  my_species = unique(as.vector(my_merged_table$species))
  for (element in my_species) {
    local_species = my_species
    local_species[local_species != element] = paste0("not_", element)
    my_dict <- hashmap(my_species, local_species)
    my_merged_table$element =  as.factor(my_dict$find(my_merged_table$species))
    names(my_merged_table)[names(my_merged_table) == "element"] = element
  }
  
  colnames(my_merged_table)[1] = "sample"
  
  PCs = colnames(ordered_PCA_res)[1:15]
  pvalues_matrix = vector()
  species_pvalues_matrix = vector()
  tissues_pvalues_matrix = vector()
  for(PC in PCs) {
    pvalues_vector = vector() #create empty pvalue vector
    species_pvalues_vector = vector()
    tissues_pvalues_vector = vector()
    for(category in c("species", "tissues")) { #cycle on the previously defined categories
      res.aov <- aov(as.formula(paste0(PC, " ~ ", category)), data = my_merged_table) #run the anova test
      pvalue = summary(res.aov)[[1]][["Pr(>F)"]][1] #get the general pvalue from the anova test
      pvalues_vector = c(pvalues_vector, pvalue) #build the pvalue vector from the different anova test (one per category)
    }
    for (category in my_species) {
      res.aov <- aov(as.formula(paste0(PC, " ~ ", category)), data = my_merged_table) #run the anova test
      pvalue = summary(res.aov)[[1]][["Pr(>F)"]][1] #get the general pvalue from the anova test
      species_pvalues_vector = c(species_pvalues_vector, pvalue)
    }
    for (category in all_tissues) {
      res.aov <- aov(as.formula(paste0(PC, " ~ ", category)), data = my_merged_table) #run the anova test
      pvalue = summary(res.aov)[[1]][["Pr(>F)"]][1] #get the general pvalue from the anova test
      tissues_pvalues_vector = c(tissues_pvalues_vector, pvalue)
    }
    pvalues_matrix = rbind(pvalues_matrix, pvalues_vector) #build pvalue matrix (each row refers to a different PC)
    species_pvalues_matrix = rbind(species_pvalues_matrix, species_pvalues_vector) #build species matrix (each row refers to a different PC)
    tissues_pvalues_matrix = rbind(tissues_pvalues_matrix, tissues_pvalues_vector) #build tissues matrix (each row refers to a different PC)
  }
  
  #transform rownames and colnames
  rownames(pvalues_matrix) = PCs
  colnames(pvalues_matrix) = c("species", "tissues")
  rownames(species_pvalues_matrix) = PCs
  colnames(species_pvalues_matrix) = my_species
  rownames(tissues_pvalues_matrix) = PCs
  colnames(tissues_pvalues_matrix) = all_tissues
  
  #Correct the pvalues
  tot_tests = dim(pvalues_matrix)[1]*dim(pvalues_matrix)[2] + 
    dim(species_pvalues_matrix)[1]*dim(species_pvalues_matrix)[2] + 
    dim(tissues_pvalues_matrix)[1]*dim(tissues_pvalues_matrix)[2]
  
  pvalues_matrix = apply(pvalues_matrix, c(1,2), function(x) x*tot_tests)
  species_pvalues_matrix = apply(species_pvalues_matrix, c(1,2), function(x) x*tot_tests)
  tissues_pvalues_matrix = apply(tissues_pvalues_matrix, c(1,2), function(x) x*tot_tests)
  pvalues_matrix[pvalues_matrix > 1] = 1
  species_pvalues_matrix[species_pvalues_matrix > 1] = 1
  tissues_pvalues_matrix[tissues_pvalues_matrix > 1] = 1
  
  ######## compute max and min between all tables in order to scale all the plots accordingly.
  #my_max = max(max(apply(pvalues_matrix, c(1,2), 
  #                       function(x) -log10(x))), 
  #             max(apply(species_pvalues_matrix, c(1,2), 
  #                       function(x) -log10(x))), 
  #             max(apply(tissues_pvalues_matrix, c(1,2), 
  #                       function(x) -log10(x))))
  my_max = 100
  my_min = 0
  
  ######### work on the general pvalues matrix
  log10_pvalues_matrix = apply(pvalues_matrix, c(1,2), function(x) -log10(x))
  log10_pvalues_table = as.data.frame(log10_pvalues_matrix)
  log10_pvalues_table$PC = rownames(log10_pvalues_table)
  log10_pvalues_table_long = melt(log10_pvalues_table, id.vars="PC")
  #Transform everything greater than 50 to 50
  log10_pvalues_table_long$value[log10_pvalues_table_long$value > 100] = 100
  
  my_palette <- colorRampPalette(c("white", "springgreen", "forestgreen"))(n = 100)
  my_palette_1 = colorRampPalette(c("white", "springgreen"))(n=20)
  my_palette_2 = colorRampPalette(c("springgreen", "forestgreen"))(n=80)
  my_palette = c(my_palette_1, my_palette_2)
  
  log10_pvalues_table_long$PC = factor(log10_pvalues_table_long$PC, levels=rev(log10_pvalues_table$PC))
  log10_pvalues_table_long$Significant = rep("Non_sign", nrow(log10_pvalues_table_long))
  log10_pvalues_table_long$Significant[log10_pvalues_table_long$value >= -log10(0.05)] = "Sign"
  
  p = ggplot(data=log10_pvalues_table_long, aes(x=variable, y=PC)) + 
    #geom_tile(aes(fill=value)) + 
    geom_tile(aes(fill=value, color=Significant, size=Significant)) + 
    #geom_text(aes(label=Significant), color="black") +
    ggtitle(paste0(species_set, " ~ Anova on PCs")) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", angle=30, hjust=1, size=12),
          axis.text.y = element_text(color="black", size=12), axis.title.y = element_blank(),
          axis.title.x = element_blank(), legend.position="bottom", axis.ticks = element_blank(),
          legend.text=element_text(size=12), legend.title=element_text(size=13),
          plot.title = element_text(size = 16), legend.key.size = unit(3, "mm")) +
    scale_fill_gradientn(colours=my_palette, limits = c(my_min, my_max)) +
    scale_color_manual(values = c("Non_sign"="gray88", "Sign"="black")) +
    scale_size_manual(values = c("Non_sign"=0.1, "Sign"=1)) +
    guides(fill=guide_legend(title="-log10(pvalue)"))
  
  ######## work on species comparison matrix
  #the values should already be -log10(pvalue)
  species_pvalues_matrix = apply(species_pvalues_matrix, c(1,2), function(x) -log10(x))
  species_pvalues_table = as.data.frame(species_pvalues_matrix)
  species_pvalues_table$PC = rownames(species_pvalues_table)
  species_pvalues_table_long = melt(species_pvalues_table, id.vars="PC")
  species_pvalues_table_long$value[species_pvalues_table_long$value > 100] = 100
  
  #my_palette <- colorRampPalette(c("white", "chocolate1", "orangered3"))(n = 100)
  my_palette_1 = colorRampPalette(c("white", "chocolate1"))(n=20)
  my_palette_2 = colorRampPalette(c("chocolate1", "orangered3"))(n=80)
  my_palette = c(my_palette_1, my_palette_2)
  
  #create factors to have ordered axis
  species_pvalues_table_long$PC = factor(species_pvalues_table_long$PC, levels=rev(species_pvalues_table$PC))
  species_pvalues_table_long$variable = factor(species_pvalues_table_long$variable, levels=all_species)
  species_pvalues_table_long$Significant = rep("Non_sign", nrow(species_pvalues_table_long))
  species_pvalues_table_long$Significant[species_pvalues_table_long$value >= -log10(0.05)] = "Sign"
  
  #plot
  p1 = ggplot(data=species_pvalues_table_long, aes(x=variable, y=PC)) +
    #geom_tile(aes(fill=value)) +
    geom_tile(aes(fill=value, color=Significant, size=Significant)) +  
    #geom_text(aes(label=Significant)) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", angle=45, hjust=1, size=12), 
          axis.title.x = element_blank(), 
          legend.position="bottom", axis.ticks = element_blank(), 
          axis.title.y=element_blank(), 
          legend.text=element_text(size=12), 
          legend.title=element_text(size=13),
          axis.text.y = element_blank(),
          plot.title = element_text(size = 16), legend.key.size = unit(3, "mm")) +
    scale_fill_gradientn(colours=my_palette, limits = c(my_min, my_max)) + 
    scale_color_manual(values = c("Non_sign"="gray88", "Sign"="black")) +
    scale_size_manual(values = c("Non_sign"=0.1, "Sign"=1)) +
    ggtitle(paste0(species_set, " ~ species sep by Anova")) + guides(fill=guide_legend(title="-log10(pvalue)"))
  
  ###### work on tissues comparison matrix
  #the values should already be -log10(pvalue)
  tissues_pvalues_matrix = apply(tissues_pvalues_matrix, c(1,2), function(x) -log10(x))
  tissues_pvalues_table = as.data.frame(tissues_pvalues_matrix)
  tissues_pvalues_table$PC = rownames(tissues_pvalues_table)
  tissues_pvalues_table_long = melt(tissues_pvalues_table, id.vars="PC")
  tissues_pvalues_table_long$value[tissues_pvalues_table_long$value > 100] = 100
  
  #my_palette <- colorRampPalette(c("white", "chocolate1", "orangered3"))(n = 100)
  my_palette_1 = colorRampPalette(c("white", "deepskyblue1"))(n=20)
  my_palette_2 = colorRampPalette(c("deepskyblue1", "mediumblue"))(n=80)
  my_palette = c(my_palette_1, my_palette_2)
  
  #create factors to have ordered axis
  tissues_pvalues_table_long$PC = factor(tissues_pvalues_table_long$PC, levels=rev(tissues_pvalues_table$PC))
  tissues_pvalues_table_long$variable = factor(tissues_pvalues_table_long$variable, levels=ordered_tissues)
  tissues_pvalues_table_long$Significant = rep("Non_sign", nrow(tissues_pvalues_table_long))
  tissues_pvalues_table_long$Significant[tissues_pvalues_table_long$value >= -log10(0.05)] = "Sign"
  
  #plot
  p2 = ggplot(data=tissues_pvalues_table_long, aes(x=variable, y=PC)) + 
    geom_tile(aes(fill=value, color=Significant, size=Significant)) + 
    #geom_tile(aes(fill=value)) +
    #geom_text(aes(label = Significant)) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", angle=45, hjust=1, size=12), 
          axis.title.x = element_blank(), 
          legend.position="bottom", axis.ticks = element_blank(), 
          axis.title.y=element_blank(), 
          legend.text=element_text(size=12), 
          legend.title=element_text(size=13),
          axis.text.y = element_blank(),
          plot.title = element_text(size = 16),
          legend.key.size = unit(3, "mm")) +
    scale_fill_gradientn(colours=my_palette, limits = c(my_min, my_max)) + 
    scale_color_manual(values = c("Non_sign"="gray88", "Sign"="black")) +
    scale_size_manual(values = c("Non_sign"=0.1, "Sign"=1)) +
    ggtitle(paste0(species_set, " ~ tissues sep by Anova")) + guides(fill=guide_legend(title="-log10(pvalue)"))
  
  eigs <- PCA_res$sdev^2
  my_eigs = eigs/sum(eigs)*100
  my_eigs_df = as.data.frame(my_eigs[1:15])
  my_eigs_df$PC = paste0("PC", seq(1,nrow(my_eigs_df)))
  my_eigs_df$PC = factor(my_eigs_df$PC, levels=rev(my_eigs_df$PC))
  colnames(my_eigs_df) = c("my_eigs", "PC")
  
  p3 = ggplot() + geom_bar(data=my_eigs_df, aes(x=PC, y=my_eigs, fill="random"), stat="identity") + coord_flip(ylim=c(0,12)) +
    theme_bw() + 
    theme(axis.text.x = element_text(color="black", size=12), 
          axis.title.y=element_blank(), 
          axis.text.y = element_blank(),
          axis.title.x = element_text(color="black", size=13),
          #axis.line = element_blank(), axis.ticks = element_blank(),
          #panel.border = element_blank(), panel.background = element_blank(), 
          legend.text=element_text(size=12), legend.title=element_text(size=13),
          #panel.grid.minor = element_blank(), panel.grid.major = element_blank(), 
          legend.position="bottom", legend.key.size = unit(3, "mm")) + 
    scale_fill_manual(values=c("random"="violet")) +
    ylab("Variance explained (%)") +
    ggtitle(paste0(species_set, " ~ PC variance"))

  res = list()
  res[[1]] = p
  res[[2]] = p1
  res[[3]] = p2
  res[[4]] = p3
  
  my_plots = plot_grid(p, p1, p2, p3, rel_widths=c(2,2,2,0.75), align="h", ncol=4)
  return(list("plots" = my_plots, "results"=res))
}
```

```{r generate_metadata_table, echo=FALSE, warning=FALSE, message=FALSE, dependson="setup"}
all_metadata_df = vector()
for (species in all_species) {
  file_species = species
  if (species == "BmA") {file_species= "Bmo"}
  metadata_df = unique(read.delim(paste0(metadata_dir, file_species, "_samples_info.tab"), header=TRUE)[,1:3])
  colnames(metadata_df) = c("species", "tissues", "metasample")
  metadata_df$species = rep(species, nrow(metadata_df)) #This is necessary only to translate Bmo to BmA
  rownames(metadata_df) = paste0(rep(species, nrow(metadata_df)), "_", as.vector(metadata_df$metasample))
  metadata_df$metasample = NULL
  all_metadata_df = rbind(all_metadata_df, metadata_df)
}
colnames(all_metadata_df) = c("species", "tissues")

sample_tissue_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$tissues))
sample_species_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$species))
```

<!-- Panel A,B,C: PC2 vs PC3, together with heatmaps with the species and tissue separation info -->
```{r Plot_first_PCs_with_Anova, echo=FALSE, warning=FALSE, message=FALSE, results="hide", dependson="setup", fig.width=14, fig.height=10, eval=FALSE}
#fig.width=16, fig.height=1
my_color_vector = c("Neural"="mediumblue", "Testis"="violet", "Ovary"="dimgray", "Muscle"="dimgray", 
                   "Kidney"="dimgray", "Epithelial"="dimgray", "DigestiveTract"="dimgray", "Adipose"="dimgray")
######## Try to do Anova test on the PCs
clade_PCA = c("Bilateria")
#Results from the PCA
for (clade in clade_PCA) {
    expr_file = paste0(pca_dir, my_version, "/STRICT/Bilateria/conserved/Bilateria_conserved-metasamples_median_expr-NOSVA-log2-TPMs-NORM-BH_genes.tab")
    expr_df = read.table(expr_file, header=TRUE, row=1)
    expr_df = expr_df[complete.cases(expr_df),]
    #####
    orthogroups_number=nrow(expr_df)
    res_PCA = PCA_basic_plot(expr_df, all_metadata_df, clade, orthogroups_number, "all gene orthogroups")
    res_anova = anova_plot(expr_df, all_metadata_df, clade)
    #plots
    first_row = annotate_figure(ggarrange(res_PCA$results[[1]] + ggtitle(""), 
                                          res_PCA$results[[2]] + ggtitle(""), 
                                          res_PCA$results[[3]] + ggtitle(""), 
                                          common.legend=TRUE, legend="right", 
                                          ncol=3), 
                            fig.lab=paste0(clade, " PC analysis ~ ", orthogroups_number, " clusters"), fig.lab.pos = "top.left", fig.lab.size=18)
    second_row = plot_grid(res_anova$results[[1]] + ggtitle("Anova on PCs"), 
                           res_anova$results[[2]] + ggtitle("Anova ~ species separation"), 
                           res_anova$results[[3]] + ggtitle("Anova  ~ tissues separation"), 
                           res_anova$results[[4]] + ggtitle("Variance explained"), 
                           rel_widths=c(1.25,2,2,1), align="h", ncol=4)
    
    final_plot = ggarrange(first_row, second_row, nrow=2)
    print(final_plot)
}

pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/new_sup/SupFig3-anova_boxes-v1.pdf", width=14, height=10)
print(final_plot)
dev.off()
```

<!-- Extra plots. Get the lateral distributions for panel B  -->
```{r lateral_distributions, echo=FALSE, warning=FALSE, message=FALSE, eval=FALSE, dependson=c("setup", "functions"), fig.width=5, fig.height=2}
expr_file = paste0(pca_dir, my_version, "/STRICT/Bilateria/conserved/Bilateria_conserved-metasamples_median_expr-NOSVA-log2-TPMs-NORM-BH_genes.tab")
expr_df = read.table(expr_file, header=TRUE, row=1)
expr_df = expr_df[complete.cases(expr_df),]
my_color_vector_distrib = c("Neural"="mediumblue", "Testis"="violet", "Others"="dimgray")

temp_metadata_df = all_metadata_df
temp_metadata_df$tissues[!(temp_metadata_df$tissues %in% c("Neural"))] = "Others"
neural_res = plot_PC_distrib_all_tissues(expr_df, temp_metadata_df, 2)
print(neural_res)

pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/new_sup/SupFig3-PC2_neural_samples.pdf", width=5, height=2)
print(neural_res)
dev.off()

temp_metadata_df = all_metadata_df
temp_metadata_df$tissues[!(temp_metadata_df$tissues %in% c("Testis"))] = "Others"
testis_res = plot_PC_distrib_all_tissues(expr_df, temp_metadata_df, 3) + scale_x_reverse()
print(testis_res)

pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/new_sup/SupFig3-PC2_testis_samples.pdf", width=5, height=2)
print(testis_res)
dev.off()
```

<!-- Panel C: heatmap showing clustering by tissue -->
```{r zscore_by_gene_tissue_ordered_branches, echo=FALSE, message=FALSE, warning=FALSE, dependson=c("setup", "functions"), fig.width=4, fig.height=7}
all_metadata_df = vector()
for (species in original_species) {
  file_species = species
  if (species == "BmA") {file_species= "Bmo"}
  metadata_df = unique(read.delim(paste0(metadata_dir, file_species, "_samples_info.tab"), header=TRUE)[,1:3])
  colnames(metadata_df) = c("species", "tissues", "metasample")
  metadata_df$species = rep(species, nrow(metadata_df)) #This is necessary only to translate Bmo to BmA
  rownames(metadata_df) = paste0(rep(species, nrow(metadata_df)), "_", as.vector(metadata_df$metasample))
  metadata_df$metasample = NULL
  all_metadata_df = rbind(all_metadata_df, metadata_df)
}
colnames(all_metadata_df) = c("species", "tissues")

sample_tissue_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$tissues))
sample_species_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$species))

#all_OG_df = read.delim(paste0(home, "projects/bilaterian_GE/data/pca_analysis_all_norms/All_version2/STRICT/Bilateria/conserved/Bilateria_conserved-metasamples_median_expr-NOSVA-log2-TPMs-NORM-species_zscore-BH_genes.tab"), header=TRUE, row=1)
all_OG_df = read.delim(paste0(home, "projects/bilaterian_GE/data/pca_analysis_all_norms/All_version2/STRICT/Bilateria/conserved/Bilateria_conserved-tissue_average_expr-NOSVA-log2-TPMs-NORM-species_zscore-BH_genes.tab"), header=TRUE, row=1)
zscore_df = all_OG_df[complete.cases(all_OG_df),]

######### plot the heatmap
#create palettes
my_palette_1 <- colorRampPalette(c("blue", "dodgerblue"))(30)
my_palette_2 = colorRampPalette(c("dodgerblue","white","firebrick1"))(85)
my_palette_3 = colorRampPalette(c("firebrick1", "firebrick"))(40)
my_palette = c(my_palette_1, my_palette_2, my_palette_3)

#my_palette = colorRampPalette(c("blue","white","firebrick1"))(25)

#plot with pheatmap
annotation_df = as.data.frame(cbind(gsub("_.*", "", colnames(zscore_df)), gsub(".*_", "", colnames(zscore_df))))
rownames(annotation_df) = colnames(zscore_df)
colnames(annotation_df) = c("Species", "Tissues")
#this is for the metasamples run
#annotation_df$Tissues = sample_tissue_dict$find(rownames(annotation_df))

#Transpose dataframe
zscore_df = as.data.frame(t(as.matrix(zscore_df)))

species_colors = c("Hs2"="#00BFFF", "Mm2"="#159DFF", "Bt2"="#1873CD", "Mdo"="#174B8B", "Gga"="#3F3F8B", "Xtr"="#64398B",
                 "Dre"="#82359D", "Cmi"="#9932CC", "Bla"="#2E8B57", "Sp2"="#96B12B", rev(c("Obi"="#FFFF00",
                 "Sma"="#FFCC33", "Cdi"="goldenrod", "Bge"="burlywood2", "Ame"="#FF9966", "Tca"="#FF6600",
                 "BmA"="#CC6600", "Aae"="#993300", "Eba"="firebrick3", "Dme"="red")))


pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/new_sup/SupFig3-heatmap_ward2.pdf", width=4, height=7)
genes_tissue_zscores_heatmap = 
  pheatmap(zscore_df, 
           color=my_palette,
           clustering_method = "ward.D2",
           show_rownames = FALSE, 
           #annotation_col = annotation_df, 
           annotation_row = annotation_df, 
           treeheight_col = 0,
           #treeheight_row = 0,
           show_colnames = FALSE,
           annotation_legend=FALSE,
           angle_col=45,
           border_color = NA,
           annotation_colors = list(Tissues = tissue_colors, Species = species_colors, main="Value = median + third quartile"),
           #annotation_legend = FALSE,
           fontsize_col = 12)
dev.off()

#pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/Fig1C-test.pdf", genes_tissue_zscores_heatmap, width=4, height=7)
```
