---
title: "EDF4"
output: html_document
---

```{r setup, include=FALSE}
#set Knitr option
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

#upload libraries
library(ggplot2)
library(mixOmics)
library(hashmap)
library(reshape2)
library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(viridis)
library(gridExtra)
library(egg)

#set directories
home="/Users/federica/mnt/"
gene_sets_dir=paste0(home, "projects/bilaterian_GE/data/gene_sets/")
#tissue_expr_dir=paste0(home, "projects/bilaterian_GE/data/preprocessing/average_expr_by_tissue/")
pca_dir=paste0(home, "projects/bilaterian_GE/data/pca_analysis_all_norms/")
metadata_dir=paste0(home, "projects/bilaterian_GE/data/samples_metadata/")
splsda_dir= paste0(home, "projects/bilaterian_GE/data/splsda_analysis/")
diff_expr_dir = paste0(home, "projects/bilaterian_GE/data/differential_expression/")
general_patterns_dir = paste0(home, "projects/bilaterian_GE/data/vertebrates_vs_insects_general_patterns/")
branches_length_dir = paste0(home, "projects/bilaterian_GE/data/branches_length_analysis/")

#set variables
my_version = "All_version2"
my_category = "STRICT"
my_evo_type = "conserved"
clades = c("Vertebrata", "Insecta", "Bilateria")
clades_PCA = c("Vertebrata", "Insecta", "Bilateria")
options("scipen"=100, "digits"=4)

all_species = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi")
ordered_species = all_species
Bilateria = all_species
Vertebrata = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi")
Insecta = c("Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi")
Outgroups = c("Bla", "Sp2", "Sma", "Obi")
all_tissues=c("Adipose", "DigestiveTract", "Kidney", "Epithelial", "Muscle", "Neural", "Ovary", "Testis")
ordered_tissues = c("Neural", "Testis", "Ovary", "Muscle", "Kidney", "Epithelial", "DigestiveTract", "Adipose")

#set aestetics vectors
my_color_vector = c("Neural"="mediumblue", "Testis"="violet", "Ovary"="darkorchid", "Muscle"="springgreen3", 
                    "Kidney"="gold", "Epithelial"="steelblue1", "DigestiveTract"="chocolate1", "Adipose"="firebrick1")
my_shapes_vector = c("Hs2"=0, "Mm2"=1, "Bt2"=2, "Mdo"=3, "Gga"=4, "Xtr"=5, "Dre"=6, "Cmi"=7, "Bla"=9, "Sp2"=8, 
                     "Dme"=15, "Eba"=18, "Aae"= 23, "BmA"=25, "Tca"=17, "Bge"=10, "Ame"=16, "Cdi"=13, "Sma"=14, "Obi"=11)
my_alpha_vector=c("Hs2"=1, "Mm2"=1, "Bt2"=1, "Mdo"=1, "Gga"=1, "Xtr"=1, "Dre"=1, "Cmi"=1, "Bla"=0.5, "Sp2"=0.5, "Sma"=0.5, "Ame"=0.5, "Dme"=0.5, "Cdi"=0.5, "Obi"=0.5, "Bge"=0.5, "BmA"=0.5, "Tca"=0.5)
my_sets_color = c("Vertebrata"= "mediumorchid", "Deuterostoma"="olivedrab3", "Insecta"="tan3", "Protostoma"="yellow", "Bilateria"="firebrick1", "Outgroups"="dimgray")
my_species_colors=c("Hs2"="#00BFFF", "Mm2"="#159DFF", "Bt2"="#1873CD", "Mdo"="#174B8B", "Gga"="#3F3F8B", "Xtr"="#64398B", "Dre"="#82359D", "Cmi"="#9932CC", "Bla"="#2E8B57", "Sp2"="#96B12B", "Obi"="#FFFF00", "Sma"="#FFCC33", "Cdi"="goldenrod", "Bge"="burlywood2", "Ame"="#FF9966", "Tca"="#FF6600", "BmA"="#CC6600", "Aae"="#993300", "Eba"="firebrick3", "Dme"="red")
my_copy_status_colors = c("single_copy_ortholog"="gray18", "duplicated"="gray76")


#Create named vector with PC and corresponding tissue
PC_tissue_named_vector = c("1"="Neural", "2"="Testis", "3"="Ovary", 
                          "4"="Muscle", "5"="Kidney", "6"="Epithelial", 
                          "7"="DigestiveTract", "8"="Adipose")
paletteLength = 75
palette_brewer = colorRampPalette(rev(brewer.pal(11, "RdBu")))(paletteLength)
```

```{r functions, warning=FALSE, message=FALSE, echo=FALSE, dependson="setup"}
number_ticks <- function(n) {function(limits) pretty(limits, n)}

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

####################################
####################################

get_cor_table = function(input_table, query_species, my_tissue)  {
  #select the Neural columns belonging to the set species
  tissue_samples = colnames(input_table)[grep(my_tissue, colnames(input_table))]
  #subset the table: only tissue samples
  tissue_expr_table = input_table[,tissue_samples]
  colnames(tissue_expr_table) = sub("_.*", "", colnames(tissue_expr_table))
  set_species = colnames(tissue_expr_table)
  #get target species depending on the species set
  all_target_species = set_species
  final_matrix =  vector()
  if (!(query_species %in% colnames(tissue_expr_table))) {
    final_table = c(query_species, NA, my_tissue, NA)
      return(final_table)} else {
  for (target_species in all_target_species) {
    subsetted_table = tissue_expr_table[,c(query_species, target_species)]
    subsetted_table = subsetted_table[complete.cases(subsetted_table),] #remove all rows containing one or two NAs
    query_vector  = as.vector(subsetted_table[,query_species]) #isolate query vector
    target_vector = as.vector(subsetted_table[,target_species]) #isolate target vector
    rho = cor.test(query_vector, target_vector, method="spearman")$estimate #isolate rho
    final_matrix = rbind(final_matrix, c(query_species, target_species, my_tissue, rho)) #append to final matrix
  }
  final_table = as.data.frame(final_matrix)
  colnames(final_table) = c("species_query", "species_target", "tissue", "cor")
  final_table$cor = as.numeric(as.vector(final_table$cor))
  return(final_table)
  }
}

####################################
####################################

plot_gene_expr = function(original_OG_ID, loadings_expr_df_long, OGID_humanID_dict, Vertebrata, Insecta, Outgroups) {
  all_plots = list()
  i = 1
  for (clade in c("Vertebrata", "Insecta", "Outgroups")) {
    my_OG_ID = paste0(OGID_humanID_dict$find(original_OG_ID), " ~ ", original_OG_ID)
    OG_expr_df = subset(loadings_expr_df_long, OG_ID == original_OG_ID)
    my_max = max(OG_expr_df$Expr, na.rm=TRUE)
    my_min = min(OG_expr_df$Expr, na.rm=TRUE)
    if (clade == "Vertebrata") {OG_expr_df = subset(OG_expr_df, Species %in% Vertebrata)}
    if (clade == "Insecta") {OG_expr_df = subset(OG_expr_df, Species %in% Insecta)}
    if (clade == "Outgroups") {OG_expr_df = subset(OG_expr_df, Species %in% Outgroups)}
    
    expr_plot = ggplot(data=OG_expr_df, aes(x=Tissue, y=Expr, fill=Tissue), color="black") +
      geom_boxplot(alpha=0.7, outlier.shape = NA) +
      geom_jitter(aes(shape=Species), width=0.2, fill="black") +
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_shapes_vector) +
      theme_bw() +
      theme(axis.title = element_text(color="black"),
            axis.text.x = element_text(color="black", angle=30, hjust=1, vjust=1)
            ) +
      guides(fill=FALSE) +
      ggtitle(paste0(my_OG_ID, " ~ ", clade)) +
      ylim(c(my_min, my_max))
    
    all_plots[[i]] = expr_plot
    i = i+1
  }
  final_plot = plot_grid(all_plots[[1]], all_plots[[2]], all_plots[[3]], ncol=3, rel_widths = c(1,1,1))
  return(final_plot)
}


####################################
####################################

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

```

```{r generate_metadata_table, echo=FALSE, warning=FALSE, message=FALSE, dependson="setup"}
all_metadata_df = vector()
for (species in all_species) {
  file_species = species
  if (species == "BmA") {file_species= "Bmo"}
  metadata_df = unique(read.delim(paste0(metadata_dir, file_species, "_samples_info.tab"), header=TRUE)[,1:3])
  colnames(metadata_df) = c("species", "tissues", "metasample")
  metadata_df$species = rep(species, nrow(metadata_df)) #This is necessary only to translate Bmo to BmA
  rownames(metadata_df) = paste0(rep(species, nrow(metadata_df)), "_", as.vector(metadata_df$metasample))
  metadata_df$metasample = NULL
  all_metadata_df = rbind(all_metadata_df, metadata_df)
}
colnames(all_metadata_df) = c("species", "tissues")

sample_tissue_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$tissues))
sample_species_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$species))
```


<!-- Panel A,B -->
<!-- Sequence similarities and expression correlations distribs for single copy orthologs -->
```{r expr_cor_vs_seq_sim_single_copy_orthologs, echo=FALSE, message=FALSE, warning=FALSE, dependson=c("setup", "functions"), fig.height=4, fig.width=10}
## Get lowly duplicated orthogroups
conserved_associated_tissues_df = read.delim(paste0(ts_gains_losses_dir, my_version, "/Bilateria_conserved_orthogroups-All_genes-associated_tissues.tab"),
                                       header=FALSE, col.names=c("OG_ID", "Species", "GeneID", "Tau", "Tissue", "Paralog_tissue", "Expr_cutoff"), stringsAsFactors = FALSE)
#Isolate the orthogroups with repeated species: these will be the duplicated orthogroups.
conserved_associated_tissues_df =
  conserved_associated_tissues_df %>%
  unite("OG_ID_Species", c("OG_ID", "Species"), sep="-", remove=FALSE)

all_OGID_species_counts = table(conserved_associated_tissues_df$OG_ID_Species)
all_duplicated_OGID_species_df = as.data.frame(all_OGID_species_counts[all_OGID_species_counts>1])
colnames(all_duplicated_OGID_species_df) = c("OGID_Species", "Count")
all_duplicated_OGID_species_df$OG_ID = sub("-.*", "", all_duplicated_OGID_species_df$OGID_Species)

duplicated_species_count_by_OG_df = all_duplicated_OGID_species_df %>%
  group_by(OG_ID) %>%
  summarise(Dup_species = n())

#Create 3 groups of duplicated orthogropus: 1-3, 4-8, >8.
single_copy = unique(as.vector(subset(conserved_associated_tissues_df, !(OG_ID %in% as.vector(duplicated_species_count_by_OG_df$OG_ID)))$OG_ID))
#lowly_dup = unique(subset(duplicated_species_count_by_OG_df, Dup_species %in% c(1))$OG_ID)
#lowly_dup = c(single_copy, lowly_dup)

input_expr_cor_df = read.delim(paste0(general_patterns_dir, my_version, "/expression_correlations_spearman_by_clade-BH_genes-NORM.tab"), header=TRUE)
###Filter for single copy orthogroups
input_expr_cor_df = subset(input_expr_cor_df, OG_ID %in% single_copy)

expr_cor_joint_plot = ggplot(data=input_expr_cor_df) +
  geom_density(aes(x=expression_correlations_spearman_insecta), color="tan3", alpha=0.5, fill="tan3") +
  geom_density(aes(x=expression_correlations_spearman_vertebrata), color="darkorchid", alpha=0.5, fill="darkorchid") +
  theme_bw() +
  theme(axis.text = element_text(color="black"),
        axis.title.x = element_text(color="black"),
        axis.title.y = element_blank(),
        plot.margin = unit(c(-0.5, 5.5, 5.5, 5.5), "pt")) +
  scale_x_continuous(breaks = number_ticks(5)) +
  scale_y_continuous(breaks = number_ticks(4), limits=c(0,3)) +
  xlab("Average\nexpression correlation")

print(expr_cor_joint_plot)

input_seq_sim_df = read.delim(paste0(general_patterns_dir, my_version, "/sequence_similarities_by_clade-BH_genes.tab"), header=TRUE)
input_seq_sim_df  = subset(input_seq_sim_df, OG_ID %in% single_copy)
seq_sim_joint_plot = ggplot(data=input_seq_sim_df) +
  geom_density(aes(x=sequence_similarities_insecta), color="tan3", alpha=0.5, fill="tan3") +
  geom_density(aes(x=sequence_similarities_vertebrata), color="darkorchid", alpha=0.5, fill="darkorchid") +
  theme_bw() +
  theme(axis.text = element_text(color="black"),
        axis.title.x = element_text(color="black"),
        axis.title.y = element_blank(),
        plot.margin = unit(c(5.5, 5.5, -0.5, 5.5), "pt")) +
  scale_x_continuous(breaks = number_ticks(6)) +
  scale_y_continuous(breaks = number_ticks(4), limits=c(0,3)) +
  xlab("Average\nsequence similarity")

print(seq_sim_joint_plot)

#Wilcoxon test to see if the two distributions are significantly different
wilcoxon_res = wilcox.test(input_seq_sim_df$sequence_similarities_vertebrata, input_seq_sim_df$sequence_similarities_insecta)

panel_CD = egg::ggarrange(seq_sim_joint_plot, expr_cor_joint_plot, ncol=1, labels=c("B", "C"), draw=FALSE)
#panel_CD = plot_grid(seq_sim_joint_plot, expr_cor_joint_plot, ncol=1, labels=c("B", "C"), align="hv")
#panel_CD = ggpubr::ggarrange(seq_sim_joint_plot, expr_cor_joint_plot, ncol=1, labels=c("B", "C"), align="hv")
print(panel_CD)

panel_CD_horizontal = egg::ggarrange(seq_sim_joint_plot, expr_cor_joint_plot, ncol=2, labels=c("B", "C"), draw=FALSE)
print(panel_CD_horizontal)

#pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/new_sup/SupFig5-single_copy_orthologs_distribs.pdf", height=4, width=10)
#print(panel_CD_horizontal)
#dev.off()
```

<!-- panel C: the loadings of the spls-DA coordinates (maybe for all tissues?) -->
```{r plot_genes_connected_by_lines, echo=FALSE, warning=FALSE, message=FALSE, dependson=c("setup", "functions"), fig.width=5, fig.height=5.5}
expr_df = read.table(paste0(pca_dir, my_version, "/", my_category, "/Bilateria/", my_evo_type, "/Bilateria_", 
                              my_evo_type, "-tissue_average_expr-NOSVA-log2-TPMs-NORM-species_zscore-BH_genes.tab"), header=TRUE, row=1)
#expr_df = read.table(paste0(pca_dir, my_version, "/", my_category, "/Bilateria/", my_evo_type, "/Bilateria_", 
#                              my_evo_type, "-tissue_average_expr-NOSVA-log2-TPMs-NORM-BH_genes.tab"), header=TRUE, row=1)

all_dot_plots = list()
i = 0
### Cycle on the tissues
for (query_tissue in ordered_tissues) {
  final_figure_bilateria_plot_list = list() #initialize figure list for each tissue

  ###################################
  ########## Plot connected dots ####
  ###################################
  #Upload the loadings
  if (query_tissue == "Adipose") {
    my_loadings_vertebrates_OGs = vector()
  } else {
    my_loadings_vertebrate_file = paste0(splsda_dir, my_version, "/", my_category, "/Bilateria/", my_evo_type, 
                                         "/loadings_clade_tissue/metasamples_median_expr/", query_tissue, "/splsda_zscore_comb_v1/Vertebrata_",
                                         query_tissue, "_splsda-zscore_loadings_orthogroups-GO_input.txt")
    my_loadings_vertebrates_OGs = as.vector(read.delim(my_loadings_vertebrate_file, header=FALSE)$V1)
  }
  
  my_loadings_insects_file = paste0(splsda_dir, my_version, "/", my_category, "/Bilateria/", my_evo_type, 
                                     "/loadings_clade_tissue/metasamples_median_expr/", query_tissue, "/splsda_zscore_comb_v1/Insecta_",
                            query_tissue, "_splsda-zscore_loadings_orthogroups-GO_input.txt")
  my_loadings_insects_OGs = as.vector(read.delim(my_loadings_insects_file, header=FALSE)$V1)
  
  my_loadings_OGs = c(my_loadings_vertebrates_OGs, my_loadings_insects_OGs)
  
  #If there are at least 2 loadings
  if (length(my_loadings_OGs) > 1) {
    loadings_expr_df = expr_df[rownames(expr_df) %in% as.vector(my_loadings_OGs),] #Subset the expression dataframe only to the selected loadings
    loadings_expr_df_long = melt(as.matrix(loadings_expr_df))
    colnames(loadings_expr_df_long) = c("OG_ID", "Metasample", "Expr")
    loadings_expr_df_long$Species = sub("_.*", "", loadings_expr_df_long$Metasample)
    loadings_expr_df_long$Tissue = sub(".*_", "", loadings_expr_df_long$Metasample)
    #Add clade label based on the species
    clade_expr_df = loadings_expr_df_long %>% 
    mutate(Clade = case_when(Species %in% Vertebrata ~ "Vertebrata",
                             Species %in% Insecta ~ "Insecta",
                             Species %in% Outgroups ~ "Outgroups")
           )
    
    OG_zscore_df = clade_expr_df %>% group_by(OG_ID, Tissue, Clade) %>% #Group dataframe by orthogroup, tissue and clade
      summarize(zscore=median(Expr, na.rm=TRUE)) %>% #Compute the median value for each tissue in each clade
      ungroup %>%
      dplyr::filter(Tissue==query_tissue & Clade %in% c("Vertebrata", "Insecta"))
      # group_by(OG_ID) %>% #Group only by orthogroup
      # mutate(zscore = (median_expr - mean(median_expr, na.rm=TRUE))/sd(median_expr, na.rm=TRUE)) #compute the zscore across the median values
      
    OG_zscore_df$ID = paste0(OG_zscore_df$Clade, "_", OG_zscore_df$Tissue) #Combine clade and tissue in a unique ID
    OG_zscore_df$Clade = factor(OG_zscore_df$Clade, levels=c("Vertebrata", "Insecta"))
    #Add category
    OG_zscore_df$Category = rep("Vertebrata_specific", nrow=OG_zscore_df)
    OG_zscore_df$Category[OG_zscore_df$OG_ID %in% my_loadings_insects_OGs] = "Insecta_specific"
    
    vertebrata_count = nrow(subset(OG_zscore_df, Category=="Vertebrata_specific"))/2
    insecta_count = nrow(subset(OG_zscore_df, Category=="Insecta_specific"))/2
    
    dots_plot = ggplot(data=OG_zscore_df) +
      geom_point(aes(x=Clade, y=zscore, color=Category), size=1, alpha=0.6) +
      annotate("text", x="Vertebrata", y=3, label=vertebrata_count, size=3) +
      annotate("text", x="Insecta", y=3, label=insecta_count, size=3) +
      geom_line(aes(x=Clade, y=zscore, group=OG_ID, color=Category), size=0.5, alpha=0.6) +
      scale_x_discrete(expand = c(0.1, 0.1)) +
      scale_color_manual(values=c("Vertebrata_specific"="darkorchid", "Insecta_specific"="tan3")) +
      ggtitle(query_tissue) +
      #xlab(query_tissue) +
      theme_bw() +
      ylim(c(-1.5, 3.3)) +
      theme(#axis.title.x = element_text(color="black", face="bold", hjust=0.5, size=10),
            axis.title.x = element_blank(),
            axis.text.y = element_text(color="black", size=8),
            plot.title = element_text(color="black", face="bold", hjust=0.5, size=10),
            #axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            panel.grid.major.x = element_blank(),
            panel.grid.minor.x = element_blank(),
            panel.grid.minor.y = element_blank(),
            plot.margin = unit(c(5.5,0,0,0), "pt")
            ) +
      guides(color=FALSE)

    print(dots_plot)
    i = i+1
    all_dot_plots[[i]] = dots_plot
  }
}

#panel_c = plot_grid(plotlist = all_dot_plots, ncol=2)
#print(panel_c)

panel_c = egg::ggarrange(all_dot_plots[[1]], 
                         all_dot_plots[[2]] +
                           theme(axis.text.y = element_blank(),
                        axis.ticks.y = element_blank(),
                        axis.title.y = element_blank()),
                        all_dot_plots[[3]] +
                           theme(axis.text.y = element_blank(),
                        axis.ticks.y = element_blank(),
                        axis.title.y = element_blank()),
                         all_dot_plots[[4]] +
                          theme(axis.text.y = element_blank(),
                        axis.ticks.y = element_blank(),
                        axis.title.y = element_blank()),
                        all_dot_plots[[5]], 
                         all_dot_plots[[6]] +
                           theme(axis.text.y = element_blank(),
                        axis.ticks.y = element_blank(),
                        axis.title.y = element_blank()),
                        all_dot_plots[[7]] +
                           theme(axis.text.y = element_blank(),
                        axis.ticks.y = element_blank(),
                        axis.title.y = element_blank()),
                         all_dot_plots[[8]] +
                           theme(axis.text.y = element_blank(),
                        axis.ticks.y = element_blank(),
                        axis.title.y = element_blank()),
                        ncol=4, byrow = TRUE, draw = FALSE,
                        labels=c("c","","","","","","",""),
                        bottom = "prova\nprova"
                           )
print(panel_c)
pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/EDF_4c.pdf", width = 5, height = 5.5)
print(panel_c)
dev.off()
```
