---
title: "figS10-11"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Upload libraries
library(OUwie)
library(reshape2)
library(phylobase)
library(treeio)
library(ggplot2)
library(cowplot)
library(ggh4x)
library(tidyverse)
library(hashmap, lib.loc="/users/mirimia/fmantica/R/x86_64-pc-linux-gnu-library/4.0")
library(viridis)

## set seed
set.seed(30)

## Set directories
home = "/users/mirimia/fmantica/projects/"
OUwie_test_dir = paste0(home, "mixed_files/OUwie_validations/")

## Create variables
all_species = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi")
all_ancestors = c("Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma",
              "Bilateria", "Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma")

#This is to paint the trees in the right way
all_positions_edges = c("Euarchontoglires"=19, 
                        "Eutheria"=18, 
                        "Mammalia"=17, 
                        "Amniota"=16, 
                        "Tetrapoda"=15, 
                        "Euteleostomi"=14,
                        "Vertebrata"=13, 
                        "Chordata"=12, 
                        "Deuterostoma"=11,
                        "Cyclorrapha"=19, 
                        "Diptera"=18, 
                        "Panorpidae"=17, 
                        "Oligoneoptera"=16,
                        "Holometabola"=15, 
                        "Neoptera"=14, 
                        "Insecta"=13, 
                        "Arthropoda"=12, 
                        "Protostoma"=11,
                        "Hs2"=8, 
                        "Mm2"=7, 
                        "Bt2"=6, 
                        "Mdo"=5, 
                        "Gga"=4, 
                        "Xtr"=3, 
                        "Dre"=2, 
                        "Cmi"=1, 
                        "Bla"=9, 
                        "Sp2"=10, 
                        "Dme"=8, 
                        "Eba"=7, 
                        "Aae"=6, 
                        "Bmo"=5, 
                        "Tca"=4, 
                        "Ame"=3, 
                        "Bge"=2, 
                        "Cdi"=1, 
                        "Sma"=9, 
                        "Obi"=10)

Bilateria = all_species
Euarchontoglires = c("Hs2", "Mm2")
Eutheria = c(Euarchontoglires, "Bt2")
Mammalia = c(Eutheria, "Mdo")
Amniota = c(Mammalia, "Gga")
Tetrapoda = c(Amniota, "Xtr")
Euteleostomi = c(Tetrapoda, "Dre")
Vertebrata = c(Euteleostomi, "Cmi")
Chordata = c(Vertebrata, "Bla")
Deuterostoma = c(Chordata, "Sp2")
Cyclorrapha = c("Dme", "Eba")
Diptera = c(Cyclorrapha, "Aae")
Panorpidae = c(Diptera, "Bmo")
Oligoneoptera = c(Panorpidae, "Tca")
Holometabola = c(Oligoneoptera, "Ame")
Neoptera = c(Holometabola, "Bge")
Insecta = c(Neoptera, "Cdi")
Arthropoda = c(Insecta, "Sma")
Protostoma = c(Arthropoda, "Obi")
Hs2 = "Hs2" 
Mm2 = "Mm2" 
Bt2 = "Bt2" 
Mdo = "Mdo" 
Gga = "Gga" 
Xtr = "Xtr" 
Dre = "Dre" 
Cmi = "Cmi" 
Bla = "Bla" 
Sp2 = "Sp2" 
Dme = "Dme"
Eba = "Eba"
Aae = "Aae" 
Bmo = "Bmo" 
Tca = "Tca"
Ame = "Ame"
Bge = "Bge" 
Cdi = "Cdi" 
Sma = "Sma" 
Obi = "Obi"

all_ancestors_by_age = c("Deuterostoma", "Protostoma", "Chordata", "Arthropoda", "Vertebrata", "Insecta", "Euteleostomi", "Neoptera",
                         "Tetrapoda", "Holometabola", "Amniota", "Oligoneoptera", "Mammalia", "Panorpidae", "Eutheria", "Diptera",
                         "Euarchontoglires", "Cyclorrapha")

my_species_colors=c("Hs2"="#00BFFF", "Mm2"="#159DFF", "Bt2"="#1873CD", "Mdo"="#174B8B", "Gga"="#3F3F8B", "Xtr"="#64398B", "Dre"="#82359D", "Cmi"="#9932CC", "Bla"="#2E8B57", "Sp2"="#96B12B", "Obi"="#FFFF00", "Sma"="#FFCC33", "Cdi"="goldenrod", "Bge"="burlywood2", "Ame"="#FF9966", "Tca"="#FF6600", "BmA"="#CC6600", "Aae"="#993300", "Eba"="firebrick3", "Dme"="red")

####Complete this
my_ancestor_colors = c("Euarchontoglires"="#159DFF", "Eutheria"="#1873CD", "Mammalia"="#174B8B", "Amniota"="#3F3F8B", "Tetrapoda"="#64398B", "Euteleostomi"="#82359D", "Vertebrata"="#9932CC", "Chordata"="#2E8B57", "Deuterostoma"="#96B12B", "Protostoma"="#FFFF00", "Arthropoda"="#FFCC33", "Insecta"="goldenrod", "Neoptera"="burlywood2", "Holometabola"="#FF9966", "Oligoneoptera"="#FF6600", "Panorpidae"="#CC6600", "Diptera"="#993300", "Cyclorrapha"="firebrick3")

all_ancestors_tree_positions = c("Euarchontoglires"=2, 
                        "Eutheria"=3, 
                        "Mammalia"=4, 
                        "Amniota"=5, 
                        "Tetrapoda"=6, 
                        "Euteleostomi"=7,
                        "Vertebrata"=8, 
                        "Chordata"=9, 
                        "Deuterostoma"=10,
                        "Cyclorrapha"=2, 
                        "Diptera"=3, 
                        "Panorpidae"=4, 
                        "Oligoneoptera"=5,
                        "Holometabola"=6, 
                        "Neoptera"=7, 
                        "Insecta"=8, 
                        "Arthropoda"=9, 
                        "Protostoma"=10)

all_ancestors_tree_positions_dict = hashmap(names(all_ancestors_tree_positions), unname(all_ancestors_tree_positions))
```

```{r functions, echo=FALSE, warning=FALSE, message=FALSE, dependson=c("setup")}
###### General
sample_n_groups = function(tbl, size, replace = FALSE, weight = NULL) {
  # regroup when done
  grps = tbl %>% groups %>% lapply(as.character) %>% unlist
  # check length of groups non-zero
  keep = tbl %>% summarise() %>% ungroup() %>% sample_n(size, replace, weight)
  # keep only selected groups, regroup because joins change count.
  # regrouping may be unnecessary but joins do something funky to grouping variable
  tbl %>% right_join(keep, by=grps) %>% group_by(!!!grps)
}

splitFacet <- function(x){
  facet_vars <- names(x$facet$params$facets)         # 1
  x$facet    <- ggplot2::ggplot()$facet              # 2
  datasets   <- split(x$data, x$data[facet_vars])    # 3
  new_plots  <- lapply(datasets,function(new_data) { # 4
    x$data <- new_data
    x})
} 

###### Input generation
get_TS_gains_compare_OU_models_inputs = function(query_tissue, expr_prop_file, inferred_gains_file, inferred_losses_file, expr_cutoff_info_file) {
  ####### Read in file for expression proportions
  expr_prop_df = read.delim(expr_prop_file, header=TRUE, sep="\t")
  ## Transform to long format
  expr_prop_long_df = melt(expr_prop_df, id.vars = c("OG_ID", "Species"), value.name = "Expr_prop", variable.name = "Tissue")
  
  ###### Read in file for inferred gains
  inferred_gains_df = read.delim(inferred_gains_file, header=TRUE)
  inferred_gains_df = inferred_gains_df %>%
    mutate(Branch = ifelse(TS_gain %in% c(Deuterostoma, deuterostoma_y_labels), "Deuterostoma", "Protostoma")) #%>%
    #filter(Category=="STRICT") #Let's start with only STRICT gains
  
  ###### Read in file for expression cutoff information
  expr_cutoff_info_df = read.delim(expr_cutoff_info_file, header=FALSE, col.names=c("OG_ID", "Species", "GeneID", "Tau", "Associated_tissue", "Expr_cutoff"))
  expr_cutoff_info_df = expr_cutoff_info_df %>%
    select(OG_ID, Species, Expr_cutoff)
  
  all_OGs_model_fitting_input_df = expr_prop_long_df %>%
    mutate(Branch = ifelse(Species %in% Deuterostoma, "Deuterostoma", "Protostoma")) %>%
    filter(Tissue==query_tissue) %>%
    left_join(expr_cutoff_info_df, by=c("OG_ID", "Species")) %>% #add expr cutoff info
    group_by(OG_ID, Branch) %>%
    filter(all(!is.na(Expr_prop) & Expr_cutoff=="YES_EXPR")) %>% #select only those entries per branch that have all species (no NAs)
    inner_join(inferred_gains_df, by=c("OG_ID", "Branch")) %>%
    #I do have to select those different from Deuterostoma, Protostoma and Bilateria (otherwise the model does not work)
    filter(!(TS_gain %in% c("Deuterostoma", "Protostoma", "Bilateria"))) %>%
    mutate(TS_info = ifelse(Species %in% eval(parse(text = TS_gain)), "TS", "NO_TS")) %>%
    select(-Tissue, -Expr_cutoff) %>%
    ungroup()
  
  ###### Read in losses file
  inferred_losses_df = read.delim(inferred_losses_file, header=TRUE)
  inferred_losses_df = inferred_losses_df %>%
    mutate(Branch = ifelse(TS_losses %in% c(Deuterostoma, deuterostoma_y_labels), "Deuterostoma", "Protostoma"))
  
  ###### Return files
  return(list(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df))
}

get_randomized_BH_compare_OU_models_inputs = function(query_tissue, expr_prop_file, inferred_gains_file, inferred_losses_file, expr_cutoff_info_file, evaluated_TS_gains_df) {
  ####### Read in file for expression proportions
  expr_prop_df = read.delim(expr_prop_file, header=TRUE, sep="\t")
  ## Transform to long format
  expr_prop_long_df = melt(expr_prop_df, id.vars = c("OG_ID", "Species"), value.name = "Expr_prop", variable.name = "Tissue")
  
  ###### Read in file for inferred gains
  inferred_gains_df = read.delim(inferred_gains_file, header=TRUE)
  inferred_gains_df = inferred_gains_df %>%
    mutate(Branch = ifelse(TS_gain %in% c(Deuterostoma, deuterostoma_y_labels), "Deuterostoma", "Protostoma")) #%>%
    #filter(Category=="STRICT") #Let's start with only STRICT gains
  
  ###### Read in file for expression cutoff information
  expr_cutoff_info_df = read.delim(expr_cutoff_info_file, header=FALSE, col.names=c("OG_ID", "Species", "GeneID", "Expr_cutoff"))
  expr_cutoff_info_df = expr_cutoff_info_df %>%
    select(OG_ID, Species, Expr_cutoff)
  
  all_OGs_model_fitting_input_df = expr_prop_long_df %>%
  mutate(Branch = ifelse(Species %in% Deuterostoma, "Deuterostoma", "Protostoma")) %>%
  filter(Tissue==query_tissue) %>%
  left_join(expr_cutoff_info_df, by=c("OG_ID", "Species")) %>% #Add expr cutoff info
  group_by(OG_ID, Branch) %>%
  filter(all(!is.na(Expr_prop) & Expr_cutoff=="YES_EXPR")) #select only those entries per branch that have one gene for all species (no NAs) and pass the expression cutoff
  
  ## This is where the randomization of the labels takes place
  randomized_entries_both_branches_df = vector()
  for (my_branch in c("Protostoma", "Deuterostoma")) {
    branch_evaluated_TS_gains = unique(as.vector(subset(evaluated_TS_gains_df, Branch == my_branch)$OG_ID))
    
    branch_all_OGs_model_fitting_input_df = all_OGs_model_fitting_input_df %>% 
    filter(Branch == my_branch) %>%
    group_by(OG_ID) %>% 
    sample_n_groups(length(branch_evaluated_TS_gains)) %>%  
    ungroup()
  
  OGID_randomized_ID_dict = hashmap(sample(unique(as.vector(branch_all_OGs_model_fitting_input_df$OG_ID))), branch_evaluated_TS_gains)
  branch_all_OGs_model_fitting_input_df$OG_ID = OGID_randomized_ID_dict$find(as.vector(branch_all_OGs_model_fitting_input_df$OG_ID))
  randomized_entries_both_branches_df = rbind(randomized_entries_both_branches_df, branch_all_OGs_model_fitting_input_df)
}

  
  all_OGs_model_fitting_input_df = randomized_entries_both_branches_df %>%  
    inner_join(inferred_gains_df, by=c("OG_ID", "Branch")) %>%
    #I do have to select those different from Deuterostoma, Protostoma and Bilateria (otherwise I do not think that the model can work)
    filter(!(TS_gain %in% c("Deuterostoma", "Protostoma", "Bilateria"))) %>%
    mutate(TS_info = ifelse(Species %in% eval(parse(text = TS_gain)), "TS", "NO_TS")) %>%
    select(-Tissue) %>%
    ungroup()
  
 ###### Read in losses file
  inferred_losses_df = read.delim(inferred_losses_file, header=TRUE)
  inferred_losses_df = inferred_losses_df %>%
    mutate(Branch = ifelse(TS_losses %in% c(Deuterostoma, deuterostoma_y_labels), "Deuterostoma", "Protostoma"))
  
  ###### Return files
  return(list(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df))
}

get_randomized_BH_noTS_compare_OU_models_inputs = function(query_tissue, expr_prop_file, inferred_gains_file, inferred_losses_file, expr_cutoff_info_file, evaluated_TS_gains_df, non_TS_prone_file) {
  ####### Read in file for expression proportions
  expr_prop_df = read.delim(expr_prop_file, header=TRUE, sep="\t")
  ## Transform to long format
  expr_prop_long_df = melt(expr_prop_df, id.vars = c("OG_ID", "Species"), value.name = "Expr_prop", variable.name = "Tissue")
  
  ###### Read nonTS-prone OGs file and filter
  non_TS_prone_OGs = as.vector(read.delim(non_TS_prone_file, header=FALSE, col.names="OG_ID")$OG_ID)
  expr_prop_long_df = subset(expr_prop_long_df, OG_ID %in% non_TS_prone_OGs)
  
  ###### Read in file for inferred gains
  inferred_gains_df = read.delim(inferred_gains_file, header=TRUE)
  inferred_gains_df = inferred_gains_df %>%
    mutate(Branch = ifelse(TS_gain %in% c(Deuterostoma, deuterostoma_y_labels), "Deuterostoma", "Protostoma")) #%>%
    #filter(Category=="STRICT") #Let's start with only STRICT gains
  
  ###### Read in file for expression cutoff information
  expr_cutoff_info_df = read.delim(expr_cutoff_info_file, header=FALSE, col.names=c("OG_ID", "Species", "GeneID", "Expr_cutoff"))
  expr_cutoff_info_df = expr_cutoff_info_df %>%
    select(OG_ID, Species, Expr_cutoff)
  
  all_OGs_model_fitting_input_df = expr_prop_long_df %>%
  mutate(Branch = ifelse(Species %in% Deuterostoma, "Deuterostoma", "Protostoma")) %>%
  filter(Tissue==query_tissue) %>%
  left_join(expr_cutoff_info_df, by=c("OG_ID", "Species")) %>% #Add expr cutoff info
  group_by(OG_ID, Branch) %>%
  filter(all(!is.na(Expr_prop) & Expr_cutoff=="YES_EXPR")) #select only those entries per branch that have one gene for all species (no NAs) and pass the expression cutoff
  
  ## This is where the randomization of the labels takes place
  randomized_entries_both_branches_df = vector()
  for (my_branch in c("Protostoma", "Deuterostoma")) {
    branch_evaluated_TS_gains = unique(as.vector(subset(evaluated_TS_gains_df, Branch == my_branch)$OG_ID))
    
    branch_all_OGs_model_fitting_input_df = all_OGs_model_fitting_input_df %>% 
    filter(Branch == my_branch) %>%
    group_by(OG_ID) %>% 
    sample_n_groups(length(branch_evaluated_TS_gains)) %>%  
    ungroup()
  
  OGID_randomized_ID_dict = hashmap(sample(unique(as.vector(branch_all_OGs_model_fitting_input_df$OG_ID))), branch_evaluated_TS_gains)
  branch_all_OGs_model_fitting_input_df$OG_ID = OGID_randomized_ID_dict$find(as.vector(branch_all_OGs_model_fitting_input_df$OG_ID))
  randomized_entries_both_branches_df = rbind(randomized_entries_both_branches_df, branch_all_OGs_model_fitting_input_df)
}

  
  all_OGs_model_fitting_input_df = randomized_entries_both_branches_df %>%  
    inner_join(inferred_gains_df, by=c("OG_ID", "Branch")) %>%
    #I do have to select those different from Deuterostoma, Protostoma and Bilateria (otherwise I do not think that the model can work)
    filter(!(TS_gain %in% c("Deuterostoma", "Protostoma", "Bilateria"))) %>%
    mutate(TS_info = ifelse(Species %in% eval(parse(text = TS_gain)), "TS", "NO_TS")) %>%
    select(-Tissue) %>%
    ungroup()
  
 ###### Read in losses file
  inferred_losses_df = read.delim(inferred_losses_file, header=TRUE)
  inferred_losses_df = inferred_losses_df %>%
    mutate(Branch = ifelse(TS_losses %in% c(Deuterostoma, deuterostoma_y_labels), "Deuterostoma", "Protostoma"))
  
  ###### Return files
  return(list(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df))
}

###### Models comparisons
compare_OU_models = function(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df) {
  ## Run the models gain by gain
  gains_model_fitting_df = vector()
  all_expr_prop_averages_df = vector()
  gains_info_df = vector()
  
  for (my_branch in c("Deuterostoma", "Protostoma")) {
    branch_OGs_model_fitting_input_df = subset(all_OGs_model_fitting_input_df, Branch == my_branch)
    branch_OGs = unique(as.vector(branch_OGs_model_fitting_input_df$OG_ID))
    ### Set tree for model testing
    if (my_branch == "Protostoma") {TS_tree = protostome_tree}
    if (my_branch == "Deuterostoma") {TS_tree = deuterostome_tree}
    
    ###### Cycle on all orthogroups with gains
    for (my_OG_ID in branch_OGs) {
      my_TS_gain = unique(as.vector(subset(branch_OGs_model_fitting_input_df, OG_ID == my_OG_ID))$TS_gain)
      my_category = unique(as.vector(subset(branch_OGs_model_fitting_input_df, OG_ID == my_OG_ID))$Category)
      if (length(my_TS_gain) > 1) {next}
      
      OG_model_fitting_input_df = branch_OGs_model_fitting_input_df %>%
        filter(OG_ID==my_OG_ID) %>%
        select(c("Species", "TS_info", "Expr_prop")) %>%
        as.data.frame()
      #Set rownames
      rownames(OG_model_fitting_input_df) = OG_model_fitting_input_df$Species
      
      ###### Integrate losses
      OG_losses_df = subset(inferred_losses_df, OG_ID==my_OG_ID & Branch==my_branch)
      if (nrow(OG_losses_df) > 0) {
        OG_losses_species = as.vector(subset(OG_losses_df, TS_losses %in% all_species)$TS_losses)
        OG_losses_ancestor = as.vector(subset(OG_losses_df, !(TS_losses %in% all_species))$TS_losses)
        
        #Get the species corresponding to the ancestor
        OG_losses_ancestor_single_species = vector()
        if (length(OG_losses_ancestor) > 0) {
          #Make not to count the loss if it's above the current gain (in case of gain after a loss)
          OG_losses_ancestor = OG_losses_ancestor[which(all_ancestors %in% OG_losses_ancestor) < which(all_ancestors == my_TS_gain)]
          OG_losses_ancestor_single_species = unlist(lapply(OG_losses_ancestor, function(x) {eval(parse(text = x))}))
          }
        #Replace TS with NO_TS status for the losses
        OG_model_fitting_input_df$TS_info[OG_model_fitting_input_df$Species %in% c(OG_losses_species, OG_losses_ancestor_single_species)] = "NO_TS"
      }
      
      ###### Build phylogenetic tree with TS info
      smap.tree = paintSubTree(TS_tree, node=all_positions_edges[[my_TS_gain]], state="TS", anc="NO_TS", stem=TRUE)
      #Add the losses
      all_OG_losses = c(OG_losses_species, OG_losses_ancestor)
      if (length(all_OG_losses) > 0) {
        for (element in all_OG_losses) {
          smap.tree = paintSubTree(smap.tree, node=all_positions_edges[[element]], state="NO_TS", stem=TRUE)
        }
      }
      #plot(smap.tree, fsize=0.8, ftype="i")
      
      ###### Get averages among TS and NonTS species
      expr_prop_averages_df = OG_model_fitting_input_df %>% 
        group_by(TS_info) %>%
        summarise(Expr_prop_avg = mean(Expr_prop)) %>%
        mutate(OG_ID = my_OG_ID,
               Branch = my_branch) %>%
        select(c("OG_ID", "Branch", "TS_info", "Expr_prop_avg"))
    
      all_expr_prop_averages_df = rbind(all_expr_prop_averages_df, expr_prop_averages_df)
      #######
      
      ####### Save info about TS and non-TS status
      info_df = OG_model_fitting_input_df %>%
        mutate(OG_ID = my_OG_ID,
               Branch = my_branch) %>%
        select(c("OG_ID", "Branch", "Species", "TS_info", "Expr_prop"))
      
      gains_info_df = rbind(gains_info_df, info_df)
      #######
      
      ###### Fit models
      fitOU1 = OUwie(smap.tree, OG_model_fitting_input_df, model="OU1", simmap.tree=TRUE) ## single optima
      fitOUM = OUwie(smap.tree, OG_model_fitting_input_df, model="OUM", simmap.tree=TRUE) ## multiple optima
      #Compare models fit
      aic = setNames(c(fitOU1$AIC, fitOUM$AIC), c("OU1","OUM"))
      aic_weights = aic.w(aic)
      #See which one is a better fit
      if (aic_weights[1] > aic_weights[2]) {better_fit = "Single_optimum"} else {better_fit = "Multiple_optima"}
      
      #Create dataframe and join to the final one
      OGs_model_fitting_df = data.frame(OG_ID = my_OG_ID,
                                        Branch = my_branch,
                                        TS_gain = my_TS_gain,
                                        Category = my_category,
                                        OU1_aic = fitOU1$AIC,
                                        OUM_aic = fitOUM$AIC,
                                        OU1_aicW = unname(aic_weights[1]),
                                        OUM_aicW = unname(aic_weights[2]),
                                        Better_fit = better_fit)
      
      gains_model_fitting_df = rbind(gains_model_fitting_df, OGs_model_fitting_df)
    }
  }
  ### Add query tissue to final dataframes
  gains_model_fitting_df = gains_model_fitting_df %>% mutate(Query_tissue = query_tissue)
  all_expr_prop_averages_df = all_expr_prop_averages_df %>% mutate(Query_tissue = query_tissue)
  gains_info_df = gains_info_df %>% mutate(Query_tissue = query_tissue)
  
  ### Return final dataframes
  return(list(gains_model_fitting_df, all_expr_prop_averages_df, gains_info_df))
}

compare_BM_OU_models = function(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df) {
  ## Run the models gain by gain
  gains_model_fitting_df = vector()
  all_expr_prop_averages_df = vector()
  gains_info_df = vector()
  
  for (my_branch in c("Deuterostoma", "Protostoma")) {
    branch_OGs_model_fitting_input_df = subset(all_OGs_model_fitting_input_df, Branch == my_branch)
    branch_OGs = unique(as.vector(branch_OGs_model_fitting_input_df$OG_ID))
    ### Set tree for model testing
    if (my_branch == "Protostoma") {TS_tree = protostome_tree}
    if (my_branch == "Deuterostoma") {TS_tree = deuterostome_tree}
    
    ###### Cycle on all orthogroups with gains
    for (my_OG_ID in branch_OGs[1:20]) {
      my_TS_gain = unique(as.vector(subset(branch_OGs_model_fitting_input_df, OG_ID == my_OG_ID))$TS_gain)
      my_category = unique(as.vector(subset(branch_OGs_model_fitting_input_df, OG_ID == my_OG_ID))$Category)
      if (length(my_TS_gain) > 1) {next}
      
      OG_model_fitting_input_df = branch_OGs_model_fitting_input_df %>%
        filter(OG_ID==my_OG_ID) %>%
        select(c("Species", "TS_info", "Expr_prop")) %>%
        as.data.frame()
      #Set rownames
      rownames(OG_model_fitting_input_df) = OG_model_fitting_input_df$Species
      
      ###### Integrate losses
      OG_losses_df = subset(inferred_losses_df, OG_ID==my_OG_ID & Branch==my_branch)
      if (nrow(OG_losses_df) > 0) {
        OG_losses_species = as.vector(subset(OG_losses_df, TS_losses %in% all_species)$TS_losses)
        OG_losses_ancestor = as.vector(subset(OG_losses_df, !(TS_losses %in% all_species))$TS_losses)
        
        #Get the species corresponding to the ancestor
        OG_losses_ancestor_single_species = vector()
        if (length(OG_losses_ancestor) > 0) {
          #Make not to count the loss if it's above the current gain (in case of gain after a loss)
          OG_losses_ancestor = OG_losses_ancestor[which(all_ancestors %in% OG_losses_ancestor) < which(all_ancestors == my_TS_gain)]
          OG_losses_ancestor_single_species = unlist(lapply(OG_losses_ancestor, function(x) {eval(parse(text = x))}))
          }
        #Replace TS with NO_TS status for the losses
        OG_model_fitting_input_df$TS_info[OG_model_fitting_input_df$Species %in% c(OG_losses_species, OG_losses_ancestor_single_species)] = "NO_TS"
      }
      
      ###### Build phylogenetic tree with TS info
      smap.tree = paintSubTree(TS_tree, node=all_positions_edges[[my_TS_gain]], state="TS", anc="NO_TS", stem=TRUE)
      #Add the losses
      all_OG_losses = c(OG_losses_species, OG_losses_ancestor)
      if (length(all_OG_losses) > 0) {
        for (element in all_OG_losses) {
          smap.tree = paintSubTree(smap.tree, node=all_positions_edges[[element]], state="NO_TS", stem=TRUE)
        }
      }
      #plot(smap.tree, fsize=0.8, ftype="i")
      
      ###### Get averages among TS and NonTS species
      expr_prop_averages_df = OG_model_fitting_input_df %>% 
        group_by(TS_info) %>%
        summarise(Expr_prop_avg = mean(Expr_prop)) %>%
        mutate(OG_ID = my_OG_ID,
               Branch = my_branch) %>%
        select(c("OG_ID", "Branch", "TS_info", "Expr_prop_avg"))
    
      all_expr_prop_averages_df = rbind(all_expr_prop_averages_df, expr_prop_averages_df)
      #######
      
      ####### Save info about TS and non-TS status
      info_df = OG_model_fitting_input_df %>%
        mutate(OG_ID = my_OG_ID,
               Branch = my_branch) %>%
        select(c("OG_ID", "Branch", "Species", "TS_info", "Expr_prop"))
      
      gains_info_df = rbind(gains_info_df, info_df)
      #######
      
      ###### Fit models
      fitOU1 = OUwie(smap.tree, OG_model_fitting_input_df, model="OU1", simmap.tree=TRUE) ## single optima
      fitBM1 = OUwie(smap.tree, OG_model_fitting_input_df, model="BM1", simmap.tree=TRUE) ## single optima BM
      #Compare models fit
      aic = setNames(c(fitOU1$AIC, fitBM1$AIC), c("OU1","BM1"))
      aic_weights = aic.w(aic)
      #See which one is a better fit
      if (aic_weights[1] > aic_weights[2]) {better_fit = "OU_single_optimum"} else {better_fit = "Brownian_single_optimum"}
      
      #Create dataframe and join to the final one
      OGs_model_fitting_df = data.frame(OG_ID = my_OG_ID,
                                        Branch = my_branch,
                                        TS_gain = my_TS_gain,
                                        Category = my_category,
                                        OU1_aic = fitOU1$AIC,
                                        BM1_aic = fitBM1$AIC,
                                        OU1_aicW = unname(aic_weights[1]),
                                        BM1_aicW = unname(aic_weights[2]),
                                        Better_fit = better_fit)
      
      gains_model_fitting_df = rbind(gains_model_fitting_df, OGs_model_fitting_df)
    }
  }
  ### Add query tissue to final dataframes
  gains_model_fitting_df = gains_model_fitting_df %>% mutate(Query_tissue = query_tissue)
  all_expr_prop_averages_df = all_expr_prop_averages_df %>% mutate(Query_tissue = query_tissue)
  gains_info_df = gains_info_df %>% mutate(Query_tissue = query_tissue)
  
  ### Return final dataframes
  return(list(gains_model_fitting_df, all_expr_prop_averages_df, gains_info_df))
}
```

```{r build_phylogenetic_tree, echo=FALSE, warning=FALSE, message=FALSE, dependson=c("setup", "functions")}
my_phylo_tree = read.newick(file=paste0(inferences_input_dir, "species_tree.nwk"))

#Set nodes correspondences with the ancestors
nodes_positions = c("Euarchontoglires"=30, 
                    "Eutheria"=29, 
                    "Mammalia"=28, 
                    "Amniota"=27, 
                    "Tetrapoda"=26, 
                    "Euteleostomi"=25, 
                    "Vertebrata"=24, 
                    "Chordata"=23, 
                    "Deuterostoma"=22,
                    "Bilateria"=21, 
                    "Cyclorrapha"=39,
                    "Diptera"=38,
                    "Panorpidae"=37, 
                    "Oligoneoptera"=36,
                    "Holometabola"=35,
                    "Neoptera"=34,
                    "Insecta"=33,
                    "Arthropoda"=32,
                    "Protostoma"=31)

nodes_positions_ancestors_dict = hashmap(as.character(as.vector(unname(nodes_positions))), names(nodes_positions))

#Subset original tree to the two branches
deuterostome_tree = tree_subset(my_phylo_tree, 22, levels_back = 0)
protostome_tree = tree_subset(my_phylo_tree, 31, levels_back = 0)
```

<!-- figS10: general OU trends -->
```{r plot_expression_distances_grouped_by_gains_fitted_model_BH_rel_expr, echo=FALSE, message=FALSE, warning=FALSE, dependson=c("setup", "functions"), fig.height=11, fig.width=7}
###########################################################
####### VARIABLES #########################################
###########################################################

species_distances_dict = hashmap(as.vector(all_species), rep(seq(0,9),2))

###########################################################
####### INPUTS ############################################
###########################################################

######## Upload extant species relative expressions
extant_species_relative_expr_file = "/users/mirimia/fmantica/projects/bilaterian_GE/data/donate_inferences/species_QN_5_TPM_v6/All_version2/relative_expr_best_hits/Bilateria_conserved_orthogroups-BH_OGs-relative_expr.tab"
extant_species_expr_df = read.delim(extant_species_relative_expr_file, header=TRUE)
extant_species_expr_long_df = melt(extant_species_expr_df, id.vars=c("OG_ID", "Species"), variable.name="Tissue", value.name="Expr_prop")

######## Add squared distance from human in the Deuterostoma branch and for fly in the Protostoma branch
extant_species_expr_long_df$Branch = ifelse(extant_species_expr_long_df$Species %in% Deuterostoma, "Deuterostoma", "Protostoma")

extant_species_squared_mean_distance_df = extant_species_expr_long_df %>%
  #filter(Tissue != "Adipose") %>%
  group_by(OG_ID, Branch, Tissue) %>%
  mutate(ref_species_value = Expr_prop[Species == "Hs2" | Species == "Dme"]) %>%
  mutate(dist_from_absolute_delta = abs(ref_species_value - Expr_prop)) %>%
  mutate(dist_from_squared_delta = (ref_species_value - Expr_prop)^2) %>%
  ungroup() %>%
  group_by(Branch, Species, Tissue) %>%
  summarise(mean_dist_from_absolute_delta = mean(dist_from_absolute_delta, na.rm=TRUE), 
            mean_dist_from_squared_delta = mean(dist_from_squared_delta, na.rm=TRUE))

####### Add distance from ancestor
extant_species_squared_mean_distance_df$ancestor_distance = species_distances_dict$find(extant_species_squared_mean_distance_df$Species)
extant_species_squared_mean_distance_df$Tissue = factor(extant_species_squared_mean_distance_df$Tissue, levels=all_tissues)

####### absolute delta
distance_from_absolute_delta_plot = ggplot(data=extant_species_squared_mean_distance_df, aes(x=ancestor_distance, y=mean_dist_from_absolute_delta, color=Tissue)) +
  geom_point(alpha=0.5) +
  geom_smooth(method="nls",
              formula = "y ~ a*x^k", 
              method.args = list(start=c(a=0.1,k=1)),
              se=FALSE,
              color="black",
              size=0.5) +
  scale_color_manual(values=my_color_vector) +
  scale_x_continuous(breaks=seq(0,9)) +
  scale_y_continuous(breaks=number_ticks(6)) +
  theme_bw() +
  theme(legend.position="bottom",
        plot.title=element_text(color="black", hjust=0.5, face="bold"),
        axis.text = element_text(color="black"),
        axis.title = element_text(color="black")) +
  ggtitle(paste0("Mean dist from absolute delta")) +
    xlab("Ancestor distance") +
  ylab("Mean distance") +
  facet_nested_wrap(~Tissue+Branch, ncol=4)

print(distance_from_absolute_delta_plot)

####### squared delta
distance_from_squared_delta_plot = ggplot(data=extant_species_squared_mean_distance_df, aes(x=ancestor_distance, y=mean_dist_from_squared_delta, color=Tissue)) +
  geom_point(alpha=0.5) +
  geom_smooth(method="nls",
              formula = "y ~ a*x^k", 
              method.args = list(start=c(a=0.1,k=1)),
              se=FALSE,
              color="black",
              size=0.5) +
  scale_color_manual(values=my_color_vector) +
  scale_x_continuous(breaks=seq(0,9)) +
  scale_y_continuous(breaks=number_ticks(6)) +
  theme_bw() +
  theme(legend.position="bottom",
        plot.title=element_text(color="black", hjust=0.5, face="bold"),
        axis.text = element_text(color="black"),
        axis.title = element_text(color="black")) +
  ggtitle(paste0("Mean dist from squared delta")) +
    xlab("Ancestor distance") +
  ylab("Mean distance") +
  facet_nested_wrap(~Tissue+Branch, ncol=4)

print(distance_from_squared_delta_plot)

#save to pdf
pdf("/users/mirimia/fmantica/projects/bilaterian_GE/data/phytools_inferences/OUwie_approach/General_OU_model_fitting-expr_prop-absolute_delta.pdf", height=11, width=7)
print(distance_from_absolute_delta_plot)
dev.off()
```

<!-- figS11: compare fitting of OU models -->
<!-- All TS gains -->
```{r TS_gains, echo=FALSE, message=FALSE, warning=FALSE, dependson="setup"}
####### Run compare models for the TS gains
all_tissues_gains_model_fitting_df = vector()
all_tissues_gains_expr_prop_averages_df = vector()
all_tissues_gains_info_df = vector()

for (query_tissue in all_tissues[all_tissues != "Adipose"]) {
  #### Define files
  expr_prop_file = paste0("/users/mirimia/fmantica/projects/bilaterian_GE/data/donate_inferences/species_QN_5_TPM_v6/All_version2/relative_expr/Bilateria_conserved_orthogroups-", 
                          query_tissue, "_specific-OGs-relative_expr.tab")
  inferred_gains_file = paste0(ts_gains_losses_dir, "Bilateria_conserved_orthogroups-All_genes-", query_tissue, "_inferred_gains.tab")
  inferred_losses_file = paste0(ts_gains_losses_dir, "Bilateria_conserved_orthogroups-All_genes-", query_tissue, "_inferred_losses.tab")
  expr_cutoff_info_file = paste0("/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_losses/species_QN_5_TPM_v6/All_version2/Bilateria_conserved_orthogroups-All_genes-",
                                 query_tissue, "_specific_OGs.tab")
  
  ### Generate inputs to compare OU models (single optimum vs double optima)
  TS_gains_compare_OU_models_input = get_TS_gains_compare_OU_models_inputs(query_tissue, expr_prop_file, inferred_gains_file, inferred_losses_file, expr_cutoff_info_file)
  
  all_OGs_model_fitting_input_df = TS_gains_compare_OU_models_input[[1]]
  expr_cutoff_info_df = TS_gains_compare_OU_models_input[[2]]
  inferred_losses_df = TS_gains_compare_OU_models_input[[3]]
  
  ### Compare models
  compare_models_output = compare_OU_models(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df)
  
  all_tissues_gains_model_fitting_df = rbind(all_tissues_gains_model_fitting_df, compare_models_output[[1]])
  all_tissues_gains_expr_prop_averages_df = rbind(all_tissues_gains_expr_prop_averages_df, compare_models_output[[2]])
  all_tissues_gains_info_df = rbind(all_tissues_gains_info_df, compare_models_output[[3]])
}

all_tissues_gains_expr_prop_averages_WIDE_df = all_tissues_gains_expr_prop_averages_df %>%
  pivot_wider(names_from = "TS_info", values_from = "Expr_prop_avg") %>%
  mutate(TS_vs_NO_TS_delta = TS - NO_TS)

all_tissues_gains_model_fitting_with_averages_df = all_tissues_gains_model_fitting_df %>%
  left_join(all_tissues_gains_expr_prop_averages_WIDE_df, by=c("OG_ID", "Branch", "Query_tissue"))

all_tissues_gains_model_fitting_with_info_df = all_tissues_gains_model_fitting_df %>%
  select(c("OG_ID", "Branch", "Query_tissue", "TS_gain", "OU1_aicW", "OUM_aicW", "Better_fit")) %>%
  right_join(all_tissues_gains_info_df, by=c("OG_ID", "Branch", "Query_tissue"))

#### Save to file
write.table(all_tissues_gains_model_fitting_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_gains_model_fitting.tab",
            sep="\t", quote=FALSE, row.names=FALSE)

write.table(all_tissues_gains_model_fitting_with_averages_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_gains_model_fitting_with_averages.tab",
            sep="\t", quote=FALSE, row.names=FALSE)

write.table(all_tissues_gains_model_fitting_with_info_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_gains_model_fitting_with_info.tab",
            sep="\t", quote=FALSE, row.names=FALSE)
```

<!-- Randomized best hits -->
```{r randomized_best_hits, echo=FALSE, message=FALSE, warning=FALSE, dependson="setup"}
####### It relies on the previous chunck being run

####### Run compare models for the TS gains
all_tissues_randomized_BH_model_fitting_df = vector()
all_tissues_randomized_BH_expr_prop_averages_df = vector()
all_tissues_randomized_BH_info_df = vector()

for (query_tissue in all_tissues[all_tissues != "Adipose"]) {
  #### Define files
  expr_prop_file = "/users/mirimia/fmantica/projects/bilaterian_GE/data/donate_inferences/species_QN_5_TPM_v6/All_version2/relative_expr_best_hits/Bilateria_conserved_orthogroups-BH_OGs-relative_expr.tab"
  inferred_gains_file = paste0(ts_gains_losses_dir, "Bilateria_conserved_orthogroups-All_genes-", query_tissue, "_inferred_gains.tab")
  inferred_losses_file = paste0(ts_gains_losses_dir, "Bilateria_conserved_orthogroups-All_genes-", query_tissue, "_inferred_losses.tab")
  expr_cutoff_info_file = "/users/mirimia/fmantica/projects/bilaterian_GE/data/donate_inferences/species_QN_5_TPM_v6/All_version2/relative_expr_best_hits/Bilateria_conserved_orthogroups-BH_OGs-Expr_cutoffs.tab"
  
  ### Define number of random OGs to consider for each set
  evaluated_TS_gains_df = all_tissues_gains_model_fitting_df %>%
    filter(Query_tissue == query_tissue) %>%
    select(OG_ID, Branch)
  
  ### Generate inputs to compare OU models (single optimum vs double optima)
  randomized_BH_compare_OU_models_input = get_randomized_BH_compare_OU_models_inputs(query_tissue, expr_prop_file, inferred_gains_file, inferred_losses_file, expr_cutoff_info_file, evaluated_TS_gains_df)
  
  all_OGs_model_fitting_input_df = randomized_BH_compare_OU_models_input[[1]]
  expr_cutoff_info_df = randomized_BH_compare_OU_models_input[[2]]
  inferred_losses_df = randomized_BH_compare_OU_models_input[[3]]
  
  ### Compare models
  compare_models_output = compare_OU_models(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df)
  
  all_tissues_randomized_BH_model_fitting_df = rbind(all_tissues_randomized_BH_model_fitting_df, compare_models_output[[1]])
  all_tissues_randomized_BH_expr_prop_averages_df = rbind(all_tissues_randomized_BH_expr_prop_averages_df, compare_models_output[[2]])
  all_tissues_randomized_BH_info_df = rbind(all_tissues_randomized_BH_info_df, compare_models_output[[3]])
}

all_tissues_randomized_BH_expr_prop_averages_WIDE_df = all_tissues_randomized_BH_expr_prop_averages_df %>%
  pivot_wider(names_from = "TS_info", values_from = "Expr_prop_avg") %>%
  mutate(TS_vs_NO_TS_delta = TS - NO_TS)

all_tissues_randomized_BH_model_fitting_with_averages_df = all_tissues_randomized_BH_model_fitting_df %>%
  left_join(all_tissues_randomized_BH_expr_prop_averages_WIDE_df, by=c("OG_ID", "Branch", "Query_tissue"))

all_tissues_randomized_BH_model_fitting_with_info_df = all_tissues_randomized_BH_model_fitting_df %>%
  select(c("OG_ID", "Branch", "Query_tissue", "TS_gain", "OU1_aicW", "OUM_aicW", "Better_fit")) %>%
  right_join(all_tissues_randomized_BH_info_df, by=c("OG_ID", "Branch", "Query_tissue"))

#### Save to file
write.table(all_tissues_randomized_BH_model_fitting_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_randomized_BH_model_fitting.tab",
            sep="\t", quote=FALSE, row.names=FALSE)

write.table(all_tissues_randomized_BH_model_fitting_with_averages_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_randomized_BH_model_fitting_with_averages.tab",
            sep="\t", quote=FALSE, row.names=FALSE)

write.table(all_tissues_randomized_BH_model_fitting_with_info_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_randomized_BH_model_fitting_with_info.tab",
            sep="\t", quote=FALSE, row.names=FALSE)
```

<!-- Randomized best hits noTS -->
```{r randomized_best_hits_noTS, echo=FALSE, message=FALSE, warning=FALSE, dependson="setup"}
####### It relies on the TS_gains chunck being run

####### Run compare models for the TS gains
all_tissues_randomized_BH_noTS_model_fitting_df = vector()
all_tissues_randomized_BH_noTS_expr_prop_averages_df = vector()
all_tissues_randomized_BH_noTS_info_df = vector()

for (query_tissue in all_tissues[!(all_tissues %in% c("Neural", "Adipose"))]) {
  print(query_tissue)
  #### Define files
  expr_prop_file = "/users/mirimia/fmantica/projects/bilaterian_GE/data/donate_inferences/species_QN_5_TPM_v6/All_version2/relative_expr_best_hits/Bilateria_conserved_orthogroups-BH_OGs-relative_expr.tab"
  inferred_gains_file = paste0(ts_gains_losses_dir, "Bilateria_conserved_orthogroups-All_genes-", query_tissue, "_inferred_gains.tab")
  inferred_losses_file = paste0(ts_gains_losses_dir, "Bilateria_conserved_orthogroups-All_genes-", query_tissue, "_inferred_losses.tab")
  expr_cutoff_info_file = "/users/mirimia/fmantica/projects/bilaterian_GE/data/donate_inferences/species_QN_5_TPM_v6/All_version2/relative_expr_best_hits/Bilateria_conserved_orthogroups-BH_OGs-Expr_cutoffs.tab"
  non_TS_prone_file = "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_losses/species_QN_5_TPM_v4/All_version2/non-TS_prone/non-TS_prone-OG_IDs-GO_input.txt"
  
  ### Define number of random OGs to consider for each set
  evaluated_TS_gains_df = all_tissues_gains_model_fitting_df %>%
    filter(Query_tissue == query_tissue) %>%
    select(OG_ID, Branch)
  
  ### Generate inputs to compare OU models (single optimum vs double optima)
  randomized_BH_noTS_compare_OU_models_input = get_randomized_BH_noTS_compare_OU_models_inputs(query_tissue, expr_prop_file, inferred_gains_file, inferred_losses_file, 
                                                                                               expr_cutoff_info_file, evaluated_TS_gains_df, non_TS_prone_file)
  
  all_OGs_model_fitting_input_df = randomized_BH_noTS_compare_OU_models_input[[1]]
  expr_cutoff_info_df = randomized_BH_noTS_compare_OU_models_input[[2]]
  inferred_losses_df = randomized_BH_noTS_compare_OU_models_input[[3]]
  
  ### Compare models
  compare_models_output = compare_OU_models(all_OGs_model_fitting_input_df, expr_cutoff_info_df, inferred_losses_df)
  
  all_tissues_randomized_BH_noTS_model_fitting_df = rbind(all_tissues_randomized_BH_noTS_model_fitting_df, compare_models_output[[1]])
  all_tissues_randomized_BH_noTS_expr_prop_averages_df = rbind(all_tissues_randomized_BH_noTS_expr_prop_averages_df, compare_models_output[[2]])
  all_tissues_randomized_BH_noTS_info_df = rbind(all_tissues_randomized_BH_noTS_info_df, compare_models_output[[3]])
}

all_tissues_randomized_BH_noTS_expr_prop_averages_WIDE_df = all_tissues_randomized_BH_noTS_expr_prop_averages_df %>%
  pivot_wider(names_from = "TS_info", values_from = "Expr_prop_avg") %>%
  mutate(TS_vs_NO_TS_delta = TS - NO_TS)

all_tissues_randomized_BH_noTS_model_fitting_with_averages_df = all_tissues_randomized_BH_noTS_model_fitting_df %>%
  left_join(all_tissues_randomized_BH_noTS_expr_prop_averages_WIDE_df, by=c("OG_ID", "Branch", "Query_tissue"))

all_tissues_randomized_BH_noTS_model_fitting_with_info_df = all_tissues_randomized_BH_noTS_model_fitting_df %>%
  select(c("OG_ID", "Branch", "Query_tissue", "TS_gain", "OU1_aicW", "OUM_aicW", "Better_fit")) %>%
  right_join(all_tissues_randomized_BH_noTS_info_df, by=c("OG_ID", "Branch", "Query_tissue"))

#### Save to file
write.table(all_tissues_randomized_BH_noTS_model_fitting_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_randomized_BH_noTS_model_fitting.tab",
            sep="\t", quote=FALSE, row.names=FALSE)

write.table(all_tissues_randomized_BH_noTS_model_fitting_with_averages_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_randomized_BH_noTS_model_fitting_with_averages.tab",
            sep="\t", quote=FALSE, row.names=FALSE)

write.table(all_tissues_randomized_BH_noTS_model_fitting_with_info_df,
            "/users/mirimia/fmantica/projects/bilaterian_GE/data/ts_gains_validation/OUwie_approach/species_QN_5_TPM_v6/OU1_vs_OUM_inputs/ALL/all_tissues_randomized_BH_noTS_model_fitting_with_info.tab",
            sep="\t", quote=FALSE, row.names=FALSE)
```

<!-- Compare results -->
```{r final_plots, warning=FALSE, echo=FALSE, message=FALSE, dependson="setup", fig.width=10, fig.height=12}
###### Build input for data composition
df1 = all_tissues_gains_model_fitting_df
df2 = all_tissues_randomized_BH_model_fitting_df
df3 = all_tissues_randomized_BH_noTS_model_fitting_df

df1$Group = rep("TS_gains", nrow(df1))
df2$Group = rep("BH", nrow(df2))
df3$Group = rep("BH_noTS", nrow(df3))

all_dfs = rbind(df1, df2, df3)
all_dfs$Group = factor(all_dfs$Group, levels=c("TS_gains", "BH", "BH_noTS"))
all_dfs$Query_tissue = factor(all_dfs$Query_tissue, levels=all_tissues)
all_dfs$OU1_aicW = round(all_dfs$OU1_aicW, 2)
all_dfs$OUM_aicW = round(all_dfs$OUM_aicW, 2)

all_dfs = all_dfs %>%
  mutate(Better_fit = ifelse(OU1_aicW == OUM_aicW, "No_optimum", Better_fit))

better_fit_plots = ggplot(data=all_dfs, aes(x=Group, fill=Better_fit)) +
  geom_bar(stat="count", position = "fill", alpha=0.8, color="white") +
  geom_text(stat="count", aes(label=..count..), position = position_fill(vjust=0.5), size=3) +
  scale_fill_manual(values = c("Single_optimum"="dimgray", "Multiple_optima"="coral3", "No_optimum"="antiquewhite3")) +
  theme_bw() +
  theme(#axis.text.x = element_text(color="black", angle=30, hjust = 1, vjust=1),
        axis.text = element_text(color="black"),
        axis.title.x = element_blank()) +
  guides(fill="none") +
  facet_wrap(~Query_tissue, ncol=2, dir="h")

#print(better_fit_plots)
separated_better_fit_plots = splitFacet(better_fit_plots)

###### Build input for higher and lower average expression prop between TS and non-TS species (Multiple Optima only)
averages_df1 = all_tissues_gains_model_fitting_with_averages_df
averages_df2 = all_tissues_randomized_BH_model_fitting_with_averages_df
averages_df3 = all_tissues_randomized_BH_noTS_model_fitting_with_averages_df

averages_df1$Group = rep("TS_gains", nrow(averages_df1))
averages_df2$Group = rep("BH", nrow(averages_df2))
averages_df3$Group = rep("BH_noTS", nrow(averages_df3))

all_averages_df = rbind(averages_df1, averages_df2, averages_df3)
all_averages_df$OU1_aicW = round(all_averages_df$OU1_aicW, 2)
all_averages_df$OUM_aicW = round(all_averages_df$OUM_aicW, 2)
all_averages_df = all_averages_df%>%
  mutate(Better_fit = ifelse(OU1_aicW == OUM_aicW, "No_optimum", Better_fit)) %>%
  filter(Better_fit=="Multiple_optima") %>%
  mutate(TS_prop_status = ifelse(TS_vs_NO_TS_delta > 0, "TS_greater", "TS_lower")) %>%
  mutate(TS_prop_status = ifelse(is.na(TS_prop_status), "TS_lower", TS_prop_status)) #temporary shit (until I fix the Protostoma)
  
all_averages_df$Group = factor(all_averages_df$Group, levels=c("TS_gains", "BH", "BH_noTS"))
all_averages_df$Query_tissue = factor(all_averages_df$Query_tissue, levels=all_tissues)

multiple_optima_TS_prop_status_plot = ggplot(data=all_averages_df, aes(x=Group, fill=TS_prop_status)) +
  geom_bar(stat="count", color="white", alpha=0.8, position=position_fill()) +
  geom_text(stat="count", aes(label=..count..), position = position_fill(vjust=0.5), size=3) +
  scale_fill_manual(values=c("TS_greater"="lightseagreen", "TS_lower"="lightslateblue")) +
  theme_bw() +
  theme(#axis.text.x = element_text(color="black", angle=30, hjust = 1, vjust=1),
        axis.text = element_text(color="black"),
        axis.title.x = element_blank()) +
  guides(fill="none") +
  facet_wrap(~Query_tissue, ncol=2, dir="h")

#print(multiple_optima_TS_prop_status_plot)
separated_multiple_optima_TS_prop_status_plot = splitFacet(multiple_optima_TS_prop_status_plot)

all_tissue_plots = list()
for (i in seq(1, 7)) {
  plot_title <- ggdraw() + draw_label(all_tissues[i], fontface='bold', size=10)
  single_tissue_plot = plot_grid(separated_better_fit_plots[[i]], separated_multiple_optima_TS_prop_status_plot[[i]], ncol=2, align="hv")
  single_tissue_titled_plot = plot_grid(plot_title, single_tissue_plot, ncol=1, rel_heights = c(0.08, 1))
  all_tissue_plots[[i]] =single_tissue_titled_plot
}

final_plots = plot_grid(plotlist = all_tissue_plots, ncol=2)
print(final_plots)

pdf("/users/mirimia/fmantica/projects/bilaterian_GE/data/phytools_inferences/OUwie_approach/all_TS_gains_comp-OUwie_approach-STRICT_and_LASSO.pdf", width = 10, height = 12)
print(final_plots)
dev.off()

###### Build input for ancestral composition in single optimum
# single_optimum_df = subset(all_dfs, Better_fit == "Single_optimum")
# single_optimum_df$TS_gain = factor(single_optimum_df$TS_gain, levels=c(all_ancestors_by_age, all_species))
# #Add species level
# single_optimum_df$Tree_level = all_ancestors_tree_positions_dict$find(single_optimum_df$TS_gain)
# single_optimum_df$Tree_level[single_optimum_df$TS_gain %in% all_species] = 1
# single_optimum_df$Tree_level = factor(single_optimum_df$Tree_level)
#   
# single_optimum_ancestor_plots = ggplot(data=single_optimum_df, aes(x=Group, fill=Tree_level)) +
#   geom_bar(stat="count", position=position_fill(), color="white", alpha=0.6) +
#   geom_text(stat="count", aes(label=..count..), position = position_fill(vjust=0.5)) +
#   scale_fill_viridis_d(direction=-1) +
#   theme_bw() +
#   theme(axis.text = element_text(color="black")) +
#   facet_wrap(~Query_tissue, ncol=2, dir="h")
# 
# print(single_optimum_ancestor_plots, ncol=2, byrow=TRUE)
# 
# ###### Build input for TS gain composition for the TS greater in the control groups
# TS_greater_multiple_optima_df = all_averages_df %>%
#   filter(TS_prop_status=="TS_greater")
# 
# TS_greater_multiple_optima_df$Tree_level = all_ancestors_tree_positions_dict$find(TS_greater_multiple_optima_df$TS_gain)
# TS_greater_multiple_optima_df$Tree_level[TS_greater_multiple_optima_df$TS_gain %in% all_species] = 1
# TS_greater_multiple_optima_df$Tree_level = factor(TS_greater_multiple_optima_df$Tree_level)
# 
# TS_greater_multiple_optima_TS_gains_prop_plot = ggplot(data=TS_greater_multiple_optima_df, aes(x=Group, fill=Tree_level)) +
#   geom_bar(stat="count", position=position_fill(), color="white", alpha=0.6) +
#   geom_text(stat="count", aes(label=..count..), position = position_fill(vjust=0.5)) +
#   scale_fill_viridis_d(direction=-1) +
#   theme_bw() +
#   theme(axis.text = element_text(color="black")) +
#   facet_wrap(~Query_tissue, ncol=2, dir="h")
# 
# print(TS_greater_multiple_optima_TS_gains_prop_plot)

###close pdf
#dev.off()
```

```{r statistics, warning=FALSE, echo=FALSE, message=FALSE, dependson="setup"}
### rate of false negatives
all_dfs %>% group_by(Query_tissue, Group, Better_fit) %>% summarize(n = n()) %>% mutate(freq = n / sum(n)) %>% filter(Group=="TS_gains", Better_fit=="Single_optimum") %>% ungroup() %>% pull(freq) %>% mean()

### rate of false positives
general_counts_df = all_dfs %>% select(Query_tissue, Group) %>% group_by(Query_tissue, Group) %>% summarise(tot = n())
TS_greater_counts_df = all_averages_df %>% group_by(Query_tissue, TS_prop_status, Group) %>% summarize(freq = n()) %>% filter(TS_prop_status=="TS_greater") %>% ungroup() %>% select(Query_tissue, Group, freq)
TS_greater_stats_df = TS_greater_counts_df %>% inner_join(general_counts_df, by=c("Query_tissue", "Group")) %>% filter(Group!="TS_gains") %>% mutate(false_positives = freq/tot)
```