---
title: "figS14"
output: html_document
---

```{r setup, include=FALSE}
#set Knitr option
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

#upload libraries
library(ggplot2)
library(mixOmics)
library(hashmap)
library(reshape2)
library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(viridis)
library(gridExtra)
library(egg)
library(plotly)
library(ggrepel)
library(pathview)
library(gage)
library(ggtree)
library(ape)
library(purrr)
library(ggh4x)
library(ggpubr)
library(forcats)
library(ggridges)
library(ggalluvial)
library(data.table)

#set directories
home="/Users/federica/mnt/"
ts_call_dir=paste0(home, "projects/bilaterian_GE/data/ts_call/")
splsda_dir = paste0(home, "projects/bilaterian_GE/data/splsda_analysis/")
tau_dir = paste0(home, "projects/bilaterian_GE/data/ts_call/species_QN_5_TPM_taus/")
original_tau_dir = paste0(home, "projects/bilaterian_GE/data/ts_call/taus/")
gene_sets_dir=paste0(home, "projects/bilaterian_GE/data/gene_sets/")
randomization_dir=paste0(home, "projects/bilaterian_GE/data/ts_call/QN_randomizations/")
evo_distances_dir = paste0(home, "projects/bilaterian_GE/data/evo_distances/")
ts_gains_losses_dir = paste0(home, "projects/bilaterian_GE/data/ts_gains_losses/species_QN_5_TPM_v4/")
GO_transfers_dir = paste0(home, "projects/bilaterian_GE/data/GO_transfers/")
intergenic_dist_dir = paste0(home, "projects/bilaterian_GE/data/ts_intergenic_regions/")
# #tissue_expr_dir=paste0(home, "projects/bilaterian_GE/data/preprocessing/average_expr_by_tissue/")
# pca_dir=paste0(home, "projects/bilaterian_GE/data/pca_analysis_all_norms/")
# metadata_dir=paste0(home, "projects/bilaterian_GE/data/samples_metadata/")
# splsda_dir= paste0(home, "projects/bilaterian_GE/data/splsda_analysis/")
# diff_expr_dir = paste0(home, "projects/bilaterian_GE/data/differential_expression/")
# general_patterns_dir = paste0(home, "projects/bilaterian_GE/data/vertebrates_vs_insects_general_patterns/")
# branches_length_dir = paste0(home, "projects/bilaterian_GE/data/branches_length_analysis/")

#set variables
my_version = "All_version2"
my_category = "STRICT"
my_evo_type = "conserved"
clades = c("Vertebrata", "Insecta", "Bilateria")
clades_PCA = c("Vertebrata", "Insecta", "Bilateria")
options("scipen"=100, "digits"=4)

all_species = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi")
ordered_species_tree = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", rev(c("Dme", "Eba", "Aae", "Bmo", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi")))
ordered_species = all_species
Bilateria = all_species
Vertebrata = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi")
Insecta = c("Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi")
Outgroups = c("Bla", "Sp2", "Sma", "Obi")
all_tissues=c("Adipose", "DigestiveTract", "Kidney", "Epithelial", "Muscle", "Neural", "Ovary", "Testis")
ordered_tissues = c("Neural", "Testis", "Ovary", "Muscle", "Kidney", "Epithelial", "DigestiveTract", "Adipose")

#set aestetics vectors
my_color_vector = c("Neural"="mediumblue", "Testis"="violet", "Ovary"="darkorchid", "Muscle"="springgreen3", 
                    "Kidney"="gold", "Epithelial"="steelblue1", "DigestiveTract"="chocolate1", "Adipose"="firebrick1")
my_shapes_vector = c("Hs2"=0, "Mm2"=1, "Bt2"=2, "Mdo"=3, "Gga"=4, "Xtr"=5, "Dre"=6, "Cmi"=7, "Bla"=9, "Sp2"=8, 
                     "Dme"=15, "Eba"=18, "Aae"= 23, "BmA"=25, "Tca"=17, "Bge"=10, "Ame"=16, "Cdi"=13, "Sma"=14, "Obi"=11)
my_alpha_vector=c("Hs2"=1, "Mm2"=1, "Bt2"=1, "Mdo"=1, "Gga"=1, "Xtr"=1, "Dre"=1, "Cmi"=1, "Bla"=0.5, "Sp2"=0.5, "Sma"=0.5, "Ame"=0.5, "Dme"=0.5, "Cdi"=0.5, "Obi"=0.5, "Bge"=0.5, "BmA"=0.5, "Tca"=0.5)
my_sets_color = c("Vertebrata"= "mediumorchid", "Deuterostoma"="olivedrab3", "Insecta"="tan3", "Protostoma"="yellow", "Bilateria"="firebrick1", "Outgroups"="dimgray")
my_species_colors=c("Hs2"="#00BFFF", "Mm2"="#159DFF", "Bt2"="#1873CD", "Mdo"="#174B8B", "Gga"="#3F3F8B", "Xtr"="#64398B", "Dre"="#82359D", "Cmi"="#9932CC", "Bla"="#2E8B57", "Sp2"="#96B12B", "Obi"="#FFFF00", "Sma"="#FFCC33", "Cdi"="goldenrod", "Bge"="burlywood2", "Ame"="#FF9966", "Tca"="#FF6600", "Bmo"="#CC6600", "Aae"="#993300", "Eba"="firebrick3", "Dme"="red")
my_copy_status_colors = c("single_copy_ortholog"="gray18", "duplicated"="gray76")
my_branch_colors = c("Deuterostoma"="olivedrab3", "Protostoma"="tan3", "Bilateria"="firebrick1")
my_ancestral_colors = c("Ancestral"="dimgray", "Species_specific"="coral3")

#Create named vector with PC and corresponding tissue
PC_tissue_named_vector = c("1"="Neural", "2"="Testis", "3"="Ovary", 
                          "4"="Muscle", "5"="Kidney", "6"="Epithelial", 
                          "7"="DigestiveTract", "8"="Adipose")
paletteLength = 75
palette_brewer = colorRampPalette(rev(brewer.pal(11, "RdBu")))(paletteLength)

multi_tissues_vector = c(ordered_tissues, "MultiTS")
multi_tissues_color_vector = c(my_color_vector, "MultiTS"="black")


####### Variables neeeded to plot the tree
Bilateria = all_species
Euarchontoglires = c("Hs2", "Mm2")
Eutheria = c(Euarchontoglires, "Bt2")
Mammalia = c(Eutheria, "Mdo")
Amniota = c(Mammalia, "Gga")
Tetrapoda = c(Amniota, "Xtr")
Euteleostomi = c(Tetrapoda, "Dre")
Vertebrata = c(Euteleostomi, "Cmi")
Chordata = c(Vertebrata, "Bla")
Deuterostoma = c(Chordata, "Sp2")
Cyclorrapha = c("Dme", "Eba")
Diptera = c(Cyclorrapha, "Aae")
Panorpidae = c(Diptera, "Bmo")
Oligoneoptera = c(Panorpidae, "Tca")
Holometabola = c(Oligoneoptera, "Ame")
Neoptera = c(Holometabola, "Bge")
Insecta = c(Neoptera, "Cdi")
Arthropoda = c(Insecta, "Sma")
Protostoma = c(Arthropoda, "Obi")

all_ancestors = c("Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma",
              "Bilateria", "Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma")

all_ancestors_colors = c("Euarchontoglires"="#159DFF",
                         "Eutheria" = "#1873CD",
                         "Mammalia" = "#174B8B",
                         "Amniota" = "#3F3F8B",  
                         "Tetrapoda" =  "#64398B",
                         "Euteleostomi" = "#82359D",
                         "Vertebrata" = "#9932CC",
                         "Chordata" = "#2E8B57",
                         "Deuterostoma" = "#96B12B",
                         "Cyclorrapha" = "firebrick3",
                         "Diptera" = "#993300",
                         "Panorpidae" = "#CC6600",
                         "Oligoneoptera" = "#FF6600", 
                         "Holometabola" = "#FF9966",
                         "Neoptera" = "burlywood2",
                         "Insecta" = "goldenrod",
                         "Arthropoda" = "#FFCC33",
                         "Protostoma" = "#FFFF00",
                         "species\nspecific" = "gray71")

clade_species = c("Euarchontoglires" = list(Euarchontoglires),
                  "Eutheria" = list(Eutheria),
                  "Mammalia" = list(Mammalia),
                  "Amniota" = list(Amniota),
                  "Tetrapoda" = list(Tetrapoda),
                  "Euteleostomi" = list(Euteleostomi),
                  "Vertebrata" = list(Vertebrata),
                  "Chordata" = list(Chordata),
                  "Deuterostoma" = list(Deuterostoma),
                  "Cyclorrapha" = list(Cyclorrapha),
                  "Diptera" = list(Diptera),
                  "Panorpidae" = list(Panorpidae),
                  "Oligoneoptera" = list(Oligoneoptera),
                  "Holometabola" = list(Holometabola),
                  "Neoptera" = list(Neoptera),
                  "Insecta" = list(Insecta),
                  "Arthropoda" = list(Arthropoda),
                  "Protostoma" = list(Protostoma),
                  "Bilateria" = list(Bilateria),
                  "Hs2" = "Hs2", "Mm2" = "Mm2", "Bt2" = "Bt2", "Mdo" = "Mdo", "Gga" = "Gga", "Xtr" = "Xtr", "Dre" = "Dre", "Cmi" = "Cmi",
                  "Bla" = "Bla", "Sp2" = "Sp2", "Sma" = "Sma", "Obi" = "Obi",
                  "Dme" = "Dme", "Eba" = "Eba", "Aae" = "Aae", "Bmo" = "Bmo", "Tca" = "Tca", "Ame" = "Ame", "Bge" = "Bge", "Cdi" = "Cdi")


node_x_position = c("Hs2"=1, "Euarchontoglires"=1.5, "Mm2"=2, "Eutheria"=2, "Bt2"=3, "Mammalia"=2.5,
                    "Mdo"=4, "Amniota"=3, "Gga"=5, "Tetrapoda"=3.5, "Xtr"=6, "Euteleostomi"=4,
                    "Dre"=7, "Vertebrata"=4.5, "Cmi"=8, "Chordata"=5, "Bla"=9, "Deuterostoma"=5.5, "Sp2"=10,
                    "Bilateria" = 11,
                    "Dme"=21, "Cyclorrapha"=20.5, "Eba"=20, "Diptera"=20, "Aae"=19, "Panorpidae"=19.5,
                    "Bmo"=18, "Oligoneoptera"=19, "Tca"=17, "Holometabola"=18.5, "Ame"=16, "Neoptera"=18,
                    "Bge"=15, "Insecta"=17.5, "Cdi"=14, "Arthropoda"=17, "Sma"=13, "Protostoma"=16.5, "Obi"=12)

node_y_position = c("Hs2"=1, "Euarchontoglires"=2, "Mm2"=1, "Eutheria"=3, "Bt2"=1, "Mammalia"=4,
                    "Mdo"=1, "Amniota"=5, "Gga"=1, "Tetrapoda"=6, "Xtr"=1, "Euteleostomi"=7,
                    "Dre"=1, "Vertebrata"=8, "Cmi"=1, "Chordata"=9, "Bla"=1, "Deuterostoma"=10, "Sp2"=1,
                    "Bilateria" = 11,
                    "Dme"=1, "Cyclorrapha"=2, "Eba"=1, "Diptera"=3, "Aae"=1, "Panorpidae"=4,
                    "Bmo"=1, "Oligoneoptera"=5, "Tca"=1, "Holometabola"=6, "Ame"=1, "Neoptera"=7,
                    "Bge"=1, "Insecta"=8, "Cdi"=1, "Arthropoda"=9, "Sma"=1, "Protostoma"=10, "Obi"=1)

node_x_labels = c("1.0"="Hs2", "1.5"="", "2.0"="Mm2", "2.5"="", "3.0"="Bt2", "3.5"="", "4.0"="Mdo", "4.5"="", "5.0"="Gga", "5.5"="",
                  "6.0"="Xtr", "7.0"="Dre", "8.0"="Cmi", "9.0"="Bla", "10.0"="Sp2",
                   "11.0"="",
                   "12.0"="Obi", "13.0"="Sma", "14.0"="Cdi", "15.0"="Bge", "16.0"="Ame", "16.5"="", "17.0"="Tca", "17.5"="", "18.0"="Bmo",
                  "18.5"="", "19.0"="Aae", "19.5"="", "20.0"="Eba", "20.5"="", "21.0"="Dme")

multi_tissues_vector = c(ordered_tissues, "MultiTS")
multi_tissues_color_vector = c(my_color_vector, "MultiTS"="black")

deuterostoma_y_labels = c("Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma", "Bilateria")
protostoma_y_labels = c("Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma", "Bilateria")


####### Get sub-ancestors
sub_Euarchontoglires = c("Hs2","Mm2")
sub_Eutheria = c("Euarchontoglires")
sub_Mammalia = c(sub_Eutheria, "Eutheria")
sub_Amniota = c(sub_Mammalia, "Mammalia")
sub_Tetrapoda = c(sub_Amniota, "Amniota")
sub_Euteleostomi = c(sub_Tetrapoda, "Tetrapoda")
sub_Vertebrata = c(sub_Euteleostomi, "Euteleostomi")
sub_Chordata = c(sub_Vertebrata, "Vertebrata")
sub_Deuterostoma = c(sub_Chordata, "Chordata")
sub_Cyclorrapha = c("Dme","Eba")
sub_Diptera = c(sub_Cyclorrapha, "Cyclorrapha")
sub_Panorpidae = c(sub_Diptera, "Diptera")
sub_Oligoneoptera = c(sub_Panorpidae, "Panorpidae")
sub_Holometabola = c(sub_Oligoneoptera, "Oligoneoptera")
sub_Neoptera = c(sub_Holometabola, "Holometabola")
sub_Insecta = c(sub_Neoptera, "Neoptera")
sub_Arthropoda = c(sub_Insecta, "Insecta")
sub_Protostoma = c(sub_Arthropoda, "Arthropoda")
sub_Bilateria = c(sub_Deuterostoma, sub_Protostoma)
```

```{r functions, warning=FALSE, message=FALSE, echo=FALSE, dependson="setup"}
number_ticks <- function(n) {function(limits) pretty(limits, n)}

####################################
####################################

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

####################################
####################################

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

####################################
####################################

plot_ts_genes_stats = function(annotation_row_df, ordered_tissues) {
  my_extra_color_vector = c("Adipose"="firebrick1", "Neural"="mediumblue", "Muscle"="springgreen3", "Ovary"="darkorchid", "Kidney"="gold", "Testis"="violet", "DigestiveTract"="chocolate1", "Epithelial"="steelblue1", "no_tissue"="white")
  ordered_tissue_combs = rev(names(table(annotation_row_df$Tissue)[order(table(annotation_row_df$Tissue))]))
  #Modify input
  annotation_row_df$Tissue = factor(annotation_row_df$Tissue, levels=ordered_tissue_combs)
  TS_genes_number_plot = ggplot(data=annotation_row_df) +
    geom_bar(aes(x=Tissue), stat="count", fill="darkgray", color="darkgray", alpha=0.8) +
    theme_bw() +
    geom_text(stat="count", aes(x=Tissue, label=..count..), vjust=-1, size=3) + #add count on top of barplot
    ylab("Number of TS genes") +
    ggtitle("Number of TS genes by tissue") +
    theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks = element_blank(),
        title = element_text(size=12, color="black"),
        panel.background = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank()) +
    scale_y_continuous(breaks=number_ticks(15), 
                       limits = c(0, max(unname(table(annotation_row_df$Tissue)))+60))
  
  #Build input for UpSet-like kind of plot
  shared_tissues_df = data.frame(tissue_comb=unique(as.vector(annotation_row_df$Tissue)))
  for (i in seq(length(ordered_tissues))) {
    shared_tissues_df$tissue = as.vector(shared_tissues_df$tissue_comb)
    shared_tissues_df$tissue[grep(ordered_tissues[i], shared_tissues_df$tissue_comb)] = ordered_tissues[i]
    shared_tissues_df$tissue[grep(ordered_tissues[i], shared_tissues_df$tissue_comb, invert=TRUE)] = "no_tissue"
    colnames(shared_tissues_df)[ncol(shared_tissues_df)] = ordered_tissues[i]
  }
  
  shared_tissues_long_df = melt(shared_tissues_df, id.vars = "tissue_comb")
  shared_tissues_long_df$tissue_comb = factor(shared_tissues_long_df$tissue_comb, levels=ordered_tissue_combs)
  colnames(shared_tissues_long_df) = c("tissue_comb", "tissue", "status")
  shared_tissues_long_df$tissue = factor(shared_tissues_long_df$tissue, levels=rev(ordered_tissues))
  shared_tissues_long_df = subset(shared_tissues_long_df, status != "no_tissue")
  
  shared_tissues_plot = ggplot(data=shared_tissues_long_df, aes(x=tissue_comb, y=tissue, group=tissue_comb)) +
    geom_line() +
    geom_point(aes(x=tissue_comb, y=tissue, fill=status), color="black", shape=21, size=3) +
    scale_fill_manual(values=my_extra_color_vector) +
    theme_bw() +
    theme(axis.title.x = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_text(color="black", size=10),
        axis.text.x=element_blank(),
        panel.background = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        panel.border = element_blank()) +
    ylab("Tissues") +
    guides(fill=FALSE)
  
  final_plot = plot_grid(TS_genes_number_plot, shared_tissues_plot, align="v", rel_heights = c(1,0.6), ncol=1)
  return(final_plot)
}

####################################
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}


####################################
see_pathview <- function(..., save_image = FALSE)
{
  msg <- capture.output(pathview::pathview(...), type = "message")
  msg <- grep("image file", msg, value = T)
  filename <- sapply(strsplit(msg, " "), function(x) x[length(x)])
  img <- png::readPNG(filename)
  grid::grid.raster(img)
  if(!save_image) invisible(file.remove(filename))
}

#######################################
########## Tree function ##############
#######################################
tree_y <-  function(ggtree, data){
  if(!inherits(ggtree, "ggtree"))
    stop("not a ggtree object")
  left_join(dplyr::select(data, label), dplyr::select(ggtree$data, label, y)) %>%
    pull(y)
}

#This is just to see if I can actually paier a ggtree with a ggplot decently.
# overwrite the default expand for continuous scales
scale_y_tree <- function(expand=expand_scale(0, 0.6), ...){
    scale_y_continuous(expand=expand, ...)
}

# get the range of the ggtree y-axis data
tree_ylim <- function(ggtree){
  if(!inherits(ggtree, "ggtree"))
    stop("not a ggtree object")
  range(ggtree$data$y)
}

# plot data next to a ggtree aligned by shared labels
ggtreeplot <- function(ggtree, data = NULL, mapping = aes(), flip=FALSE,
     expand_limits=expand_scale(0,.6), ...){
  
  if(!inherits(ggtree, "ggtree"))
    stop("not a ggtree object")

  # match the tree limits
  limits <- tree_ylim(ggtree)
  limits[1] <- limits[1] + (limits[1] * expand_limits[1]) - expand_limits[2]
  limits[2] <- limits[2] + (limits[2] * expand_limits[3]) + expand_limits[4]
  
  if(flip){
    mapping <- modifyList(aes_(x=~x), mapping)
    data <- mutate(data, x=tree_y(ggtree, data))
    gg <- ggplot(data=data, mapping = mapping, ...) +
      scale_x_continuous(limits=limits, expand=c(0,0))
  }else{
    mapping <- modifyList(aes_(y=~y), mapping)
    data <- mutate(data, y=tree_y(ggtree, data))
    gg <- ggplot(data=data, mapping = mapping, ...) +
      scale_y_continuous(limits=limits, expand=c(0,0))
  }
  gg
}

#######################################
########## Randomizations #############
#######################################

get_random_labels_stats = function(ts_long_df) {
  final_mat = vector()
  current_species = vector()
  for (index in seq(1, length(ordered_species))) {
    new_species = ordered_species[index]
    current_species = c(current_species, new_species)
    current_OGs_df = subset(ts_long_df, Species %in% current_species) #Select the orthogroups containing at least one of the species
    current_OGs_num = length(unique(as.vector(current_OGs_df$OG_ID)))
    TS_OGs_df = subset(current_OGs_df, TS_labels == "TS")
    TS_OGs_num = length(unique(as.vector(TS_OGs_df$OG_ID)))
    TS_OGs_proportion = TS_OGs_num/current_OGs_num
    final_mat = rbind(final_mat, c(length(current_species), TS_OGs_num, TS_OGs_proportion, new_species))
  }
  colnames(final_mat) = c("Species_number", "TS_OG_number", "TS_OG_proportion", "new_species")
  final_df = as.data.frame(final_mat)
  final_df$TS_OG_number = as.numeric(as.vector(final_df$TS_OG_number))
  final_df$TS_OG_proportion = as.numeric(as.vector(final_df$TS_OG_proportion))
  final_df$Species_number = as.numeric(as.vector(final_df$Species_number))
  final_df$new_species = as.character(final_df$new_species)
  return(final_df)
}

#######################################
######## TS gains and losses ##########
#######################################

plot_tree_structure = function(node_x_position, node_y_position, node_x_labels) {
  ancestors = c("Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma",
                "Bilateria", "Hs2", "Dme",
                "Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma")
  deuterostoma_side = c("Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma")
  protostoma_side = c("Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma")
  
  node_y_values = unique(as.numeric(unname(node_y_position))[as.numeric(unname(node_y_position)) != 1])
  deuterostoma_y_labels = c("Euarchontoglires", "Eutheria", "Mammalia", "Amniota", "Tetrapoda", "Euteleostomi", "Vertebrata", "Chordata", "Deuterostoma", "")
  protostoma_y_labels = c("Cyclorrapha", "Diptera", "Panorpidae", "Oligoneoptera", "Holometabola", "Neoptera", "Insecta", "Arthropoda", "Protostoma", "")
  
  node_x_position_dict = hashmap(names(node_x_position), unname(node_x_position))
  node_y_position_dict = hashmap(names(node_y_position), unname(node_y_position))
  
  tree_input_df = data.frame(Node=c(all_species, all_ancestors))
  #Add coordinates for each node
  tree_input_df$Node_x_position = node_x_position_dict$find(tree_input_df$Node)
  tree_input_df$Node_y_position = node_y_position_dict$find(tree_input_df$Node)
  #Add groups so that lines between all ancestors and all pairs will be drawn.
  tree_input_df$ancestor_state = rep("none", nrow(tree_input_df))
  tree_input_df$ancestor_state[tree_input_df$Node %in% ancestors] = "ancestor"
  #Add side of the tree (Deuterostoma or Protostoma)
  
  #This is long and manual
  tree_input_df$node_state = rep("none", nrow(tree_input_df))
  tree_input_df$node_state[tree_input_df$Node %in% c("Mm2", "Euarchontoglires")] = "Euarchontoglires"
  tree_input_df$node_state[tree_input_df$Node %in% c("Bt2", "Eutheria")] = "Eutheria"
  tree_input_df$node_state[tree_input_df$Node %in% c("Mdo", "Mammalia")] = "Mammalia"
  tree_input_df$node_state[tree_input_df$Node %in% c("Gga", "Amniota")] = "Amniota"
  tree_input_df$node_state[tree_input_df$Node %in% c("Xtr", "Tetrapoda")] = "Tetrapoda"
  tree_input_df$node_state[tree_input_df$Node %in% c("Dre", "Euteleostomi")] = "Euteleostomi"
  tree_input_df$node_state[tree_input_df$Node %in% c("Cmi", "Vertebrata")] = "Vertebrata"
  tree_input_df$node_state[tree_input_df$Node %in% c("Bla", "Chordata")] = "Chordata"
  tree_input_df$node_state[tree_input_df$Node %in% c("Sp2", "Deuterostoma")] = "Deuterostoma"
  
  tree_input_df$node_state[tree_input_df$Node %in% c("Eba", "Cyclorrapha")] = "Cyclorrapha"
  tree_input_df$node_state[tree_input_df$Node %in% c("Aae", "Diptera")] = "Diptera"
  tree_input_df$node_state[tree_input_df$Node %in% c("Bmo", "Panorpidae")] = "Panorpidae"
  tree_input_df$node_state[tree_input_df$Node %in% c("Tca", "Oligoneoptera")] = "Oligoneoptera"
  tree_input_df$node_state[tree_input_df$Node %in% c("Ame", "Holometabola")] = "Holometabola"
  tree_input_df$node_state[tree_input_df$Node %in% c("Bge", "Neoptera")] = "Neoptera"
  tree_input_df$node_state[tree_input_df$Node %in% c("Cdi", "Insecta")] = "Insecta"
  tree_input_df$node_state[tree_input_df$Node %in% c("Sma", "Arthropoda")] = "Arthropoda"
  tree_input_df$node_state[tree_input_df$Node %in% c("Obi", "Protostoma")] = "Protostoma"
  
  ts_gains_plot = ggplot(data=tree_input_df, aes(x=Node_x_position, y=Node_y_position)) +
    geom_line(data=subset(tree_input_df, ancestor_state=="ancestor"), 
              aes(group=ancestor_state),
              color="dimgray") +
    geom_line(data=subset(tree_input_df, node_state!="none"), 
              aes(group=node_state),
              color="dimgray") +
    geom_segment(data=subset(tree_input_df, ancestor_state=="ancestor" & Node %in% deuterostoma_side), 
                 aes(x=0, y=Node_y_position, xend=Node_x_position, yend=Node_y_position), 
                 linetype="dashed", stroke=0.2, color="dimgray") +
    geom_segment(data=subset(tree_input_df, ancestor_state=="ancestor" & Node %in% protostoma_side),
                 aes(x=Node_x_position, y=Node_y_position, xend=21.5, yend=Node_y_position), 
                 linetype="dashed", stroke=0.2, color="dimgray") +
    theme_void() +
    #add different labels on the two sides
    scale_x_continuous(breaks=as.numeric(names(node_x_labels)), labels=unname(node_x_labels)) +
    scale_y_continuous(breaks=node_y_values, labels=deuterostoma_y_labels,
                       sec.axis = dup_axis(labels=protostoma_y_labels)) +
    theme(axis.title=element_blank(),
          axis.text.x = element_text(angle=30, color="black"),
          axis.text.y = element_text(color="black"),
          plot.title=element_text(hjust=0.5))

  return(ts_gains_plot)
}

##########################
##########################

plot_taus_ts_gains = function(clade_tau_df, my_clade_species, nodelist) {
  category_tau_plot = ggplot(data=clade_tau_df, aes(x=Species, y=Tau, fill=Species)) +
      geom_boxplot(alpha=0) + #very ugly line of code to set the axis.
      
      geom_rect(data=subset(clade_tau_df, Species %in% c(my_clade_species[1], my_clade_species[length(my_clade_species)]))[1,],
          aes(ymin=0, ymax=1,
              xmin=which(nodelist==my_clade_species[1])-0.5,
              xmax=which(nodelist==my_clade_species[length(my_clade_species)])+0.5),
          color="white", fill="dimgray", alpha=0.3) +
      
      geom_boxplot(color="black", alpha=0.8) +
      geom_hline(yintercept = 0.75, color="red") +
      scale_fill_manual(values=my_species_colors) +
      theme_bw() +
      theme(axis.title = element_text(color="black"),
            axis.text.y = element_text(color="black"),
            axis.text.x = element_text(color="black", angle=30)) +
      scale_y_continuous(breaks=number_ticks(10), limits=c(0,1)) +
      guides(fill=FALSE)
    
    return(category_tau_plot)
}
```

```{r species_levels_order}
human_order = c("Brain_4wpc", "Brain_5wpc", "Brain_6wpc", "Brain_7wpc", "Brain_8wpc", "Brain_9wpc", 
                "Brain_10wpc", "Brain_11wpc", "Brain_12wpc", "Brain_13wpc", "Brain_16wpc", "Brain_18wpc", "Brain_19wpc",
                "Brain_20wpc", "Brain_newborn", "Brain_toddler", "Brain_infant", "Brain_school", "Brain_teenager", "Brain_youngAdult",
                "Brain_youngMidAge", "Brain_olderMidAge", "Brain_senior",
                
                
                "Testis_4wpc", "Testis_5wpc", "Testis_6wpc", "Testis_7wpc", "Testis_8wpc", "Testis_9wpc", 
                "Testis_10wpc", "Testis_11wpc", "Testis_12wpc", "Testis_13wpc", "Testis_16wpc", "Testis_18wpc", "Testis_19wpc", 
                "Testis_toddler", "Testis_infant", "Testis_youngTeenager", "Testis_oldTeenager", "Testis_youngAdult", 
                "Testis_youngMidAge", "Testis_olderMidAge", "Testis_Senior",
                
                "Ovary_4wpc", "Ovary_5wpc", "Ovary_6wpc",  "Ovary_7wpc", "Ovary_8wpc", "Ovary_9wpc", 
                "Ovary_10wpc", "Ovary_11wpc", "Ovary_12wpc", "Ovary_13wpc", "Ovary_16wpc", "Ovary_18wpc", 
                
                "Heart_4wpc", "Heart_5wpc", "Heart_6wpc", "Heart_7wpc", "Heart_8wpc", "Heart_9wpc", "Heart_10wpc", "Heart_11wpc", "Heart_12wpc",
                "Heart_13wpc", "Heart_16wpc", "Heart_18wpc", "Heart_19wpc", "Heart_newborn", "Heart_toddler", "Heart_infant", "Heart_teenager",
                "Heart_youngAdult", "Heart_olderMidAge",
                
                "Kidney_4wpc", "Kidney_5wpc", "Kidney_6wpc", "Kidney_7wpc", "Kidney_8wpc", "Kidney_9wpc", "Kidney_10wpc", "Kidney_11wpc",
                "Kidney_12wpc", "Kidney_13wpc", "Kidney_16wpc", "Kidney_18wpc", "Kidney_19wpc", "Kidney_20wpc", "Kidney_newborn", 
                "Kidney_infant",  "Kidney_toddler", "Kidney_school",
                
                "Liver_4wpc", "Liver_5wpc", "Liver_6wpc", "Liver_7wpc", "Liver_8wpc", "Liver_9wpc",
                "Liver_10wpc", "Liver_11wpc", "Liver_12wpc", "Liver_13wpc", "Liver_16wpc", "Liver_18wpc", "Liver_19wpc", "Liver_20wpc",
                "Liver_toddler", "Liver_infant", "Liver_newborn", "Liver_school", "Liver_teenager", "Liver_youngAdult", "Liver_olderMidAge", "Liver_senior")

macaque_order = c("Brain_e93", "Brain_e108", "Brain_e112", "Brain_e123", "Brain_e130",  "Brain_P0", "Brain_P23", "Brain_P152", "Brain_P365", "Brain_P1095", "Brain_P3285", 
                   "Brain_P5475", "Brain_P8030", 
                  
                  "Testis_e108", "Testis_e112", "Testis_e123", "Testis_e130", "Testis_P0", "Testis_P23", "Testis_P152", "Testis_P183", "Testis_P365",
                  "Testis_P1095", "Testis_P3285", "Testis_P5475", "Testis_P8030",
                  
                  "Heart_e93", "Heart_e108", "Heart_e112", "Heart_e123", "Heart_e130", "Heart_P0", "Heart_P23", "Heart_P152", "Heart_P1095", 
                  "Heart_P365", "Heart_P3285",  "Heart_P5475", "Heart_P8030", 
                  
                  "Kidney_e93", "Kidney_e108", "Kidney_e112", "Kidney_e123","Kidney_e130", "Kidney_P0", "Kidney_P23", "Kidney_P152", "Kidney_P183", "Kidney_P365",
                  "Kidney_P1095", "Kidney_P3285", "Kidney_P5475", "Kidney_P8030",
                  
                  "Liver_e108", "Liver_e112", "Liver_e123", "Liver_e130", "Liver_e93", "Liver_P0", "Liver_P23", "Liver_P152", "Liver_P183", "Liver_P365", "Liver_P1095", "Liver_P3285", 
                  "Liver_P5475", "Liver_P8030")

mouse_order = c("Brain_e10", "Brain_e11", "Brain_e12", "Brain_e13", "Brain_e14", "Brain_e15", "Brain_e16", "Brain_e17", "Brain_e18", 
                "Brain_P0", "Brain_P3", "Brain_P14", "Brain_P28", "Brain_P63",
                
                "Testis_e10", "Testis_e11", "Testis_e12", "Testis_e13", "Testis_e14", "Testis_e15", "Testis_e16", "Testis_e17", "Testis_e18", 
                "Testis_P0", "Testis_P3", "Testis_P14", "Testis_P28", "Testis_P63",
                
                "Ovary_e10", "Ovary_e11", "Ovary_e12", "Ovary_e13", "Ovary_e14", "Ovary_e15", "Ovary_e16", "Ovary_e17", "Ovary_e18", 
                "Ovary_P0", "Ovary_P14", "Ovary_P28", "Ovary_P3", "Ovary_P63",
                
                "Heart_e10", "Heart_e11", "Heart_e12", "Heart_e13", "Heart_e14", "Heart_e15", "Heart_e16", "Heart_e17", "Heart_e18",
                "Heart_P0",  "Heart_P3", "Heart_P14", "Heart_P28", "Heart_P63",
                
                "Kidney_e11", "Kidney_e12", "Kidney_e13", "Kidney_e14", "Kidney_e15", "Kidney_e16", "Kidney_e17", "Kidney_e18", 
                "Kidney_P0", "Kidney_P3", "Kidney_P14", "Kidney_P28", "Kidney_P63",
                
                "Liver_e10", "Liver_e11", "Liver_e12", "Liver_e13", "Liver_e14",  "Liver_e15",  "Liver_e16",  "Liver_e17",  "Liver_e18",
                "Liver_P0", "Liver_P3", "Liver_P14", "Liver_P28", "Liver_P63")

rat_order = c("Brain_e11", "Brain_e12", "Brain_e13", "Brain_e14", "Brain_e15", "Brain_e16", "Brain_e17", "Brain_e18", "Brain_e19", "Brain_e20",
              "Brain_P0", "Brain_P3", "Brain_P7", "Brain_P14", "Brain_P42", "Brain_P112",
              
              "Testis_e12", "Testis_e13", "Testis_e14", "Testis_e15", "Testis_e16", "Testis_e17", "Testis_e18", "Testis_e19", "Testis_e20", 
              "Testis_P0", "Testis_P3", "Testis_P7", "Testis_P14", "Testis_P42", "Testis_P112",
              
              "Ovary_e12", "Ovary_e13", "Ovary_e14", "Ovary_e15", "Ovary_e16", "Ovary_e17", "Ovary_e18", "Ovary_e19", "Ovary_e20", 
              "Ovary_P0", "Ovary_P3", "Ovary_P7", "Ovary_P14",  "Ovary_P42", "Ovary_P112", 
              
              "Heart_e11", "Heart_e12", "Heart_e13", "Heart_e14", "Heart_e15", "Heart_e16", "Heart_e17", "Heart_e18", "Heart_e19", "Heart_e20", 
              "Heart_P0",  "Heart_P3", "Heart_P7", "Heart_P14", "Heart_P42", "Heart_P112",
              
              "Kidney_e15", "Kidney_e16", "Kidney_e17", "Kidney_e18", "Kidney_e19", "Kidney_e20",
              "Kidney_P0", "Kidney_P3", "Kidney_P7", "Kidney_P14", "Kidney_P42", "Kidney_P112",
              
              "Liver_e12", "Liver_e13", "Liver_e14", "Liver_e15", "Liver_e16", "Liver_e17", "Liver_e18", "Liver_e19", "Liver_e20",
              "Liver_P0", "Liver_P3", "Liver_P14", "Liver_P7", "Liver_P42", "Liver_P112")

rabbit_order = c("Brain_e12", "Brain_e13", "Brain_e14", "Brain_e15", "Brain_e16", "Brain_e18", "Brain_e19", "Brain_e21", "Brain_e23", "Brain_e24", "Brain_e27",
                 "Brain_P0", "Brain_P14", "Brain_P84", "Brain_P186",
                 
                 "Testis_e12", "Testis_e13", "Testis_e14", "Testis_e15", "Testis_e16", "Testis_e18", "Testis_e19", "Testis_e21", "Testis_e23", "Testis_e24", "Testis_e27", 
                 "Testis_P0", "Testis_P14", "Testis_P84", "Testis_P186",
                 
                 "Ovary_e12", "Ovary_e13", "Ovary_e14", "Ovary_e15", "Ovary_e16", "Ovary_e18", "Ovary_e19", "Ovary_e21", "Ovary_e23", "Ovary_e24", "Ovary_e27", 
                 "Ovary_P0", "Ovary_P14", "Ovary_P186", 
                 
                 "Heart_e12", "Heart_e13", "Heart_e14", "Heart_e15", "Heart_e16", "Heart_e18", "Heart_e19", "Heart_e21", "Heart_e23", "Heart_e24", "Heart_e27",
                 "Heart_P0", "Heart_P14", "Heart_P84", "Heart_P186",
                 
                 "Kidney_e15", "Kidney_e16", "Kidney_e18", "Kidney_e19", "Kidney_e21", "Kidney_e23", "Kidney_e24", "Kidney_e27", 
                 "Kidney_P0", "Kidney_P14", "Kidney_P84", "Kidney_P186", 
                 
                 "Liver_e13", "Liver_e14", "Liver_e15", "Liver_e16", "Liver_e18", "Liver_e19", "Liver_e21", "Liver_e23", "Liver_e24", "Liver_e27",
                 "Liver_P0", "Liver_P14", "Liver_P84", "Liver_P186")

opossum_order = c("Brain_13", "Brain_14", "Brain_16", "Brain_18", "Brain_20", "Brain_24", "Brain_28", "Brain_35", "Brain_42", "Brain_56",
                  "Brain_74", "Brain_104", "Brain_134", "Brain_164", "Brain_194",
                  
                  "Testis_16", "Testis_18", "Testis_20", "Testis_24", "Testis_28", "Testis_35", "Testis_42", "Testis_56", "Testis_74",
                  "Testis_104", "Testis_134", "Testis_164", "Testis_194",  
                  
                 "Ovary_16", "Ovary_18", "Ovary_20", "Ovary_24", "Ovary_28", "Ovary_35", "Ovary_42", 
                 "Ovary_104", "Ovary_134", "Ovary_164", "Ovary_194",  "Ovary_56", "Ovary_74",
                  
                 "Heart_13", "Heart_14", "Heart_16", "Heart_18", "Heart_20", "Heart_24", "Heart_28", "Heart_35", "Heart_42", "Heart_56", "Heart_74", 
                 "Heart_104",  "Heart_134",  "Heart_164",  "Heart_194", 
                 
                "Kidney_24", "Kidney_28", "Kidney_35", "Kidney_42", "Kidney_56", "Kidney_74",
                "Kidney_104", "Kidney_134", "Kidney_164", "Kidney_194",
                
                "Liver_13", "Liver_14", "Liver_16", "Liver_18", "Liver_20", "Liver_24", "Liver_28", "Liver_35", "Liver_42", "Liver_56", "Liver_74",
                "Liver_104", "Liver_134", "Liver_164", "Liver_194")

samples_orders = list()
samples_orders[["Human"]] = human_order
samples_orders[["Macaque"]] = macaque_order
samples_orders[["Mouse"]] = mouse_order
samples_orders[["Rat"]] = rat_order
samples_orders[["Rabbit"]] = rabbit_order
samples_orders[["Opossum"]] = opossum_order
```

```{r plot_Fgf17_developmental_expression_brain_cerebellum_average_v2, echo=FALSE, message=FALSE, warning=FALSE, dependson=c("setup", "functions"), fig.width=12, fig.height=15}
#Generate variables
Kaessman_species = c("Human", "Macaque", "Mouse", "Rat", "Rabbit", "Opossum")
Kaessman_tissues = c("Brain", "Cerebellum", "Testis", "Ovary", "Heart", "Kidney", "Liver")
#Kaessman_tissues = c("Brain", "Testis", "Ovary", "Heart", "Kidney", "Liver")
Kaessman_tissue_colors = c("Brain"="mediumblue", 
                           "Cerebellum"="dodgerblue2", 
                           "Testis"="violet", 
                           "Ovary"="darkorchid",
                           "Heart"="springgreen3",
                           "Kidney"="gold",
                           "Liver"="tan4")

#Upload expression from Kaessman paper
expr_file = paste0(home, "projects/bilaterian_GE/downloaded/Kaessman_dev_expr/Fgf17_Kaessman_orthologs_expr.tab")
expr_long_df = read.delim(expr_file, header=FALSE, col.names=c("Species", "Sample", "GeneID", "Expr"))
expr_long_df$Sample = sub("\\..*", "", sub("\\.", "_", expr_long_df$Sample))


all_plots_list = list()
i = 1
for (species in Kaessman_species) {
  species_expr_df = subset(expr_long_df, Species==species)
  species_expr_df = species_expr_df %>%
    separate(Sample, c("Tissue", "Timepoint"), remove=FALSE)
  
  GeneID = unique(species_expr_df$GeneID)
  
  #Order by samples by tissue
  final_species_expr_df = vector()
  for (tissue in Kaessman_tissues) {
    tissue_df = subset(species_expr_df, Tissue==tissue)
    final_species_expr_df = rbind(final_species_expr_df, tissue_df)
  }
  
  species_median_expr_long_df = final_species_expr_df %>%
    group_by(Species, Sample, Tissue, Timepoint, GeneID) %>%
    summarize(Median_expr = median(Expr)) %>%
    #separate(Sample, c("Tissue", "Timepoint"), remove=FALSE) %>%
    unite("Species_sample", c(Species, Sample), remove=FALSE)
  
  ####Get average between brain and cerebellum
  species_median_expr_long_df$Tissue[species_median_expr_long_df$Tissue=="Cerebellum"] = "Brain"
  species_median_expr_long_df$Sample = sub("Cerebellum", "Brain", species_median_expr_long_df$Sample)
  
  species_median_expr_long_df = species_median_expr_long_df %>%
    group_by(Species, Sample, Tissue, Timepoint, GeneID) %>%
    summarise(Avg_median_expr=mean(Median_expr))
  
  #Get sample order
  sample_order = samples_orders[[species]]
  sample_labels = sub(".*_", "", sample_order)
  #if (species=="Human") {sample_order = human_order; samples_labels = human_labels}
  
  species_median_expr_long_df$Sample = factor(species_median_expr_long_df$Sample, levels=sample_order)
  species_median_expr_long_df$Tissue = factor(species_median_expr_long_df$Tissue, levels=Kaessman_tissues[Kaessman_tissues!="Cerebellum"])
  #species_median_expr_long_df$Log2_expr = log2(species_median_expr_long_df$Median_expr+1)
  
  species_plot = ggplot(data=species_median_expr_long_df, aes(x=Sample, y=Avg_median_expr, color=Tissue, fill=Tissue, group=Tissue)) +
    geom_point() +
    geom_line() +
    scale_color_manual(values=Kaessman_tissue_colors) +
    scale_fill_manual(values=Kaessman_tissue_colors) +
    ggtitle(paste0(species, " ~ ", GeneID)) +
    theme_bw() +
    ylab("Median RPKM expr") +
    scale_x_discrete(labels = sample_labels) +
    scale_y_continuous(breaks = number_ticks(6)) +
    theme(axis.text.x = element_text(color="black", angle=90, vjust=0, hjust=1),
          axis.text.y = element_text(color="black"),
          axis.title.y = element_text(color="black"),
          axis.title.x = element_blank(),
          legend.position = c(0.9,0.9),
          legend.direction = "horizontal",
          legend.justification = c("right", "top"),
          plot.margin = unit(c(0,0,0,0), "cm")) +
    coord_cartesian(ylim=c(0,30))
  
  #print(species_plot)
  all_plots_list[[i]] = species_plot
  i = i+1
}

final_plots = plot_grid(plotlist = all_plots_list, ncol=1, align = "vh", labels=c("A", "B", "C", "D", "E", "F"))
print(final_plots)

pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/SupFig10-v6-CORRECTED.pdf", width=12, height=15)
print(final_plots)
dev.off()
```


<!-- Backup -->
```{r plot_Fgf17_developmental_expression_brain_cerebellum_average, echo=FALSE, message=FALSE, warning=FALSE, dependson=c("setup", "functions"), fig.width=12, fig.height=15}
#Generate variables
Kaessman_species = c("Human", "Macaque", "Mouse", "Rat", "Rabbit", "Opossum")
Kaessman_tissues = c("Brain", "Cerebellum", "Testis", "Ovary", "Heart", "Kidney", "Liver")
#Kaessman_tissues = c("Brain", "Testis", "Ovary", "Heart", "Kidney", "Liver")
Kaessman_tissue_colors = c("Brain"="mediumblue", 
                           "Cerebellum"="dodgerblue2", 
                           "Testis"="violet", 
                           "Ovary"="darkorchid",
                           "Heart"="springgreen3",
                           "Kidney"="gold",
                           "Liver"="tan4")


#This is because human has some samples for cerebellum that are not included in brain
human_order = c("Brain_4wpc", "Brain_5wpc", "Brain_6wpc", "Brain_7wpc", "Brain_8wpc", "Brain_9wpc","Brain_10wpc", "Brain_11wpc", "Brain_12wpc",
                "Brain_13wpc", "Brain_16wpc", "Brain_18wpc", "Brain_19wpc", "Brain_20wpc", "Brain_newborn", "Brain_infant", "Brain_toddler",
                "Brain_school", "Brain_teenager", "Brain_youngAdult", "Brain_youngMidAge", "Brain_olderMidAge", "Brain_senior",
                "Testis_4wpc", "Testis_5wpc", "Testis_6wpc", "Testis_7wpc", "Testis_8wpc", "Testis_9wpc", "Testis_10wpc", "Testis_11wpc", "Testis_12wpc",
                "Testis_13wpc", "Testis_16wpc", "Testis_18wpc", "Testis_19wpc", "Testis_infant", "Testis_toddler", "Testis_youngTeenager", "Testis_oldTeenager",
                "Testis_youngAdult", "Testis_youngMidAge", "Testis_olderMidAge", "Testis_Senior", "Ovary_4wpc", "Ovary_5wpc", "Ovary_6wpc", "Ovary_7wpc",
                "Ovary_8wpc", "Ovary_9wpc", "Ovary_10wpc", "Ovary_11wpc", "Ovary_12wpc", "Ovary_13wpc", "Ovary_16wpc", "Ovary_18wpc", "Heart_4wpc", "Heart_5wpc",
                "Heart_6wpc", "Heart_7wpc", "Heart_8wpc", "Heart_9wpc", "Heart_10wpc", "Heart_11wpc", "Heart_12wpc", "Heart_13wpc", "Heart_16wpc", "Heart_18wpc",
                "Heart_19wpc", "Heart_newborn", "Heart_infant", "Heart_toddler", "Heart_teenager", "Heart_youngAdult", "Heart_olderMidAge",
                "Kidney_4wpc", "Kidney_5wpc", "Kidney_6wpc", "Kidney_7wpc", "Kidney_8wpc", "Kidney_9wpc", "Kidney_10wpc", "Kidney_11wpc", "Kidney_12wpc",
                "Kidney_13wpc", "Kidney_16wpc", "Kidney_18wpc", "Kidney_19wpc", "Kidney_20wpc", "Kidney_newborn", "Kidney_infant", "Kidney_toddler", "Kidney_school",
                "Liver_4wpc", "Liver_5wpc", "Liver_6wpc", "Liver_7wpc", "Liver_8wpc", "Liver_9wpc", "Liver_10wpc", "Liver_11wpc", "Liver_12wpc", "Liver_13wpc",
                "Liver_16wpc", "Liver_18wpc", "Liver_19wpc", "Liver_20wpc", "Liver_newborn", "Liver_infant", "Liver_toddler", "Liver_school", "Liver_teenager",
                "Liver_youngAdult", "Liver_olderMidAge", "Liver_senior")
human_labels = sub(".*_", "", human_order)

#Upload expression from Kaessman paper
expr_file = paste0(home, "projects/bilaterian_GE/downloaded/Kaessman_dev_expr/Fgf17_Kaessman_orthologs_expr.tab")
expr_long_df = read.delim(expr_file, header=FALSE, col.names=c("Species", "Sample", "GeneID", "Expr"))
expr_long_df$Sample = sub("\\..*", "", sub("\\.", "_", expr_long_df$Sample))


all_plots_list = list()
i = 1
for (species in Kaessman_species) {
  species_expr_df = subset(expr_long_df, Species==species)
  species_expr_df = species_expr_df %>%
    separate(Sample, c("Tissue", "Timepoint"), remove=FALSE)
  
  GeneID = unique(species_expr_df$GeneID)
  
  #Order by samples by tissue
  final_species_expr_df = vector()
  for (tissue in Kaessman_tissues) {
    tissue_df = subset(species_expr_df, Tissue==tissue)
    final_species_expr_df = rbind(final_species_expr_df, tissue_df)
  }
  #Get sample order
  sample_order = unique(final_species_expr_df$Sample)
  sample_labels = unique(final_species_expr_df[,c("Sample", "Timepoint")])$Timepoint
  if (species=="Human") {sample_order = human_order; samples_labels = human_labels}
  
  species_median_expr_long_df = final_species_expr_df %>%
    group_by(Species, Sample, Tissue, Timepoint, GeneID) %>%
    summarize(Median_expr = median(Expr)) %>%
    #separate(Sample, c("Tissue", "Timepoint"), remove=FALSE) %>%
    unite("Species_sample", c(Species, Sample), remove=FALSE)
  
  ####Get average between brain and cerebellum
  species_median_expr_long_df$Tissue[species_median_expr_long_df$Tissue=="Cerebellum"] = "Brain"
  species_median_expr_long_df$Sample = sub("Cerebellum", "Brain", species_median_expr_long_df$Sample)
  
  species_median_expr_long_df = species_median_expr_long_df %>%
    group_by(Species, Sample, Tissue, Timepoint, GeneID) %>%
    summarise(Avg_median_expr=mean(Median_expr))
  
  species_median_expr_long_df$Sample = factor(species_median_expr_long_df$Sample, levels=sample_order)
  species_median_expr_long_df$Tissue = factor(species_median_expr_long_df$Tissue, levels=Kaessman_tissues[Kaessman_tissues!="Cerebellum"])
  #species_median_expr_long_df$Log2_expr = log2(species_median_expr_long_df$Median_expr+1)
  
  species_plot = ggplot(data=species_median_expr_long_df, aes(x=Sample, y=Avg_median_expr, color=Tissue, fill=Tissue, group=Tissue)) +
    geom_point() +
    geom_line() +
    scale_color_manual(values=Kaessman_tissue_colors) +
    scale_fill_manual(values=Kaessman_tissue_colors) +
    ggtitle(paste0(species, " ~ ", GeneID)) +
    theme_bw() +
    ylab("Median RPKM expr") +
    scale_x_discrete(labels = sample_labels) +
    scale_y_continuous(breaks = number_ticks(6)) +
    theme(axis.text.x = element_text(color="black", angle=90, vjust=0, hjust=1),
          axis.text.y = element_text(color="black"),
          axis.title.y = element_text(color="black"),
          axis.title.x = element_blank(),
          legend.position = c(0.9,0.9),
          legend.direction = "horizontal",
          legend.justification = c("right", "top"),
          plot.margin = unit(c(0,0,0,0), "cm")) +
    coord_cartesian(ylim=c(0,30))
  
  #print(species_plot)
  all_plots_list[[i]] = species_plot
  i = i+1
}

final_plots = plot_grid(plotlist = all_plots_list, ncol=1, align = "vh", labels=c("A", "B", "C", "D", "E", "F"))
print(final_plots)

#pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/SupFig10-v5.pdf", width=12, height=15)
#print(final_plots)
#dev.off()
```

```{r plot_Fgf17_developmental_expression_brain_cerebellum_average_v1, echo=FALSE, message=FALSE, warning=FALSE, dependson=c("setup", "functions"), fig.width=12, fig.height=15}
#Generate variables
Kaessman_species = c("Human", "Macaque", "Mouse", "Rat", "Rabbit", "Opossum")
Kaessman_tissues = c("Brain", "Cerebellum", "Testis", "Ovary", "Heart", "Kidney", "Liver")
#Kaessman_tissues = c("Brain", "Testis", "Ovary", "Heart", "Kidney", "Liver")
Kaessman_tissue_colors = c("Brain"="mediumblue", 
                           "Cerebellum"="dodgerblue2", 
                           "Testis"="violet", 
                           "Ovary"="darkorchid",
                           "Heart"="springgreen3",
                           "Kidney"="gold",
                           "Liver"="tan4")


#This is because human has some samples for cerebellum that are not included in brain
human_order = c("Brain_4wpc", "Brain_5wpc", "Brain_6wpc", "Brain_7wpc", "Brain_8wpc", "Brain_9wpc","Brain_10wpc", "Brain_11wpc", "Brain_12wpc",
                "Brain_13wpc", "Brain_16wpc", "Brain_18wpc", "Brain_19wpc", "Brain_20wpc", "Brain_newborn", "Brain_infant", "Brain_toddler",
                "Brain_school", "Brain_teenager", "Brain_youngAdult", "Brain_youngMidAge", "Brain_olderMidAge", "Brain_senior",
                "Testis_4wpc", "Testis_5wpc", "Testis_6wpc", "Testis_7wpc", "Testis_8wpc", "Testis_9wpc", "Testis_10wpc", "Testis_11wpc", "Testis_12wpc",
                "Testis_13wpc", "Testis_16wpc", "Testis_18wpc", "Testis_19wpc", "Testis_infant", "Testis_toddler", "Testis_youngTeenager", "Testis_oldTeenager",
                "Testis_youngAdult", "Testis_youngMidAge", "Testis_olderMidAge", "Testis_Senior", "Ovary_4wpc", "Ovary_5wpc", "Ovary_6wpc", "Ovary_7wpc",
                "Ovary_8wpc", "Ovary_9wpc", "Ovary_10wpc", "Ovary_11wpc", "Ovary_12wpc", "Ovary_13wpc", "Ovary_16wpc", "Ovary_18wpc", "Heart_4wpc", "Heart_5wpc",
                "Heart_6wpc", "Heart_7wpc", "Heart_8wpc", "Heart_9wpc", "Heart_10wpc", "Heart_11wpc", "Heart_12wpc", "Heart_13wpc", "Heart_16wpc", "Heart_18wpc",
                "Heart_19wpc", "Heart_newborn", "Heart_infant", "Heart_toddler", "Heart_teenager", "Heart_youngAdult", "Heart_olderMidAge",
                "Kidney_4wpc", "Kidney_5wpc", "Kidney_6wpc", "Kidney_7wpc", "Kidney_8wpc", "Kidney_9wpc", "Kidney_10wpc", "Kidney_11wpc", "Kidney_12wpc",
                "Kidney_13wpc", "Kidney_16wpc", "Kidney_18wpc", "Kidney_19wpc", "Kidney_20wpc", "Kidney_newborn", "Kidney_infant", "Kidney_toddler", "Kidney_school",
                "Liver_4wpc", "Liver_5wpc", "Liver_6wpc", "Liver_7wpc", "Liver_8wpc", "Liver_9wpc", "Liver_10wpc", "Liver_11wpc", "Liver_12wpc", "Liver_13wpc",
                "Liver_16wpc", "Liver_18wpc", "Liver_19wpc", "Liver_20wpc", "Liver_newborn", "Liver_infant", "Liver_toddler", "Liver_school", "Liver_teenager",
                "Liver_youngAdult", "Liver_olderMidAge", "Liver_senior")
human_labels = sub(".*_", "", human_order)

#Upload expression from Kaessman paper
expr_file = paste0(home, "projects/bilaterian_GE/downloaded/Kaessman_dev_expr/Fgf17_Kaessman_orthologs_expr.tab")
expr_long_df = read.delim(expr_file, header=FALSE, col.names=c("Species", "Sample", "GeneID", "Expr"))
expr_long_df$Sample = sub("\\..*", "", sub("\\.", "_", expr_long_df$Sample))


all_plots_list = list()
i = 1
for (species in Kaessman_species) {
  species_expr_df = subset(expr_long_df, Species==species)
  species_expr_df = species_expr_df %>%
    separate(Sample, c("Tissue", "Timepoint"), remove=FALSE)
  
  GeneID = unique(species_expr_df$GeneID)
  
  #Order by samples by tissue
  final_species_expr_df = vector()
  for (tissue in Kaessman_tissues) {
    tissue_df = subset(species_expr_df, Tissue==tissue)
    final_species_expr_df = rbind(final_species_expr_df, tissue_df)
  }
  
  #Get sample order
  species_median_expr_long_df = final_species_expr_df %>%
    group_by(Species, Sample, Tissue, Timepoint, GeneID) %>%
    summarize(Median_expr = median(Expr)) %>%
    #separate(Sample, c("Tissue", "Timepoint"), remove=FALSE) %>%
    unite("Species_sample", c(Species, Sample), remove=FALSE)
  
  ####Get average between brain and cerebellum
  species_median_expr_long_df$Tissue[species_median_expr_long_df$Tissue=="Cerebellum"] = "Brain"
  species_median_expr_long_df$Sample = sub("Cerebellum", "Brain", species_median_expr_long_df$Sample)
  
  species_median_expr_long_df = species_median_expr_long_df %>%
    group_by(Species, Sample, Tissue, Timepoint, GeneID) %>%
    summarise(Avg_median_expr=mean(Median_expr))
  
  sample_order = unique(species_median_expr_long_df$Sample)
  sample_labels = unique(species_median_expr_long_df[,c("Sample", "Timepoint")])$Timepoint
  
  species_median_expr_long_df$Sample = factor(species_median_expr_long_df$Sample, levels=sample_order)
  species_median_expr_long_df$Tissue = factor(species_median_expr_long_df$Tissue, levels=Kaessman_tissues[Kaessman_tissues!="Cerebellum"])
  #species_median_expr_long_df$Log2_expr = log2(species_median_expr_long_df$Median_expr+1)
  

  #if (species=="Human") {sample_order = human_order; samples_labels = human_labels}
  
  species_plot = ggplot(data=species_median_expr_long_df, aes(x=Sample, y=Avg_median_expr, color=Tissue, fill=Tissue, group=Tissue)) +
    geom_point() +
    geom_line() +
    scale_color_manual(values=Kaessman_tissue_colors) +
    scale_fill_manual(values=Kaessman_tissue_colors) +
    ggtitle(paste0(species, " ~ ", GeneID)) +
    theme_bw() +
    ylab("Median RPKM expr") +
    scale_x_discrete(labels = sample_labels) +
    scale_y_continuous(breaks = number_ticks(6)) +
    theme(axis.text.x = element_text(color="black", angle=90, vjust=0, hjust=1),
          axis.text.y = element_text(color="black"),
          axis.title.y = element_text(color="black"),
          axis.title.x = element_blank(),
          legend.position = c(0.9,0.9),
          legend.direction = "horizontal",
          legend.justification = c("right", "top"),
          plot.margin = unit(c(0,0,0,0), "cm")) +
    coord_cartesian(ylim=c(0,30))
  
  #print(species_plot)
  all_plots_list[[i]] = species_plot
  i = i+1
}

final_plots = plot_grid(plotlist = all_plots_list, ncol=1, align = "vh", labels=c("A", "B", "C", "D", "E", "F"))
print(final_plots)

#pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/SupFig10-v5.pdf", width=12, height=15)
#print(final_plots)
#dev.off()
```

