---
title: "SupFig3"
output: html_document
---

```{r setup, include=FALSE}
#set Knitr option
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

#upload libraries
library(ggplot2)
library(mixOmics)
library(hashmap)
library(reshape2)
library(pheatmap)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(viridis)
library(gridExtra)
library(egg)

#set directories
home="/Users/federica/mnt/"
gene_sets_dir=paste0(home, "projects/bilaterian_GE/data/gene_sets/")
#tissue_expr_dir=paste0(home, "projects/bilaterian_GE/data/preprocessing/average_expr_by_tissue/")
pca_dir=paste0(home, "projects/bilaterian_GE/data/pca_analysis_all_norms/")
metadata_dir=paste0(home, "projects/bilaterian_GE/data/samples_metadata/")
splsda_dir= paste0(home, "projects/bilaterian_GE/data/splsda_analysis/")
diff_expr_dir = paste0(home, "projects/bilaterian_GE/data/differential_expression/")
general_patterns_dir = paste0(home, "projects/bilaterian_GE/data/vertebrates_vs_insects_general_patterns/")
branches_length_dir = paste0(home, "projects/bilaterian_GE/data/branches_length_analysis/")

#set variables
my_version = "All_version2"
my_category = "STRICT"
my_evo_type = "conserved"
clades = c("Vertebrata", "Insecta", "Bilateria")
clades_PCA = c("Vertebrata", "Insecta", "Bilateria")
options("scipen"=100, "digits"=4)

all_species = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi", "Bla", "Sp2", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi")
ordered_species = all_species
Bilateria = all_species
Vertebrata = c("Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dre", "Cmi")
Insecta = c("Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi")
Outgroups = c("Bla", "Sp2", "Sma", "Obi")
all_tissues=c("Adipose", "DigestiveTract", "Kidney", "Epithelial", "Muscle", "Neural", "Ovary", "Testis")
ordered_tissues = c("Neural", "Testis", "Ovary", "Muscle", "Kidney", "Epithelial", "DigestiveTract", "Adipose")

#set aestetics vectors
my_color_vector = c("Neural"="mediumblue", "Testis"="violet", "Ovary"="darkorchid", "Muscle"="springgreen3", 
                    "Kidney"="gold", "Epithelial"="steelblue1", "DigestiveTract"="chocolate1", "Adipose"="firebrick1")
my_shapes_vector = c("Hs2"=0, "Mm2"=1, "Bt2"=2, "Mdo"=3, "Gga"=4, "Xtr"=5, "Dre"=6, "Cmi"=7, "Bla"=9, "Sp2"=8, 
                     "Dme"=15, "Eba"=18, "Aae"= 23, "BmA"=25, "Tca"=17, "Bge"=10, "Ame"=16, "Cdi"=13, "Sma"=14, "Obi"=11)
my_alpha_vector=c("Hs2"=1, "Mm2"=1, "Bt2"=1, "Mdo"=1, "Gga"=1, "Xtr"=1, "Dre"=1, "Cmi"=1, "Bla"=0.5, "Sp2"=0.5, "Sma"=0.5, "Ame"=0.5, "Dme"=0.5, "Cdi"=0.5, "Obi"=0.5, "Bge"=0.5, "BmA"=0.5, "Tca"=0.5)
my_sets_color = c("Vertebrata"= "mediumorchid", "Deuterostoma"="olivedrab3", "Insecta"="tan3", "Protostoma"="yellow", "Bilateria"="firebrick1", "Outgroups"="dimgray")
my_species_colors=c("Hs2"="#00BFFF", "Mm2"="#159DFF", "Bt2"="#1873CD", "Mdo"="#174B8B", "Gga"="#3F3F8B", "Xtr"="#64398B", "Dre"="#82359D", "Cmi"="#9932CC", "Bla"="#2E8B57", "Sp2"="#96B12B", "Obi"="#FFFF00", "Sma"="#FFCC33", "Cdi"="goldenrod", "Bge"="burlywood2", "Ame"="#FF9966", "Tca"="#FF6600", "BmA"="#CC6600", "Aae"="#993300", "Eba"="firebrick3", "Dme"="red")
my_copy_status_colors = c("single_copy_ortholog"="gray18", "duplicated"="gray76")


#Create named vector with PC and corresponding tissue
PC_tissue_named_vector = c("1"="Neural", "2"="Testis", "3"="Ovary", 
                          "4"="Muscle", "5"="Kidney", "6"="Epithelial", 
                          "7"="DigestiveTract", "8"="Adipose")
paletteLength = 75
palette_brewer = colorRampPalette(rev(brewer.pal(11, "RdBu")))(paletteLength)
```

```{r functions, warning=FALSE, message=FALSE, echo=FALSE, dependson="setup"}
number_ticks <- function(n) {function(limits) pretty(limits, n)}

firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

####################################
####################################

get_cor_table = function(input_table, query_species, my_tissue)  {
  #select the Neural columns belonging to the set species
  tissue_samples = colnames(input_table)[grep(my_tissue, colnames(input_table))]
  #subset the table: only tissue samples
  tissue_expr_table = input_table[,tissue_samples]
  colnames(tissue_expr_table) = sub("_.*", "", colnames(tissue_expr_table))
  set_species = colnames(tissue_expr_table)
  #get target species depending on the species set
  all_target_species = set_species
  final_matrix =  vector()
  if (!(query_species %in% colnames(tissue_expr_table))) {
    final_table = c(query_species, NA, my_tissue, NA)
      return(final_table)} else {
  for (target_species in all_target_species) {
    subsetted_table = tissue_expr_table[,c(query_species, target_species)]
    subsetted_table = subsetted_table[complete.cases(subsetted_table),] #remove all rows containing one or two NAs
    query_vector  = as.vector(subsetted_table[,query_species]) #isolate query vector
    target_vector = as.vector(subsetted_table[,target_species]) #isolate target vector
    rho = cor.test(query_vector, target_vector, method="spearman")$estimate #isolate rho
    final_matrix = rbind(final_matrix, c(query_species, target_species, my_tissue, rho)) #append to final matrix
  }
  final_table = as.data.frame(final_matrix)
  colnames(final_table) = c("species_query", "species_target", "tissue", "cor")
  final_table$cor = as.numeric(as.vector(final_table$cor))
  return(final_table)
  }
}

####################################
####################################

plot_gene_expr = function(original_OG_ID, loadings_expr_df_long, OGID_humanID_dict, Vertebrata, Insecta, Outgroups) {
  all_plots = list()
  i = 1
  for (clade in c("Vertebrata", "Insecta", "Outgroups")) {
    my_OG_ID = paste0(OGID_humanID_dict$find(original_OG_ID), " ~ ", original_OG_ID)
    OG_expr_df = subset(loadings_expr_df_long, OG_ID == original_OG_ID)
    my_max = max(OG_expr_df$Expr, na.rm=TRUE)
    my_min = min(OG_expr_df$Expr, na.rm=TRUE)
    if (clade == "Vertebrata") {OG_expr_df = subset(OG_expr_df, Species %in% Vertebrata)}
    if (clade == "Insecta") {OG_expr_df = subset(OG_expr_df, Species %in% Insecta)}
    if (clade == "Outgroups") {OG_expr_df = subset(OG_expr_df, Species %in% Outgroups)}
    
    expr_plot = ggplot(data=OG_expr_df, aes(x=Tissue, y=Expr, fill=Tissue), color="black") +
      geom_boxplot(alpha=0.7, outlier.shape = NA) +
      geom_jitter(aes(shape=Species), width=0.2, fill="black") +
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(values=my_shapes_vector) +
      theme_bw() +
      theme(axis.title = element_text(color="black"),
            axis.text.x = element_text(color="black", angle=30, hjust=1, vjust=1)
            ) +
      guides(fill=FALSE) +
      ggtitle(paste0(my_OG_ID, " ~ ", clade)) +
      ylim(c(my_min, my_max))
    
    all_plots[[i]] = expr_plot
    i = i+1
  }
  final_plot = plot_grid(all_plots[[1]], all_plots[[2]], all_plots[[3]], ncol=3, rel_widths = c(1,1,1))
  return(final_plot)
}


####################################
####################################

get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

```

```{r generate_metadata_table, echo=FALSE, warning=FALSE, message=FALSE, dependson="setup"}
all_metadata_df = vector()
for (species in all_species) {
  file_species = species
  if (species == "BmA") {file_species= "Bmo"}
  metadata_df = unique(read.delim(paste0(metadata_dir, file_species, "_samples_info.tab"), header=TRUE)[,1:3])
  colnames(metadata_df) = c("species", "tissues", "metasample")
  metadata_df$species = rep(species, nrow(metadata_df)) #This is necessary only to translate Bmo to BmA
  rownames(metadata_df) = paste0(rep(species, nrow(metadata_df)), "_", as.vector(metadata_df$metasample))
  metadata_df$metasample = NULL
  all_metadata_df = rbind(all_metadata_df, metadata_df)
}
colnames(all_metadata_df) = c("species", "tissues")

sample_tissue_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$tissues))
sample_species_dict = hashmap(rownames(all_metadata_df), as.vector(all_metadata_df$species))
```

<!-- Panels A-I: All the sPLS-DA coordinates for all the tissues -->
```{r sPLS_DA_vertebrates_vs_insects, warning=FALSE, echo=FALSE, message=FALSE, dependson="setup", fig.width=12, fig.height=14}
#########################################
# tissue_PC_list = list("Vertebrata_Neural" = "Positive_PC2",
#                      "Insecta_Neural" = "Negative_PC2",
#                      "Vertebrata_Testis" = c("Positive_PC2", "Positive_PC3"),
#                      "Insecta_Testis" = "Negative_PC2",
#                      "Vertebrata_Ovary" = "Positive_PC2",
#                      "Insecta_Ovary" = "Negative_PC1",
#                      "Vertebrata_Muscle" = "Negative_PC2",
#                      "Insecta_Muscle" = c("Positive_PC2", "Positive_PC3"),
#                      "Vertebrata_Kidney" = c("Positive_PC1", "Positive_PC3"),
#                      "Insecta_Kidney" = "Negative_PC2",
#                      "Vertebrata_Epithelial" = "Positive_PC1",
#                      "Insecta_Epithelial" = "Negative_PC2",
#                      "Vertebrata_DigestiveTract" = "Positive_PC1",
#                      "Insecta_DigestiveTract" = "Negative_PC2",
#                      "Vertebrata_Adipose" = "Positive_PC1",
#                      "Insecta_Adipose" = "Negative_PC2")
#########################################
all_tissue_PCs = list("Neural"=2, 
                   "Testis"=c(2,3), 
                   "Ovary"=c(1,2), 
                   "Muscle"=c(2,3), 
                   "Kidney"=c(1,2,3), 
                   "Epithelial"=c(1,2),
                   "DigestiveTract"=c(1,2),
                   "Adipose"=c(1,2))

#Get expression df
expr_file = paste0(pca_dir, my_version, "/", my_category, "/Bilateria/", my_evo_type, "/Bilateria_conserved-metasamples_median_expr-NOSVA-log2-TPMs-NORM-BH_genes.tab")
expr_df = read.table(expr_file, header=TRUE, row=1)
expr_df = expr_df[, colnames(expr_df) %in% rownames(all_metadata_df)]

all_PC_plots = list()
i = 1
for (query_tissue in ordered_tissues) {
  my_test = load(paste0(splsda_dir, my_version, "/STRICT/Bilateria/conserved/Bilateria_conserved-metasamples_median_expr-tuned_sPLSDA-clade_tissue-", query_tissue, ".RDATA"))
  ncomp <- tune.splsda.srbct$choice.ncomp$ncomp
  select.keepX <- tune.splsda.srbct$choice.keepX[1:ncomp]
  
  clade_tissue_df = all_metadata_df
  clade_tissue_df$clade_tissue = rep("Others", nrow(clade_tissue_df))
  clade_tissue_df$clade_tissue[clade_tissue_df$species %in% Vertebrata & clade_tissue_df$tissues==query_tissue] = paste0("Vertebrata_", query_tissue)
  clade_tissue_df$clade_tissue[clade_tissue_df$species %in% Insecta & clade_tissue_df$tissues==query_tissue] = paste0("Insecta_", query_tissue)
  sample_tissue_dict = hashmap(rownames(clade_tissue_df), as.vector(clade_tissue_df$clade_tissue))
  
  #Generate the needed membership factor
  samples_membership = factor(sample_tissue_dict$find(colnames(expr_df)))
  splsda.srbct <- splsda(t(as.matrix(expr_df)), samples_membership, ncomp = ncomp, keepX = select.keepX)
  
  #####Plotting PCs
  #Here I want to plot with my colors and shapes
  my_PC_df = as.data.frame(splsda.srbct$variates$X)
  colnames(my_PC_df) = paste0(rep("PC", length(colnames(my_PC_df))), seq(1, length(colnames(my_PC_df))))
  #add tissue and species. Use the dictionaries generated in the upload_feature_table chunck.
  my_PC_df$tissues = sample_tissue_dict$find(rownames(my_PC_df))
  my_PC_df$species = factor(sample_species_dict$find(rownames(my_PC_df)), levels=ordered_species)
  #### Modification needed for the clade_tissue run ####
  my_PC_df$tissues = sub(".*_", "", as.vector(my_PC_df$tissues))
  #####
  #Generate a dictionary with PC and percentage of variance explained
  explained_variance_dict = hashmap(seq(1, length(splsda.srbct$explained_variance$X)), round(splsda.srbct$explained_variance$X*100, 2))
  
  #create a name vector which I use only for one run, to get the legend exactly as I need it:
  my_fake_species_colors = rep("black", length(my_species_colors))
  names(my_fake_species_colors) = names(my_species_colors)

  ####### Select all the tissues PCs. For many it will be only two, for one it will be 3  
  tissue_PCs = all_tissue_PCs[[query_tissue]]
  for (round in seq(0,length(tissue_PCs)-1)) {
    if (round==0 & length(tissue_PCs)==1) { #If there is only one component, select that and the following one.
      first_PC=tissue_PCs[1]; second_PC=tissue_PCs[1]+1;
    } else if (round==1) { #If there are exactly the two components, select them.
      first_PC=tissue_PCs[1]; second_PC=tissue_PCs[2];
    } else if (round==2){ #If there are more than two components, make 2 plots.
      first_PC=tissue_PCs[2]; second_PC=tissue_PCs[3];
    } else {
      next
    }
    PC1=paste0("PC", first_PC)
    PC2=paste0("PC", second_PC)
    
    PC_plot = ggplot() +
      geom_point(data=as.data.frame(my_PC_df),
                 aes_string(x=PC1, y=PC2,
                     color="tissues",
                     fill="tissues",
                     shape="species"), size=2, stroke=0.8) +
      theme_bw() +
      xlab(paste0("sPLS-DA comp ", first_PC, ": ", explained_variance_dict$find(first_PC), "%")) +
      ylab(paste0("sPLS-DA comp ", second_PC, ": ", explained_variance_dict$find(second_PC), "%")) +
      theme(axis.title = element_text(color="black", size=14),
            axis.text = element_text(color="black", size=12),
            legend.text = element_text(color="black", size=12),
            legend.title = element_text(color="black", size=13)) +
      scale_colour_manual(values=my_color_vector) + #this is great because I can have named vectors
      scale_fill_manual(values=my_color_vector) +
      scale_shape_manual(name = "Species", values=my_shapes_vector) +
      guides(color=guide_legend(title="Tissues"), fill=FALSE, shape=guide_legend(title="Species"))
    
    if (i==1) {
      my_legend = cowplot::get_legend(PC_plot)
    }
    PC_plot = PC_plot + guides(shape=FALSE, color=FALSE, fill=FALSE)
    all_PC_plots[[i]] = PC_plot
    i = i+1
  }
}
#Compose final plot
# splda_plot = plot_grid(plotlist = all_PC_plots[2:length(all_PC_plots)],
#                        ncol=3, align="hv")
splda_plot = plot_grid(plotlist = all_PC_plots,
                       ncol=3, align="hv", labels=c("A","B","C","D","E","F","G","H","I"))

legend_plot = plot_grid(my_legend, NA, ncol=1, rel_heights = c(1,0.5))

final_plot = plot_grid(splda_plot, legend_plot, ncol=2, rel_widths = c(1,0.1))
print(final_plot)

pdf("/Users/federica/Documents/CRG_PhD/bilaterian_GE/Images/Images_from_R/SupFig5-v1.pdf", width=12, height=14)
print(final_plot)
dev.off()
```
