general_paths:
  data: "/users/mirimia/fmantica/projects/bilaterian_GE/data"
  downloaded: "/users/mirimia/fmantica/projects/bilaterian_GE/downloaded"
  src: "/users/mirimia/fmantica/projects/bilaterian_GE/src"
  conda_envs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/conda_envs"

paths:
  broccoli: "/users/mirimia/fmantica/projects/bilaterian_GE/data/broccoli"
  database: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB"
  genome_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/genomes"
  gtf_ref_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/gtf/ref"
  gtf_master_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/gtf/master"
  exint_ref_dir: "/users/mirimia/fmantica/projects/bilaterian_GE/data/DB/exint/ref"
  geneID_params: "./geneID_params.txt"  
  problematic_genes: "/users/mirimia/fmantica/projects/bilaterian_GE/data/broccoli/BmA_version1/corrected_gtfs/problematic_genes-original_geneIDs.txt"

tools:
  broccoli_main: "/users/mirimia/fmantica/software/Broccoli-master-2/broccoli.py"
  get_exint_fasta: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_exint_file.pl"
  compute_prot_len: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/compute_prot_len.py"
  mafft: "/users/mirimia/fmantica/software/src/MAFFT_V2.0/mafft.bat"
  compute_prot_overlap: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/protein_overlap.py"
  compute_sim_score: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/ProtSim_from_Aln.pl"
  target_matched_portion: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/target_matched_portion.py"
  get_chimeric_clusters: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/Get_chimeric_GCLs.pl"
  split_clusters: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/split_cluster_file.pl"
  get_sim_scores_chimeric: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_aln_target_gene_v2.pl"
  get_longest_aln: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_longest_aln.pl"
  get_exon_pos_aln: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_exon_pos_aln.pl"
  get_first_last_ex_aln: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_first_last_exaln.pl"
  get_excoords: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_excoords.pl"
  get_ex_path: "/users/mirimia/fmantica/projects/bilaterian_GE/src/pl/get_ex_path.pl"
  get_aa_position: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/get_exon_aa_coords.py"
  align_chimeric_OG: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/align_chimeric_OG.py"
  get_chimeric_aligned_region: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/get_chimeric_aligned_region.py"
  classify_chimeric_genes: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/classify_chimeric_genes.py"
  generate_brochi_geneIDs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/generate_brochi_geneIDs.py"
  correct_ref_gtf: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/correct_ref_gtf.py"
  correct_master_gtf: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/correct_master_gtf.py"
  correct_gene_orthogroups: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/correct_gene_orthogroups.py"
  format_orthopairs: "/users/mirimia/fmantica/projects/bilaterian_GE/src/py/format_orthopairs-v1.py"

variables:
  all_species: ["Hs2", "Mm2", "Bt2", "Mdo", "Gga", "Xtr", "Dr2", "Cmi", "Bla", "Spu", "Dme", "Eba", "Aae", "BmA", "Tca", "Ame", "Bge", "Cdi", "Sma", "Obi"]
  my_version: "BmA_version1"
  gene_num: ["two_genes", "more_genes"]
  invertebrate_species: ["BmA", "Eba", "Bge", "Sma", "Ame", "Bla", "Obi", "Tca", "Aae", "Cdi", "Spu"]
  seqsim_cutoff: 0.30
  human_match_cutoff: 0.25
  overlap_stringency: 0.60
  min_aligned: 10
